### ISSUE TITLE
音声信号処理・無線通信工学本

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#100]
## ネタ

- 信号処理の基本
- 折り返し雑音
- サンプリング定理
- 高速フーリエ変換
- FIR/IIRフィルタの原理と設計・実装法
- AM変調・SSB変調
- 包絡線検波
- プロダクト検波
- ヘテロダイン現象
- 自動利得制御
- モールス信号の読み取り

**Comment by JG1VPP** [comment]
## 実装言語

〇〇で学ぶ音声信号処理・無線通信工学

- golang
- Haskell
- TypeScript

### 棄却

- C/C++
- Rust
- OCaml

**Comment by jucky154** [comment]
julia

**Comment by JG1VPP** [comment]
[LuaLaTeXのテンプレート](https://github.com/nextzlog/.github/tree/master/book)はあるので、どうぞ自由に執筆してください

**Comment by JG1VPP** [comment]
[Haskellで実装する信号処理と制御理論](http://pafelog.net/wave)

**Comment by JG1VPP** [comment]
制御工学の先生に薦められてMATLAB/Simulinkを始めたら世界が360度変わりましたね...というわけで [JG1VPP/wave](https://github.com/jg1vpp/wave)

**Comment by jucky154** [comment]
360度回転しているので, そのままMATLAB反対派なのでは…

**Comment by JG1VPP** [comment]
モデル予測制御の概要から始まり、カスケード制御・状態空間モデルの特異値分解の重要性・ナイキスト線図・ロバスト安定性まで話を広げた勉強資料を構想中。実は、既に骨子はできているが、図を用意できていない。
