### ISSUE TITLE
ZyLOでpanicハンドリング(Question)

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#105]
## 問題意識
CW解析プラグインは、たまにzLogごと落ちる
https://github.com/nextzlog/todo/issues/102　や　https://github.com/nextzlog/todo/issues/93#issuecomment-1271848753
で自分がタイミングを理解し、再現できるものは解決したと思われるが、それ以外にも落ちるタイミングがある可能性がある…
（というか、やっている感じありそう）

## 解決方法
https://text.baldanders.info/golang/stack-trace-and-panic-handling/ や　https://qiita.com/nayuneko/items/9534858156dfd50b43fb
このようなpanicハンドリングを適切な位置に設定し、テキストエディタ形式で吐き出すようにしておくのが開発者側には必須だと思われる（そのテキストをissueに貼ってもらうのでもよい）

これはZyLOでも使えますか？（CW解析DLLの場合は、おそらく録音関数を作るところや、解析する関数のところに入れればよい？）

**Comment by JG1VPP** [comment]
まず前提として、panicはハンドリングすべきではないというのは置いておいて、既にZyLOでは、イベントハンドラの中でpanicが発生した際に、それをダイアログで通知するようになっているはずです。

**Comment by JG1VPP** [comment]
基本的には、ソースコードのリファクタリングを行なってください。モールス信号のデコードは、ライブラリを使用してください。既に、`zylo`パッケージは公開試験中であり、その中に、デコーダが含まれる予定です。

**Comment by jucky154** [comment]
前回の　[この問題](https://github.com/nextzlog/todo/issues/93)とかもpanicが発生しているので、ダイアログ表示されるはずですけど、何も出ずに落ちたんですよね…

大体のwincを使ったプラグイン、自分でも原因不明のタイミングで落ちる（zlogごと　＆　ダイアログも出さない）んですよね…
そのため、原因もよくわかっていないので、再現もできず、その後まぁ動くからいいかみたいなノリでそのまま放置している部分があります…

ちなみに今日も無線機で実際に接続して使ったら、急に落ちました。
[この問題の修正](https://github.com/nextzlog/todo/issues/102)をしていないバージョンなので、それが原因かもしれませんが、前の結果表示からそんなに時間経っていないはずなので、そんなに長いデータが流れたように思えないんですよね…
実際のモールス音、ノイズばかりの時の挙動は再現性が…

（ちなみに無線機接続の場合は解析は回りましたけど、意味のある解析はできませんでした… 信号が弱すぎで… その後落ちました…　こういう解析が難しい音声は、EとかTが無限配列されますけど、そのへんで文字列が長いものをlistviewにしようとしたから落ちたのか？？

**Comment by JG1VPP** [comment]
それはwincを使っているからではなくgoroutineを独自に使っているからでしょう。goroutineの内部で発生したpanicはZyLOで捕捉されることはありません。goroutineを重点的に調査してください。また、一般に、堅牢な設計のソフトウェアはデバッグもしやすく、高品質です。

**Comment by JG1VPP** [comment]
まずは、意識してコードの行数を減らしましょう。高機能にするより、堅牢な設計を目指してください。

**Comment by JG1VPP** [comment]
ZyLOプラグインの適正な行数は100行を想定しています。Maplotプラグインで130行、最も高機能なリアルタイムコンテストプラグインでも250行程度なので、参考にしてください。

**Comment by jucky154** [comment]
抜本的なCW解析プラグインの修正を行います

**Comment by JG1VPP** [comment]
まずは、`decoder.go`と`symbols.go`を配置して、それを使ってください。これらは、`zylo`パッケージに収録予定です。これにより、大幅に本体のソースコードの行数が減り、見通しが良くなるはずです。

**Comment by JG1VPP** [comment]
関数内で発生した`panic`を捕捉するための`zylo.DisplayPanic`関数を用意しました。
