### ISSUE TITLE
CWサンプル音声の整備

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#107]
## 問題意識

CWデコーダの開発で指標となる短時間のモールス信号(BFO)の波形が欲しい。

## 解決方法

解読の容易なものと困難なものを、それぞれ10秒ずつの音声データを用意する。

**Comment by JG1VPP** [comment]
@jucky154 お願いします

**Comment by jucky154** [comment]
ただいま、研究の方の作業をしておりますので、それが終わり次第対応します

**Comment by jucky154** [comment]
結構、多種多様なデータを入れておきました
実際には`jissai.mp3`のように前後に完全に無音（たまに「ザッ」と入る）が入ります
それは無線機が送信状態（semibreakなら、逆にfullなら「ザッ」と入るのが頻繁にあります）になっているので、受信音もなく・基本的には無線機とPCを繋いでいる場合は、送信音も入らない（入力ラインには）ので、無音です。

**Comment by jucky154** [comment]
テストデータはmp3よりwavの方がいいですか？

**Comment by jucky154** [comment]
wavに修正されました。
