### ISSUE TITLE
プロダクト検波によるモールス信号解読

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#108]
## 問題意識

[モールス信号の自動解読 #91](https://github.com/nextzlog/todo/issues/91)で実現した解析アルゴリズムは信号のパワーを計算し、LPFで平滑化して目的信号とする方式だったが、S/N比に難がある。

## 解決方法

別の方式として、プロダクト検波回路を模倣したアルゴリズムも考えられる。容易に実装できるので、試してみる。

**Comment by JG1VPP** [comment]
## アルゴリズム

以下、搬送波とは、BFOにより得られた可聴信号を指す。

1. FFTで搬送波の周波数を推定する
2. 搬送波と同じ周波数の正弦波との乗算を行った結果をLPFに通す
3. 搬送波と同じ周波数の余弦波との乗算を行った結果を位相を90度進めてLPFに通す
4. 2と3の信号を加算してモールス信号を取り出す

**Comment by JG1VPP** [comment]
プロダクト検波の利点として、BPFに頼ることなく良好な周波数分離特性を得られるはず。また、LPF(IIRフィルタ)を加味しても計算量がO(n)で済むので高速に処理できる。

**Comment by JG1VPP** [comment]
これまでの解析アルゴリズムは包絡線検波の類型と言えそうですね。ただ、信号のパワーを求めてから平滑化しているので、その点が特徴的です。

**Comment by jucky154** [comment]
> 3. 搬送波と同じ周波数の余弦波との乗算を行った結果を位相を90度進めてLPFに通す

は乗算を行なって出てくる`2omega`(2倍の角周波数）の結果に対する90度進めるということですね…（手元で数式を確認していたところです）

つまり、`f_s:サンプリング周波数, `f_b:FFTで出てくる周波数`とすると、`2*f_s/f_b*1/4`(2倍は乗算で2倍の周波数になるので、f_bで点数に変えて、1/4で90度の点数にする）点進めたものを足し合わせればいいんですね。

**Comment by jucky154** [comment]
こんな感じですかね？　
```Go
func (d *Decoder) Decode(signal []float64) (result string) {
 	smooth_sin := equalizer.NewLowPass(d.fs, RATIO*d.fq, LPF_Q)
	smooth_cos := equalizer.NewLowPass(d.fs, RATIO*d.fq, LPF_Q)
  convert_diff := int((2.0*d.fs)/(4.0*d.fq))
  inverse_sample := 1.0/d.fs
  pi = math.Pi
 
  signal_mix := make([]float64, len(signal) - convert_diff)
  signal_cos := make([]float64, len(signal))
  
	for i, val := range signal {
		val -= signal[0]
    val_sin := val * math.Sin(2.0 * pi * d.fq * float64(i) * inverse_sample)
    val_sin = smooth_sin.Apply(val_sin)
    
    val_cos := val * math.Cos(2.0 * pi * d.fq * float64(i) * inverse_sample)
    val_cos = smooth_sin.Apply(val_cos)
    signal_cos[i] = val_cos
    
		
    if i => convert_diff {
        signal_mix[i-convert_diff] = val_sin + signal_cos[i-convert_diff]
      }
	}
	return d.detect(signal_mix)
}
```

**Comment by JG1VPP** [comment]
こんな感じですね:

```go:decoder.go
func (d *Decoder) Decode(signal []float64) (result string) {
	smooth1 := equalizer.NewLowPass(d.fs, RATIO, LPF_Q)
	smooth2 := equalizer.NewLowPass(d.fs, RATIO, LPF_Q)
	smooth3 := equalizer.NewLowPass(d.fs, RATIO, LPF_Q)
	smooth4 := equalizer.NewLowPass(d.fs, RATIO, LPF_Q)
	wave := make([]float64, len(signal))
	shift := int(0.5 * d.fs / d.fq)
	fmt.Println(shift, d.fs, d.fq)
	for i, val := range signal[shift:] {
		phase := 2 * math.Pi * float64(i) * d.fq / d.fs
		sin := val * math.Sin(phase)
		cos := val * math.Cos(phase)
		sin = smooth1.Apply(sin)
		sin = smooth2.Apply(sin)
		cos = smooth3.Apply(cos)
		cos = smooth4.Apply(cos)
		wave[i+shift] += sin
		wave[i] += cos
	}
	for i, val := range wave {
		wave[i] = math.Abs(val)
	}
	waveplot(wave)
	return d.detect(wave)
}
```

```go:main.go
package main

import "fmt"
const rate = 12000

func main() {
	encoder := Encoder{
		Freq: 100,
		WPMs: 10,
		Rate: rate,
	}
	tone := encoder.Tone(TextToCode("JA1ZLO"))
	signal := make([]float64, len(tone))
	for i,val := range tone {
		signal[i] = val[0]
	}
	fmt.Println(len(signal))
	decoder := Decoder{
		th:     0.3,
		fq:     100,
		fs:     rate,
		epochs: 50,
	}
	fmt.Println(CodeToText(decoder.Decode(signal)))
}
```

試してみるとわかりますが、非常に選択度が高く、逆に、高すぎるので、このままだと実用性が微妙です。

**Comment by JG1VPP** [comment]
現状だと1Hz単位でぴったりと搬送波の周波数を言い当てる必要があって、FFTだと難しいと思います。とりあえず試してみて、もし厳しすぎるようであれば、同調周波数の幅を広げる工夫をしましょう。

**Comment by JG1VPP** [comment]
具体的には、わざと局発周波数を1Hzずらして、フィルタの選択性能をフラットにする方法が考えられますね。

**Comment by JG1VPP** [comment]
具体的には、わざと局発周波数を1Hzずらして同様に検波を行なって、選択性能をフラットにする方法が考えられますね。

**Comment by JG1VPP** [comment]
切りの良い周波数ではかなり高い性能を示す一方で、素数周波数では解読できないので、位相を進める部分は真面目に実装したほうが良さそう。

**Comment by JG1VPP** [comment]
サンプリング周波数とモールス信号の周波数によって性能が変化しますね。正弦波の数値計算や位相の進め方は、何かしら工夫が要るかも知れません。

**Comment by JG1VPP** [comment]
`encoder.go`でトーンの正弦波の位相が連続するように修正すると周波数が端数でもデコードできるようになりました。

**Comment by jucky154** [comment]
上で解決されたようなので無意味になってしまいましたが、モールス信号のデコードに関する論文を調べ始めたところだったので、一部貼っておきます

Wang, X.; Zhang, M.; Zhou, H.; Lin, X.; Ren, X. A Robust Real-Time Automatic Recognition Prototype for Maritime Optical Morse-Based Communication Employing Modified Clustering Algorithm. Appl. Sci. 2020, 10, 1227. https://doi.org/10.3390/app10041227
↑誤り訂正をしている

Q. Shanhu, L. Hongbo and Z. Xu, "Morse Recognition Algorithm Based on K-means," 2019 Cross Strait Quad-Regional Radio Science and Wireless Technology Conference (CSQRWC), 2019, pp. 1-2, doi: 10.1109/CSQRWC.2019.8799149.
↑ K-Meansでモールス信号をデコードする先行研究

**Comment by JG1VPP** [comment]
テストコード:

```go
const freq = 501
const rate = 450 * 100

encoder1 := Encoder{
	Freq: freq,
	WPMs: 10,
	Rate: rate,
}
encoder2 := Encoder{
	Freq: freq - 20,
	WPMs: 20,
	Rate: rate,
}

tone1 := encoder1.Tone(TextToCode("JA1ZLO"))
tone2 := encoder2.Tone(TextToCode("CQ DE JA1YWX JA1YWX"))

signal := make([]float64, len(tone2))

amp1 := 1.0
amp2 := 0.05

for i, val := range tone1 {
	signal[i] += amp1 * val[0]
}

for i, val := range tone2 {
	signal[i] += amp2 * val[0]
}
```

**Comment by jucky154** [comment]
> `encoder.go`でトーンの正弦波の位相が連続するように修正すると周波数が端数でもデコードできるようになりました。

どういうコードになりました？

**Comment by jucky154** [comment]
https://gist.github.com/jucky154/deb981715f8d7dfd08546a6b534ba481

これでは適切に動いてくれなかったです

**Comment by JG1VPP** [comment]
LPFのカットオフ周波数が間違っていると思います。

**Comment by jucky154** [comment]
![smoothed](https://user-images.githubusercontent.com/58735989/195145621-baa2287d-33b5-4c7f-89e1-54f2167204a6.png)
fqを501から500にしただけで波形がここまで汚くなるのは対策を考えないといけないですね…

後ほど、実際の音源をつかってFFTして、解析にかけてみますが…

**Comment by jucky154** [comment]
一応はeasyのものをやってみましたが何故か解読できました
マジでなんで？　とはいえ、ここまで波形が汚いので、なんらかの改良が必要な気がします

![smoothed](https://user-images.githubusercontent.com/58735989/195155890-4559b330-b039-4a04-8c5f-d2361a5af0b8.png)

**Comment by jucky154** [comment]
逆にFFTの点数を増やせばdeltaFも小さくなって良いかと思って、下のようにしたのですが、逆に解読に失敗しました…
もう少し、周波数選択性の改良が必要そうです
```
	var opt spectral.PwelchOptions

	opt.NFFT = 65536
	opt.Noverlap = 16384
	opt.Window = nil
	opt.Pad = 65536
	opt.Scale_off = false
```

**Comment by JG1VPP** [comment]
オールパスフィルタで位相を90度進める代わりに、単純に配列をシフトさせると、サンプリング周波数とトーン周波数の組み合わせによっては、却って信号を打ち消す可能性があります。そもそも、プロダクト検波では、正弦波と余弦波を用意する必要はなくて、搬送波の位相が既知であれば、その位相に合わせた正弦波と乗算することで、最大の利得を得られます。

多少の利得の低下は許容して、正弦波と余弦波で試してみて、最も利得の大きな方を検波出力とするのではどうでしょうか？

**Comment by jucky154** [comment]
今回は余弦波が解読に成功しました。
しかし、コールサインの最後の「Z」が本当に解読できた？　みたいな形をしているので不安はありますね（いろいろ余計なピョコっと出ているものもありますし）

**cosを使った場合**
![smoothed](https://user-images.githubusercontent.com/58735989/195369251-a1bc495d-dead-44c5-a940-53fb0bcab7e1.png)

**sinを使った場合**
![smoothed](https://user-images.githubusercontent.com/58735989/195369500-5df6e191-01ef-40ed-9d28-c9af88578a21.png)

**Comment by jucky154** [comment]
https://gist.github.com/jucky154/36c83c09f3b3cff9de664503781aeab0
Twitterでの議論にあった通り、
TFFT→特定周波数の値のslice→kmeansとかで二値化したslice→信号として入力
という形で信号検知をしてみました
![smoothed](https://user-images.githubusercontent.com/58735989/196235880-33a6b919-85b3-4a18-b62e-e6f9dd0e0f7f.png)

**Comment by JG1VPP** [comment]
スペクトログラムの周波数分解能はFFTとSTFTで揃っていますか？揃っていないなら、修正が必要です

**Comment by JG1VPP** [comment]
ですが、コードの修正と効率化は私の方で行うので、大丈夫です。

**Comment by jucky154** [comment]
一応、gistに上げたものは確かですがどちらのFFTもSTFTも4096点でやっているので周波数分解能は一致していると思います.
また、テストデータでやったところそれなりにできそうな雰囲気でした. (VPPさんの方でも確認してもらえると嬉しいです）
ただし, veryveryhardとした途中で音が消えているようなものは解読できませんでした.（仕方がない気もしますし、一部は解読できているので、それに？をつけて送信すれば良さそうな感じがします）

**Comment by JG1VPP** [comment]
FFTの計算量はNlogNで、時系列の長さが長くなるほど無視できません。ここはそこまで精度が要求される場面でもないので、STFTで算出したスペクトログラムからピーク周波数を求めれば十分だと思います。
