### ISSUE TITLE
JARL ver2.1のチェックログへの対応

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#110]
## 問題意識
https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/e-log.html
チェックログへの対応が簡単になったらしいです…

その都合で, おそらく今後提出されるJARLサマリーシートにもこういうのが含まれてくるので対応が必要と思われます…
## 解決方法
ATS-4の場合は[一般に想定される手法](https://github.com/jr8ppg/zLog/issues/364#issuecomment-1278288812)（つまりは, 部門外のものが含まれていても特に気にせずに計算）で行われているので、`#CHECKLOG`という文字列は無視するとかで対応可能だと思われます。

**Comment by JG1VPP** [comment]
JARL指定の交信記録の書式に限り、#CHECKLOGで始まる行を無視する機能をQxSLに追加しました。なお、zLog等の書式では対応していません。
