### ISSUE TITLE
スペクトログラムによるモールス信号の解読

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#111]
https://github.com/nextzlog/todo/issues/108#issuecomment-1281159877

## 実装内容

1. STFTでスペクトログラムを生成（その際に可能な限り時系列の長さを抑制）
2. スペクトログラムを時間方向に合計して周波数成分の強さを計算
3. 可聴域で最も振幅の大きな周波数をピーク検知により取得
4. スペクトログラムから目的の周波数成分を抽出
5. Kmeansにより2値化
6. エッジ検出（ここでピーク検知を行う必要はない）
7. Kmeansにより短点・長点の長さを解析
8. 短点・長点・空白を抽出してモールス信号を得る
9. 元の文字列を得る

## テスト

パイル時の音声(`pileup001.wav`)でテストした結果:

![image](https://user-images.githubusercontent.com/23717324/196459023-f0a951ac-b4f9-4c41-a8ff-7969f20209cf.png)
![image](https://user-images.githubusercontent.com/23717324/196459048-79e7f864-b07b-4ece-be54-227e456fa6a6.png)
![image](https://user-images.githubusercontent.com/23717324/196459082-fc17da91-64a6-482e-b368-2a466cf56d11.png)

**Comment by JG1VPP** [comment]
パイル時の音声(pileup003.wav)でテストした結果:

![image](https://user-images.githubusercontent.com/23717324/196463092-f36f62ce-f270-4757-843c-f1ae8ab48985.png)
![image](https://user-images.githubusercontent.com/23717324/196463113-9ae3acda-0ad1-43ad-863ebe9b13a871e2.png)

フェージングでしょうか？別途、AGCのアルゴリズムを実装すると解消できるかも知れません。Future Workで良いと思います。

**Comment by JG1VPP** [comment]
パイル時の音声(pileup003.wav)でテストした結果:

![image](https://user-images.githubusercontent.com/23717324/196463434-ef7d0cfc-5659-4275-86f0-8e7aef9d1e1d.png)
![image](https://user-images.githubusercontent.com/23717324/196463449-30394a67-8cd1-472f-901b-73c3c689cd81.png)

フェージングでしょうか？別途、AGCのアルゴリズムを実装すると解消できるかも知れません。Future Workで良いと思います。

**Comment by JG1VPP** [comment]
パイル時の音声(`pileup003.wav`)でテストした結果:

![image](https://user-images.githubusercontent.com/23717324/196463434-ef7d0cfc-5659-4275-86f0-8e7aef9d1e1d.png)
![image](https://user-images.githubusercontent.com/23717324/196463449-30394a67-8cd1-472f-901b-73c3c689cd81.png)

フェージングでしょうか？別途、AGCのアルゴリズムを実装すると解消できるかも知れません。Future Workで良いと思います。

**Comment by JG1VPP** [comment]
パイル時の音声(`pileup004.wav`)でテストした結果:


![image](https://user-images.githubusercontent.com/23717324/196464339-a961589d-fa80-4f65-9d13-0b2654ab17b8.png)
![image](https://user-images.githubusercontent.com/23717324/196464415-8aa59d13-2b73-49b3-b9a3-d038ed0bc58e.png)
![image](https://user-images.githubusercontent.com/23717324/196464369-527f3a9b-d3b1-4663-b200-8852cc27a8c4.png)

非常に癖の強い信号は読めないことがある。もしくは、空白の時間は短点・長点とは別に最適化した方が良さそうですね。

**Comment by JG1VPP** [comment]
空白の扱いには工夫が必要そうですが、概ね実用化できるレベルになって来たと思います。100%読める必要はないので、可視化を工夫することで、非常に実用性の高い機能になると思います。

**Comment by jucky154** [comment]
空白系の問題はおそらく縦振りのJAの間がない（人間の場合はそうなっていても理解できてしまい、相手も直さない）などはありえそうですね
可視化は考えた方が良さそうですね

無味乾燥に文字列を並べてもという感じですし…
CW skimmerのようにスペクトログラムをなんとか描画してその横に文字を並べるとかでしょうか（そうなると描画の画像を作るのに時間がかかって無意味になりそうな気もしますし… 難しい）

あとはやはりACAG中に後輩から言われたのはストリーミングで解釈されないので、すぐに応答できない・無音を１秒待つのは渋いとのことなので、ユーザーが任意のタイミングで停止・解読させる機能は必要そうですね

**Comment by JG1VPP** [comment]
フェージングに対しては、混合ガウス分布モデルの導入で解消できるようにも思います。Kmeansで振幅の平均値を計算し、更にEMアルゴリズムを行うことで、振幅の分散を求めます。

**Comment by JG1VPP** [comment]
> 無味乾燥に文字列を並べてもという感じですし… CW skimmerのようにスペクトログラムをなんとか描画してその横に文字を並べるとかでしょうか（そうなると描画の画像を作るのに時間がかかって無意味になりそうな気もしますし… 難しい）

ラベルで短点と長点を可視化すれば十分です。

> あとはやはりACAG中に後輩から言われたのはストリーミングで解釈されないので、すぐに応答できない・無音を１秒待つのは渋いとのことなので、ユーザーが任意のタイミングで停止・解読させる機能は必要そうですね

別に無音と有音の区別をする必要がないのであれば、例えば過去10秒間の文字列をそのまま垂れ流すのでも良いと思います。

**Comment by jucky154** [comment]
> ラベルで短点と長点を可視化すれば十分です。
これは、モールスの解読された短点＋長点の羅列と文字列をListで表示する感じですか？


> 別に無音と有音の区別をする必要がないのであれば、例えば過去10秒間の文字列をそのまま垂れ流すのでも良いと思います。
そうしてしまうと応答が終わるギリギリに解読が終了してしまうタイミングがあるので、ボタンで割り込んだ方が良くないですか？

**Comment by jucky154** [comment]
以下のような感じで有音時間でも1秒に一回デコードをし, 解析結果が良くなるようにすればストリーミングで解釈される & それなりの精度でいけるというのを満たさないでしょうか？　
コンテスト中でも相手が送信中でも解読されるので、相手が送信中でも入力できタイムラグ少なく応答可能できます（コンテストで求められそう）

```Go
	onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {
		second_cnt := rate_sound/framecount //１秒に何回これが呼ばれるか
		Signalint := make([]int32, framecount)
		buffer := bytes.NewReader(pSample)
		binary.Read(buffer, binary.LittleEndian, &Signalint)
		for _, val := range Signalint {
			ringbuffer.Value = float64(val)
			ringbuffer = ringbuffer.Next()
		}
		cnt := 0
		if IsSilent(ringbuffer, rate_sound) {
			// 録音データが入っているかどうかのif
			if len(pCapturedSamples) > length_limit {
				go decode_main(pCapturedSamples, rate_sound)
			}
			pCapturedSamples = make([]int32, 0)
			for i := 0; i < length_ring; i++ {
				buffer_int32[i] = int32(ringbuffer.Value.(float64))
				ringbuffer = ringbuffer.Next()
			}
			cnt = 0
			pCapturedSamples = append(pCapturedSamples, buffer_int32...)
		} else {
			pCapturedSamples = append(pCapturedSamples, Signalint...)
			cnt += 1
			// 有音の１秒ごとにデコードする（最初は解析が良くないかもしれないがだんだん良くなっていく.）
			if cnt > second_cnt {
				go decode_main(pCapturedSamples, rate_sound)
				cnt = 0	
			}		
		}
	}
```

**Comment by JG1VPP** [comment]
なお、Issueのタイトルと別の話題に触れる場合は、Issueを立ててください
