### ISSUE TITLE
ストリーミング的なモールス解読

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#112]
## 問題意識
コンテストでは素早い応答が求められる
例えば、[phoneでも応答の仕方](https://twitter.com/JJ2JQF/status/1579446806811144192)を規定してくる場合もある
現状のCW解析では何秒か待つ必要があり、その点に困難さがある

## 解決方法
以下のような実装方法で良いだろうか
```Go
	onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {
		second_cnt := rate_sound/framecount //１秒に何回これが呼ばれるか
		Signalint := make([]int32, framecount)
		buffer := bytes.NewReader(pSample)
		binary.Read(buffer, binary.LittleEndian, &Signalint)
		for _, val := range Signalint {
			ringbuffer.Value = float64(val)
			ringbuffer = ringbuffer.Next()
		}
		cnt := 0
		if IsSilent(ringbuffer, rate_sound) {
			// 録音データが入っているかどうかのif
			if len(pCapturedSamples) > length_limit {
				go decode_main(pCapturedSamples, rate_sound)
			}
			pCapturedSamples = make([]int32, 0)
			for i := 0; i < length_ring; i++ {
				buffer_int32[i] = int32(ringbuffer.Value.(float64))
				ringbuffer = ringbuffer.Next()
			}
			cnt = 0
			pCapturedSamples = append(pCapturedSamples, buffer_int32...)
		} else {
			pCapturedSamples = append(pCapturedSamples, Signalint...)
			cnt += 1
			// 有音の１秒ごとにデコードする（最初は解析が良くないかもしれないがだんだん良くなっていく.）
			if cnt > second_cnt {
				go decode_main(pCapturedSamples, rate_sound)
				cnt = 0	
			}		
		}
	}
```

**Comment by JG1VPP** [comment]
断片的なコードなので、理解できていない部分もありますが、音を検出して、録音を開始した後、周期的にデコードを行って、また、UIにはその結果を一時的なものとして表示した後、無音になった際には、結果を確定させて表示させれば良いと思います。確定した結果は残し続ければ良いでしょう。

**Comment by jucky154** [comment]
**メモ**
CQモードと呼び回りモードで分けるべきかも
CQを出す側ならば、自分の送信は無音であり、相手の呼び出し後に無音である可能性が高い
しかし、呼び回る側だとCQ出した後にすぐに応答があるため、無音が担保されずすごい長さの解析を必要となり、make([]float64,len)が落ちる可能性がある

よって、CQモードだと上のように音が始まると一定周期で解析、無音で確定とし、呼び周りモードだとある一定時間のリングバッファを一定時間より短い周期で解析に回すとかにした方がよさそう

**Comment by jucky154** [comment]
https://github.com/nextzlog/todo/issues/114
でストリーミング的なモールス解読は解決した
呼び周りにどう対応していくは検討課題（一応、現状のものでも最大の計測時間というのが設定されているので問題ないと言えばそれはそう）
