### ISSUE TITLE
モールス信号解読プラグインのUI改善

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#114]
## 問題意識

モールス信号解読プラグインのUIが熟れていない。

## 解決方法

ユーザビリティを考慮しつつ模索する。

**Comment by JG1VPP** [comment]
## 提案

最初のリリースでは、後々の派生も期待して、最もシンプルな形を追求すべき。つまり、

- グラフの表示は削除。
- 周波数の表示も不要。

その上で、以下の要素だけを備えたUIに再構成する。

- デバイスの切り替え
- 解読した文字列を表示するリスト

動作は以下の通り。

1. 音を検知すると、モールス信号の解析を開始する。
2. 音が続く限り、1を繰り返しつつ、リストの末尾に解読中の文字列を表示・更新する。
3. 音が途切れたら、解読結果を確定し、その時点でリストに表示されている文字列は、リストに残し続ける。

リストの末尾に文字列を追加する際は、周波数でソートする。

- デコーダが自動的にソートするので、そのまま受け取れば良い。
- 周波数自体に特に意味はないので、周波数の情報を可視化する必要はない。

**Comment by jucky154** [comment]
それに合わせて修正しているのですが
https://gist.github.com/jucky154/7095bfbd76bf5a1cf3887e3906aa42e1
というコードでは落ちてしまいました

以下だと「ここ」が表示され
```Go
	reiwa.DisplayModal("ここ")
	decode_result := decoder.Read(souce_arr)
```

以下だと「ここ」が表示されません
```Go
	decode_result := decoder.Read(souce_arr)
	reiwa.DisplayModal("ここ")
```

decoder側に何かありそうな気がします

**Comment by JG1VPP** [comment]
今、最新の`zbuild`を利用してみてください。状況が変わらなければ`panic`の内容をキャプチャして教えてください。

**Comment by JG1VPP** [comment]
最新の`zbuild`を利用してみてください。状況が変わらなければ、以下のようにして`panic`を捕捉してください。

```go
func foo() {
  defer reiwa.DisplayPanic()
  // do something
}
```

**Comment by jucky154** [comment]
問題が複合的に発生しているようです
最新のzbuildを使ったところ落ちなくなりましたが、音を入れたのに結果が0であるという応答が来ました
また、なぜか解析の関数が高頻度で呼ばれているようです
その辺に何かありそうです

**Comment by JG1VPP** [comment]
高頻度のくだりはよくわかりませんが、閾値の指定方法を変更しましたので、ビルドし直してください。0.5等の値で大丈夫です。

**Comment by jucky154** [comment]
**現在のコード**
https://gist.github.com/jucky154/d4b8a10d2991a1681edb3f22cd90823f

**よくわからない現象**
閾値をｐ0.5にしても画面が何も変わらないので、結果の個数を表示するように

`reiwa.DisplayModal(strconv.Itoa(len(decode_result)))`

というものを解析の関数に入れた
すると繰り返し0が表示される（つまり、解析の関数が無限に呼ばれている）

そして、最終的に以下のようなerrorがはかれました…
![error](https://user-images.githubusercontent.com/58735989/197352871-c161d8f0-51e6-4883-a0bd-3cd3d27c05da.png)

**Comment by JG1VPP** [comment]
今、修正しました。ビルドし直してください。

**Comment by JG1VPP** [comment]
`panic`の発生箇所については修正しました。ビルドし直してください。

**Comment by JG1VPP** [comment]
panicの発生箇所については修正しました。ビルドし直してください。なお、デコーダは[`cw_test.go`](https://github.com/nextzlog/zylo/blob/master/commons/morse/cw_test.go)でテストしており、特に問題なく動作しています。

**Comment by jucky154** [comment]
無音なのになぜ解析関数が呼ばれているのか、こちらでは何も解析には結果が表示されないのかを調査しないとダメですね…

**Comment by JG1VPP** [comment]
デコーダの安定性を改善しました。使用方法は[Gist](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a)も参考にしてください。

```sh
$ go mod init foo
$ go mod tidy
$ go build
$ ./foo
$ go test
```

**Comment by JG1VPP** [comment]
デコーダの安定性を改善しました。使用方法は[Gist](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a)も参考にしてください。

```sh
$ go mod init foo
$ go mod tidy
$ go build
$ ./foo
$ go test
```

なお、最新の`zbuild`は`zbuild compile`を実行するだけで常に最新のZyLOをリポジトリから入手する仕様です。

**Comment by JG1VPP** [comment]
> 無音なのになぜ解析関数が呼ばれているのか、こちらでは何も解析には結果が表示されないのかを調査しないとダメですね…
> 
> 解析関数が高頻度で呼ばれるのは本当に謎ですね…（recv関数周りは前回とほぼ変えていないので…）

`IsSilent`関数の単体テストをすれば良いと思います。気になった点ですが、`Freq`には、どんな周波数が格納されますか？

```go
Power, Freq := spectral.Pwelch(buffer_float64, float64(sampling_freq), &opt)

mean := 0.0
cnt := 0
peakPower := 0.0
for i, val := range Freq {
	if val > 200 && val < 2000 {
		mean += Power[i]
		cnt += 1
		if Power[i] > peakPower {
			peakPower = Power[i]
		}
	}
}
```

200Hzから2000Hzまでというのは、周波数の範囲をハードコーディングしている訳ですが、FFTで得られる配列の後半は折り返されて負の周波数成分になる点に注意してください。折り返しによって、意図せずに直流成分を拾っている可能性はありませんか？

**Comment by JG1VPP** [comment]
最新のZyLOでは、`IsSilent`関数の代わりに、`morse.Monitor`を使用することができます。

```go
encoder := morse.Encoder{
	Freq: 600,
	WPMs: 10,
	Rate: 48000,
}
decoder := morse.Decoder{
	Thre: 0.1,
	Bias: 2,
	Iter: 50,
	STFT: &stft.STFT{
		FrameShift: 48000 / 100,
		FrameLen:   4096,
		Window:     window.CreateHanning(4096),
	},
}
tone := encoder.Tone(morse.TextToCode(TEXT))
monitor := morse.Monitor{
	Decoder: decoder,
	Squelch: 10,
}
mute := make([]float64, 1024)
texts1, mute1 := monitor.Read(tone)
texts2, mute2 := monitor.Read(mute)
```

`monitor.Read`関数の返り値は、解読結果と、引数で渡された信号が無音であったかの判定結果です。判定の基準は、`Squelch`により変わります。その内容は、`IsSilent`関数とほぼ同様です。

**Comment by JG1VPP** [comment]
リングバッファ自体は今まで通り使って、リングバッファを一巡したら(0.5秒程度が目安)、`monitor.Read`で解読し、2個目の返り値が`true`の場合は、結果を確定させれば良いと思います。この場合、リングバッファのリセットは不要です。

**Comment by JG1VPP** [comment]
最新のZyLOでは、`IsSilent`関数の代わりに、`morse.Monitor`を使用することができます。

```go
encoder := morse.Encoder{
	Freq: 600,
	WPMs: 10,
	Rate: 48000,
}
decoder := morse.Decoder{
	Thre: 0.1,
	Bias: 2,
	Iter: 50,
	STFT: &stft.STFT{
		FrameShift: 48000 / 100,
		FrameLen:   4096,
		Window:     window.CreateHanning(4096),
	},
}
tone := encoder.Tone(morse.TextToCode(TEXT))
monitor := morse.Monitor{
	Decoder: decoder,
	Squelch: 10,
}
mute := make([]float64, 1024)
texts1, mute1 := monitor.Read(tone)
texts2, mute2 := monitor.Read(mute)
```

### 返り値

`monitor.Read`関数の返り値は、解読結果と、引数で渡された信号が無音であったかの判定結果です。

### 解読結果

`monitor.Read`関数を呼ぶと、音声が蓄積されます。蓄積された音声に対する解読結果が返されます。

### 無音判定

判定の基準は、`Squelch`により変わります。その内容は、`IsSilent`関数とほぼ同様です。

### 利用方法

リングバッファ自体は今まで通り使って、リングバッファを一巡したら(0.5秒程度が目安)、`monitor.Read`で解読し、2個目の返り値が`true`の場合は、結果を確定させれば良いと思います。この場合、リングバッファのリセットは不要です。

**Comment by JG1VPP** [comment]
最新のZyLOでは、`IsSilent`関数の代わりに、`morse.Monitor`を使用することができます。

```go
encoder := morse.Encoder{
	Freq: 600,
	WPMs: 10,
	Rate: 48000,
}
decoder := morse.Decoder{
	Thre: 0.1,
	Bias: 2,
	Iter: 50,
	STFT: &stft.STFT{
		FrameShift: 48000 / 100,
		FrameLen:   4096,
		Window:     window.CreateHanning(4096),
	},
}
tone := encoder.Tone(morse.TextToCode(TEXT))
monitor := morse.Monitor{
	Decoder: decoder,
	Squelch: 10,
}
mute := make([]float64, 1024)
texts1, mute1 := monitor.Read(tone)
texts2, mute2 := monitor.Read(mute)
```

### 返り値

`monitor.Read`関数の返り値は、解読結果と、引数で渡された信号が無音であったかの判定結果です。

### 解読結果

`monitor.Read`関数を呼ぶと、音声が蓄積されます。蓄積された音声に対する解読結果が返されます。

### リセット

蓄積された音声は、無音を検知すると自動的に消去されます。

### 無音判定

判定の基準は、`Squelch`により変わります。その内容は、`IsSilent`関数とほぼ同様です。

### 利用方法

リングバッファ自体は今まで通り使って、リングバッファを一巡したら(0.5秒程度が目安)、`monitor.Read`で解読し、2個目の返り値が`true`の場合は、結果を確定させれば良いと思います。この場合、リングバッファのリセットは不要です。

**Comment by JG1VPP** [comment]
忘れてましたが、`monitor.MaxHold`を1以上の値に設定してください。`MaxHold`の回数だけ`monitor.Read`関数を呼び出して音声を蓄積できます。それを上回ると、無音になるまで蓄積しなくなります。

**Comment by JG1VPP** [comment]
@jucky154 これでプラグインをもっとシンプルにできますか？

**Comment by jucky154** [comment]
ZLOの方で作業（プラグインに興味がある一年生に講習会を開いて、コンテストプラグインの制作をお願いしました）があったので、今見ました。
おそらくは、プラグインをもう少しシンプルにできると思います。

**Comment by jucky154** [comment]
https://gist.github.com/jucky154/ec81d00be579e8486632fe907590ba2a

書き換えましたが、音声を入れると以下のようなpanicが出ました

![error2](https://user-images.githubusercontent.com/58735989/197397834-28ffffb3-1b21-4a1a-b5d2-4d09a9aac1ae.png)

**Comment by JG1VPP** [comment]
修正しました。ビルドし直してください。

**Comment by JG1VPP** [comment]
修正しました。`go.mod`を削除して、ビルドし直すと、最新のパッチが適用されます。

**Comment by jucky154** [comment]
解読も動き、いい感じにストリーミング的に動きましたが、なぜか文字になりませんでした
・morse.init()とかよんだ方がいいですか？
・空白がない感じでしょうか？（ストリーミング的には - というものがあったので、空白がない系ではなさそう）
![適切に解析されない](https://user-images.githubusercontent.com/58735989/197398976-57924070-d98c-4d4e-ab68-d0a389f5a586.png)

**Comment by JG1VPP** [comment]
[Gist](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a)のサンプルを動かしてみてください。`pileup001.wav`については、以下のような出力が得られるはずです。

```
.___ .._. ..___ __ _ __ . . .. _.._. ..___
JF2MTMEEI/2
.___ ... ..___ __. _.__ _.
JS2GYN
_.. . .___ ._ _____ _... ; __.. ; .
DEJA0B Z E
```

**Comment by JG1VPP** [comment]
`CodeToText`関数では、読み取れなかったモールス符号語をそのまま出力するので、空白が失われています。

**Comment by JG1VPP** [comment]
というかもはやリングバッファ使う意味ってないですよね。適当な配列を用意して、バッファとして使えば良さそう。コピー動作が無駄なんですよね。

**Comment by jucky154** [comment]
modを削除してコンパイルしても、変わらずでした

音声が上のgistではJA1ZLOと解析されることは確認しています
![test (2)-4](https://user-images.githubusercontent.com/58735989/197400963-881acbb9-d38c-45c1-85b1-ec6b2980c17f.png)

また、どういう感じで解析が動くかの動画が以下です

https://user-images.githubusercontent.com/58735989/197401026-224bf8f1-30d9-4573-b5fc-37ba2274f732.mp4

**Comment by JG1VPP** [comment]
そもそも`CodeToText`関数を呼び出してないですね

**Comment by JG1VPP** [comment]
そもそも`CodeToText`関数を呼び出してないですね。`monitor.Read`関数の返り値は、モールス信号の符号語列なので、欧文に変換する必要があります。

**Comment by jucky154** [comment]
それはそうという感じの話でした…
成功した動画を貼っておきます。（ツイートとかできるように背景にzLogを入れておきました）

https://user-images.githubusercontent.com/58735989/197402883-512bea5a-4891-4fa1-89e3-22c7d24f1b23.mp4



https://gist.github.com/jucky154/45276f2ae596ec2a7605b86ba785b956
現在のバージョンです

バグみたいな物（一度解析のwindowを閉じて再度開いたら解析が非常に不安定）があったので、いろいろ調査する必要があるなと思っています。（そのため、まだgithubの本体の方にはあげていません）
そちらの方は明日やります（明日は朝に指導教官と面談があるので、今日は寝ます）

**Comment by JG1VPP** [comment]
ちょっと表示がわかりにくいので、入力中の行にプロンプトを付けてみるのはどうでしょうか？

**Comment by JG1VPP** [comment]
閾値も強めに設定した方が良さそうですね

**Comment by JG1VPP** [comment]
ちょっと表示がわかりにくいので、入力中の行にプロンプトを付けてみるのはどうでしょうか？スケルチも閾値を引き上げた方が良さそうですね。

**Comment by jucky154** [comment]
> バグみたいな物（一度解析のwindowを閉じて再度開いたら解析が非常に不安定）
は現状考えられるのは、trueが連続できた時でもデータを確定しリストを更新してしまうので、そのせいで0.5秒でデータが上がっていくというのを繰り返している可能性がありそうです。

前がtrueで次がtrueのときは無音→無音なので更新しないとかした方がいい感じですよね

**Comment by jucky154** [comment]
@JG1VPP 
これはzylo/morse側で実装した方がいいと思うのですが、私が前実装した際には立ち上がりの問題がありました
立ち上がりの問題というのは、CW音が実際には入っているがその一定周期（ここでは0.5秒）の中では短いため、無音と判断され、次のタイミングで遅れて有音となるということです。

つまり、例えば「JA1ZLO」が最初のトンが立ち上がりの問題で消えてしまいOA1ZLOと判断されます。

そのため、わざと一つ前のバッファーもmonitorに保持しておき、初めて有音になった場合には「有音になる一つ前のバッファーも追加する」などの対策をした方がいいと考えます。
（実際、アルファ版では最初が適切に解読されないという問題があり、このような実装が行われています）

cwListener側でも一応は実装はできますけど、どうしますか？

**Comment by jucky154** [comment]
以下のように、storageを真っ白にせず、無音（？）を入れておいてもらえば解決しそう？
```Go
func (m *Monitor) Read(signal []float64) ([]string, bool) {
	if m.counter < m.MaxHold || m.MaxHold == 0 {
		m.storage = append(m.storage, signal...)
		m.counter += 1
	}
	text := m.Decoder.Read(m.storage)
	spec := fft.FFTReal(signal)
	amps := make([]float64, 0)
	for _, val := range spec[:len(spec)/2] {
		amps = append(amps, cmplx.Abs(val))
	}
	amps = amps[m.Decoder.Bias:]
	size := float64(len(amps))
	peak := funk.MaxFloat64(amps)
	mean := funk.SumFloat64(amps) / size
	if peak <= mean*m.Squelch {
		**m.storage =　signal**
		m.counter = 0
		return text, true
	} else {
		return text, false
	}
}
```
