### ISSUE TITLE
CW解読の立ち上がりの遅れ

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#116]
## 問題意識
@JG1VPP
これはzylo/morse側で実装した方がいいと思うのですが、私が前実装した際には立ち上がりの問題がありました
立ち上がりの問題というのは、CW音が実際には入っているがその一定周期（ここでは0.5秒）の中では短いため、無音と判断され、次のタイミングで遅れて有音となるということです。

つまり、例えば「JA1ZLO」が最初のトンが立ち上がりの問題で消えてしまいOA1ZLOと判断されます。

## 解決方法
そのため、わざと一つ前のバッファーもmonitorに保持しておき、初めて有音になった場合には「有音になる一つ前のバッファーも追加する」などの対策をした方がいいと考えます。
（実際、アルファ版では最初が適切に解読されないという問題があり、このような実装が行われています）

cwListener側でも一応は実装はできますけど、どうしますか？

おそらくmorse側で対応する場合は以下のように、storageを真っ白にせず、無音（? 本当はちょっと入っているかも）のsignalを入れておいてもらえば解決しそう？
```Go
func (m *Monitor) Read(signal []float64) ([]string, bool) {
	if m.counter < m.MaxHold || m.MaxHold == 0 {
		m.storage = append(m.storage, signal...)
		m.counter += 1
	}
	text := m.Decoder.Read(m.storage)
	spec := fft.FFTReal(signal)
	amps := make([]float64, 0)
	for _, val := range spec[:len(spec)/2] {
		amps = append(amps, cmplx.Abs(val))
	}
	amps = amps[m.Decoder.Bias:]
	size := float64(len(amps))
	peak := funk.MaxFloat64(amps)
	mean := funk.SumFloat64(amps) / size
	if peak <= mean*m.Squelch {
		m.storage =　signal　　　//ここを書き換えました
		m.counter = 0
		return text, true
	} else {
		return text, false
	}
}
```

**Comment by JG1VPP** [comment]
対応しました

**Comment by jucky154** [comment]
ありがとうございます。
いい感じになりました。　（あと一箇所、muteがtrue（ひとつ前） → true（今）のときに何も表示しないようにするというところさえできれば、ベータ版として公開できると思います）
