### ISSUE TITLE
自動利得制御

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#122]
## 問題意識

モールス信号解読プラグインをフェージングに強くする。

## 解決方法

自動利得制御を実装する。特定の周波数成分に対し、

1. 移動最大値フィルタで信号強度の時系列を得る
2. 信号強度の時系列を平滑化する
3. 信号強度の時系列をクリッピングする
4. 信号強度の時系列の逆数を求め利得の時系列とする
5. 利得の時系列に従って信号を増幅する

**Comment by jucky154** [comment]
https://github.com/nextzlog/todo/issues/118#issuecomment-1293650567
にあげた以外にフェージングみたいなことが起こっているのは`hard_JF2OZHp2`です
画像のように完全に信号が途中で0になるんでそういう場合には対応できない（正確には妙な増幅がかからない）ようにする必要がありそうですね

![smoothed](https://user-images.githubusercontent.com/58735989/198519940-a3949704-1a47-420e-b734-fa29e813f396.png)

**Comment by JG1VPP** [comment]
[Gist](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a)にフェージング対応版を用意しました。`hard_GBLUR5NN2214M.wav`の例:

```sh
__._...._.. UR 5NN 2214M
```

**Comment by jucky154** [comment]
![スクリーンショット 2022-10-29 005303](https://user-images.githubusercontent.com/58735989/198680526-a8ddf710-ae18-4abe-bbd4-0903914965d2.png)
プラグインのほうも対応しました。
特に問題なさそうですね（計算時間も増えた様子はなさそうですし）
