### ISSUE TITLE
CW解読プラグインのベータ版リリース

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#124]
## 概要

https://github.com/nextzlog/todo/issues/91 以来、1ヶ月に渡り開発を続けてきたモールス信号解読プラグインが実用に耐える性能に達したので、ベータ版のリリースと広報の準備を行う。

**Comment by JG1VPP** [comment]
## リリースまでの作業

- https://github.com/nextzlog/todo/issues/123 の反映
- https://github.com/nextzlog/todo/issues/118#issuecomment-1295155422 の対応

**Comment by JG1VPP** [comment]
- https://github.com/nextzlog/todo/issues/103#issuecomment-1288919082 の対応

**Comment by JG1VPP** [comment]
## リリースまでの作業

- https://github.com/nextzlog/todo/issues/123 の反映
- https://github.com/nextzlog/todo/issues/118#issuecomment-1295155422 の対応
- https://github.com/nextzlog/todo/issues/103#issuecomment-1288919082 の対応

**Comment by JG1VPP** [comment]
## リリースまでの作業

- https://github.com/nextzlog/todo/issues/123 の反映
- https://github.com/nextzlog/todo/issues/125 の対応
- https://github.com/nextzlog/todo/issues/103#issuecomment-1288919082 の対応

**Comment by jucky154** [comment]
**追加でやらないといけないこと**
CW解析で必要となる機能は

1. なっているモールスの音のリアルタイム解析
2. 過去のモールスの解析結果の表示

の二つが求められる. 現状としてはリアルタイムな解析が可能であり, 表示するだけならchottoをいじるだけですぐにできる.
一方で2については, 現状の実装はFinish関数(昔の実装にあった関数）がTrueになったときに, モールスの音が終了したとして過去のモールスの解析結果欄に移動させていた.
しかし, モールスの内容がキューみたいになっているため, モールスが終了したとしても過去の音のデータが残るので難しい.

https://github.com/nextzlog/zylo/blob/master/commons/morse/decoder.go#L169
以下に前のようにFFTして音がなければ`samples`を空にするとすればいいが, それではchottoでは文字がすぐに消えてしまう. 

この辺を衝突しないような解決方法を検討しなければならない.

**Comment by JG1VPP** [comment]
今の実装では、ある周波数で無音が`Monitor.MaxMiss`回続くと、その周波数の`Message`の内容が消去されます。それを確認して、過去に流れた文章として表示すれば良いのではないでしょうか？

**Comment by jucky154** [comment]
```
	m.samples = append(m.samples, signal...)
	if len(m.samples) > m.MaxHold {
		m.samples = m.samples[len(signal)/shift*shift:]
	}
	for _, next := range m.Decoder.Read(m.samples) {
		for _, prev := range m.targets {
			if next.Freq == prev.Freq {
				drop := len(next.Data) - (len(signal) / shift)
				data := append(prev.Data, next.Data[drop:]...)
				next = m.Decoder.detect(data)
				next.Freq = prev.Freq
				next.Life = prev.Life
			}
		}
		next.Life += 1
		result = append(result, next)
	}
	for _, prev := range m.targets {
		miss := true
		for _, next := range result {
			if next.Freq == prev.Freq {
				miss = false
			}
		}
		if miss && prev.Miss < m.MaxMiss {
			prev.Miss += 1
			result = append(result, prev)
		}
	}
	m.targets = result
```
がその辺のコードだと思うのですが, 音の信号がやってきて, 長さが長いと先頭を消して後ろに付け足す. それをSTFTして解析して解析において文字があるかを判断し, 前回と同じ周波数のものがあるかを確認していく.あればSTFTの結果を追加してdetectしてコードにする.
その後, ある一定程度なければ消される. というものだと見えるのですが,

`next := range m.Decoder.Read(m.samples)`の結果を用いて, `if next.Freq == prev.Freq `としているので, `m.samples`からその周波数の音が消えなければその文字列は消えません.つまりは, 解析結果はJ→JA→JA1→・・・→JA1ZLO→A1ZLO→・・→O→ようやく消える. (chottoの動作はそういう感じだった記憶) というものになってしまい, 確定動作ができないと思われます...

**Comment by jucky154** [comment]
上の機能を考えると, `m.samples`はモールスの音があるかないかを判断するためのバッファーなので, 現状の
https://github.com/nextzlog/zylo/blob/master/commons/morse/decoder.go#L149
5秒より短いほうがいいかもしれないという感じでしょうか？

**Comment by JG1VPP** [comment]
`m.samples`が短すぎるとモールス信号の検出のrecallが低下すると思います

**Comment by jucky154** [comment]
最新の状況です
https://gist.github.com/jucky154/efb80231a1c73b1fc68226df76184154
左のリストに解析中の解析結果を, 右のリストに解析が終了したものを表示するようにしました.
chottoを参考にしてはいます.

上のgistのように描いてみたものの, 以下のようなエラーが出ます.
使用しているのは現在最新のzLog(令和)とzbuildです.
自分のWindows PCが不調をきたしている可能性もあります.

![error2](https://user-images.githubusercontent.com/58735989/230776078-582ad383-31e3-430d-b489-04b146908ed5.png)
![error1](https://user-images.githubusercontent.com/58735989/230776082-174540cd-f672-4ab2-937e-dc1197218e19.png)

**Comment by JG1VPP** [comment]
`HandleButton`周りでのエラーですかね？他のプラグインは問題ありませんか？

**Comment by jucky154** [comment]
そうですね.
プラグインのマーケットプレイスからComport一覧とかを入手し, 確認しましたが問題なく, 想定通りの動きをしました.

**Comment by jucky154** [comment]
6/11に物を見せられるようにしようとCW解析プラグインのdebugをしております
問題の切り離しのために以下のgistのようにコンボボックスと音声機器の調査するところだけでも同じエラーが発生しました
https://gist.github.com/jucky154/4f79c5011ffbb71b06648417195de39e

出たエラーは以下の2つです
![error2-2](https://github.com/nextzlog/todo/assets/58735989/4363692b-ade0-4bbb-81df-3e6c26913ffa)
![error1-2](https://github.com/nextzlog/todo/assets/58735989/ddb2b33a-dacb-421e-9dd6-eb16fc7336d5)

一応、txtも生成されたのでそれも添付しておきます
[zlog.exe-exception-20230604175141.txt](https://github.com/nextzlog/todo/files/11645223/zlog.exe-exception-20230604175141.txt)

使用したzLog/zbuildは最新です

**Comment by jucky154** [comment]
Buttonがないぞというエラーなのでメニューに何か手を加えているのが問題なのかと思い、
`reiwa.RunDelphi(runDelphi)`
を消してコンパイル＆実行してもダメでした

**Comment by JG1VPP** [comment]
特に何も問題なく起動できました

- zLog 2.8.4.7
- https://gist.github.com/jucky154/4f79c5011ffbb71b06648417195de39e

**Comment by JG1VPP** [comment]
`zLog.JPN`のバージョンはzLogと揃っていますか？

**Comment by jucky154** [comment]
> zLog.JPNのバージョンはzLogと揃っていますか？
それが原因でした。
（zLogをダウンロードした時にJPNを移動させずに、使ったせいのエラーでした）

**Comment by JG1VPP** [comment]
解決して良かったです

[`EClassNotFound`](https://docwiki.embarcadero.com/Libraries/Sydney/ja/System.Classes.EClassNotFound)の説明から、消去法で原因をある程度絞り込めると思います

**Comment by jucky154** [comment]
zLogは起動するようになったものの
https://gist.github.com/jucky154/81530313093668a65b5dbfd594bd7a69
では、すごい無限にエラーを吐くようになりました
以下のようなtoastがいろんな種類出てきて、警告のクリスマスツリー状態でした
![謎のエラー](https://github.com/nextzlog/todo/assets/58735989/a97d735e-5e2a-4c6e-9d18-644f155a934a)

それを消すためにプラグインのwindowを閉じようとすると
![謎のエラー２](https://github.com/nextzlog/todo/assets/58735989/5580c51e-434a-4155-8c65-8d4da81c310c)
というエラーがでて、最終的にzlogを落とすと以下のようなエラーが出ます。
![謎のエラー３](https://github.com/nextzlog/todo/assets/58735989/e5e405a3-16c0-4902-9a40-e49c01bb6ea3)


多分、すべてのやり直しが正解だと思うのですが、
chottoより高度な機能（確定した文字しか表示しない、音が消えて全て確定した後には別の欄に表示するようにする、マイクの入力を変更できるようにする）が多いため、何をどう修正すればいいのかわかっていない状況です…

マイク入力の変更ができる部分はまぁ現状で良いとして、確定した文字しか表示しない・音が消えて全て確定した後に別の欄に移すあたりの指針が頂きたいです

**Comment by JG1VPP** [comment]
@jucky154 

`cwListener.go` を修正しました. これで良いですか？
https://gist.github.com/JG1VPP/9a2668d1802326244945835a788badfe

**Comment by jucky154** [comment]
というかその辺の動作が適切にコードにできていないですね（再考します）

**Comment by jucky154** [comment]
https://gist.github.com/jucky154/eb8da71e64e7bae5a338c225b7384f26
に書き換えることで、確定動作（音が消えてそれ以上文字列は更新されないはずなので、その文字列を右に移動させる）のタイミングは微妙ですが、動作しました。
しかし、謎のクラッシュをしました。

https://github.com/nextzlog/todo/assets/58735989/8e5786a2-a0df-4188-b66a-7634c939bb13

やはり、確定動作（音が消えてそれ以上文字列は更新されないはずなので、その文字列を右に移動させる）などのコードが複雑すぎる（以下の範囲）
https://gist.github.com/jucky154/eb8da71e64e7bae5a338c225b7384f26#file-cwlistener-go-L244-288
のが原因かと思っています…

**Comment by jucky154** [comment]
確定した文字列の列（右列）に余計な文字列が入ってしまうのは、現状のコードでは左側はcorrectなどで綺麗な文字列のみを表示するようにしているが、右側は
```Go
		if prev_text, ok := prev_results[f]; (ok && miss) {
			for i:= 0; i < len(old_results)-1; i++ {
				old_results[len(old_results)-1-i] = old_results[len(old_results)-2-i]
			}
			old_results[0] = prev_text
			delete(prev_results, f)
		}
```
で表示をしているので、一つ前の解析において存在したかどうかが重要なので、二回連続でその周波数に雑音がいた場合は表示されてしまうという課題があります…
その辺をどうするか…

**Comment by jucky154** [comment]
よくない結果がいっぱい出てきてしまうのはたまたま2回連続でその周波数に何かが載るとそうなってしまう(correctを通していないから）からでした
まえまでは`LIFE_THRESH`はなかったので無音が発生したら直後に確定しないといけないため、correctを通すと音の最後の方が消えてしまう可能性があるので、correctを通さずに表示したのですが、`LIFE_THRESH`ができたので無音の後に確定をしなくてもいい（`LIFE_THRESH=2`ならば無音の後に必ず2回はいる）ので、correctを通すことで解決することを考えています


```
INTERVAL_MS       = 500
```
なので、そこを短くすることで、右に移す時間を短くするのがいいのかなと思っていますがどうでしょうか？(250ミリ秒くらい)

**Comment by jucky154** [comment]
現状です
https://gist.github.com/jucky154/5103474b154f8e654064dfc2aa7f25aa


https://github.com/nextzlog/todo/assets/58735989/5726ba83-98c4-4d99-a2d3-b1cece167b64

やはり、なんかノイズみたいなものが表示されてしまいますね… (確定した文字のみを表示しても）
一応、確定した文字は右に移すようにできましたし、ある程度は想定の動作という感じですけど、どうでしょうか？

**Comment by JG1VPP** [comment]
現状の[モールス信号解読プラグイン](https://github.com/nextzlog/todo/issues/156)の設定をバックフィットして、現状の機能のままリリース・宣伝してみてはどうでしょうか？

**Comment by JG1VPP** [comment]
モールス信号解読器の主力はzLogプラグインからCW4ISRに移行したので、このIssueを閉じます
