### ISSUE TITLE
CW解読プラグインのウィンドウを安全に閉じる

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#125]
## 概要

https://github.com/nextzlog/todo/issues/118#issuecomment-1295155422

**Comment by JG1VPP** [comment]
## コメント

@jucky154 [`initdevice`関数の内部](https://github.com/jucky154/cwListener/blob/7a88c89a31a547bb7e3c52cc557844dd0db79923/cwListener.go#L336-L339)で`ctx.Uninit`の上`ctx.Free`までしているが、[`closewindow`関数](https://github.com/jucky154/cwListener/blob/7a88c89a31a547bb7e3c52cc557844dd0db79923/cwListener.go#L205-L211)でも同様に`ctx.Uninit`しているのはどういう理由ですか？

**Comment by jucky154** [comment]
[initdevice関数の内部](https://github.com/jucky154/cwListener/blob/7a88c89a31a547bb7e3c52cc557844dd0db79923/cwListener.go#L336-L339)はmalgoのコピペで生き残っていて、[closewindow関数](https://github.com/jucky154/cwListener/blob/7a88c89a31a547bb7e3c52cc557844dd0db79923/cwListener.go#L205-L211)はちゃんと録音切らないとという気持ちで残っていました…

`initdevide`の方は消して、`closewindow`の方に統一したほうが良さそうですね
https://github.com/nextzlog/todo/issues/117
によると、deviceを停止させてからctxを解放しないといけないらしいので、その辺でpanicが起きている説はありますね

**Comment by JG1VPP** [comment]
こちら、解決済みですよね？

**Comment by jucky154** [comment]
その通りです
