### ISSUE TITLE
Chotto Wakaru CWプラグイン

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#133]
## 概要

テストベッドとなる[最も簡単なモールス信号解読プラグイン](https://github.com/nextzlog/zylo/tree/master/plugins/utils/chotto)を整備する。

**Comment by JG1VPP** [comment]
## 機能

- 同時に1局のみ受信可能
- デフォルト尾の音声デバイスを使用

**Comment by JG1VPP** [comment]
## 機能の制限

- 同時に1局のみ受信可能
- デフォルトの音声デバイスを使用

**Comment by jucky154** [comment]
自分の環境で使うと
![tyerror](https://user-images.githubusercontent.com/58735989/199862759-6dd4c0f7-c9e9-4de8-ab6a-6988763bc724.png)
というエラーが出ますね

実際に使った動画がこれです
https://user-images.githubusercontent.com/58735989/199862805-f78c4d7d-2d0c-43b2-9930-9d7c17a78615.mp4

**Comment by JG1VPP** [comment]
モールス信号解読モジュールのデバッグ環境が整った

<img width="214" alt="キャプチャ" src="https://user-images.githubusercontent.com/23717324/200007077-831c9a91-ba8a-4ec0-a5b9-9e3f528dae99.PNG">

**Comment by JG1VPP** [comment]
Chotto Wakaru CWプラグインを活用することで、だいぶモールス信号解読モジュールの問題の把握が進みました。ついでに、`Join`関数を`Monitor.Read`関数の内部で自動的に実行する方式に変更したので、今後は明示的に呼ぶ必要はありません。

### 単純な例

綺麗に読み取れていますね。なお、数字は、モールス信号の短点の速度で、単位はHzです。

<img width="214" src="https://user-images.githubusercontent.com/23717324/200123166-1ebf5159-d380-494a-9d4c-b785c9eaf1ae.PNG">

### ノイズ

非常に苦労しているのが、モールス信号とノイズの判別です。残念ながら、信号のパワーに基づく方法では、完全にノイズを排除できず、意味不明な解析結果が表示されます。対処法を色々と実験しつつ検討しました。手元で発生しているノイズの特徴は以下の2点です。

- 短点の羅列である
- 極端に高速である

この特徴から、読み取り可能なモールス信号の速度の限界に発想が至りました。言わば、ナイキスト周波数に相当する上限があって、それを超える高速な信号は誤った信号である、ということです。

<img width="214" alt="キャプチャ" src="https://user-images.githubusercontent.com/23717324/200123758-3327dd2b-ee1a-4b7e-a02b-2d959a2b544f.PNG">

今、デフォルトの設定で、STFTの時間方向のシフト量は50Hzとしています。つまり、25Hzを上回る信号は存在し得ません。そのような周波数の信号が検知された場合、それは、意味のある信号は取得できなかった、と判断できるのではないでしょうか。

**Comment by JG1VPP** [comment]
Chotto Wakaru CWプラグインを活用することで、だいぶモールス信号解読モジュールの問題の把握が進みました。ついでに、`Join`関数を`Monitor.Read`関数の内部で自動的に実行する方式に変更したので、今後は明示的に呼ぶ必要はありません。

### 単純な例

綺麗に読み取れていますね。なお、数字は、モールス信号の短点の秒数の逆数です。

<img width="214" src="https://user-images.githubusercontent.com/23717324/200123166-1ebf5159-d380-494a-9d4c-b785c9eaf1ae.PNG">

### ノイズ

非常に苦労しているのが、モールス信号とノイズの判別です。残念ながら、信号のパワーに基づく方法では、完全にノイズを排除できず、意味不明な解析結果が表示されます。対処法を色々と実験しつつ検討しました。手元で発生しているノイズの特徴は以下の2点です。

- 短点の羅列である
- 極端に高速である

この特徴から、読み取り可能なモールス信号の速度の限界に発想が至りました。言わば、誤り検出可能な速度の上限があって、それを超える高速な信号は誤った信号である可能性が高い、ということです。

<img width="214" alt="キャプチャ" src="https://user-images.githubusercontent.com/23717324/200123758-3327dd2b-ee1a-4b7e-a02b-2d959a2b544f.PNG">

今、デフォルトの設定で、STFTの時間方向のシフト量は50Hzとしています。ここで、短点1個が2サンプル以上で表現される場合、その短点は信頼できます。逆に言えば、1秒間に短点1個に相当する符号語（有音・無音）が25個を超える場合、それは誤り検出できません。

そのような周波数の信号ばかりが検出される場合、意味のある信号は取得できなかった、と判断できるのではないでしょうか。

**Comment by JG1VPP** [comment]
@jucky154 まずは、Chotto Wakaru CWプラグインを試していただけますでしょうか？

**Comment by JG1VPP** [comment]
Chotto Wakaru CWプラグインでは、主に`Join`関数周りの改良を行なっています。

[Go Playground](https://go.dev/play/p/0C5If8rf1mh)

```go
package main

import (
	"fmt"
	"strings"
	"github.com/thoas/go-funk"
)

type hoge struct {
	msg string
}

func Join(prev, next string) string {
	best := 1
	save := 0
	skip := 0
	head := strings.Split(prev, " ")
	tail := strings.Split(next, " ")
	for idx := 0; idx < len(head); idx++ {
		zip := funk.Zip(head[idx:], tail)
		pos := 0
		neg := 0
		for id, tuple := range zip {
			p := tuple.Element1.(string)
			n := tuple.Element2.(string)
			if p == n {
				pos += 1
			} else if len(head[idx:]) > len(tail) {
				neg = id + 1
			} else {
				neg = id
			}
		}
		if pos >= best {
			best = pos
			save = idx + neg
			skip = neg
		}
	}
	code := append(head[:save], tail[skip:]...)
	return strings.Join(code, " ")
}

func main() {
	fmt.Println(Join("Z", "7 L 1 F F H"))
	fmt.Println(Join("7 Z", "7 L 1 F F H"))
	fmt.Println(Join("7 L 1 F F H : : :", "? 1 ? F H"))
}
```

Chotto Wakaru CWプラグインに[ループバック](https://vb-audio.com/Cable/)で音声を流してみて、出現した`Message`のパターンに応じて、その動作を追っています。概ね、`Join`関数は上記のコードと同じなので、ぜひ改良してみてください。その結果がZyLOにバックフィットされます。

**Comment by JG1VPP** [comment]
あるいは、このあたりのアルゴリズム改善に皆さんの力を借りてみてはどうでしょうか？

**Comment by JG1VPP** [comment]
現状では、同じ文字列の繰り返しで誤動作する(`JA1ZLO JA1ZLO JA1ZLO...`)ことがわかっています。一方で、`next`が綺麗に解読できなかった場合、`Join`関数で誤った場所に挿入してしまい、異常な結果になる場合もあります。このあたりはChotto Wakaru CWプラグインで体験できますし、それを上のサンプルコードで再現することもできます。

**Comment by JG1VPP** [comment]
別の方法として、信号を記憶しておき、結合していく方法もある。以下の2方法が考えられる。

1. オリジナルの信号を`Message`に記憶・蓄積する
2.  特定周波数の信号を`Message`に記憶・蓄積する

1はSTFTの計算量の観点で非現実的。2は信号を切り出した際の端部の処理が問題。例えば、ある瞬間までを切り出してフィルタ処理した場合、その次の瞬間に出現する波形を考慮しないので、全く異なる波形になり得るし、単純にパディングの長さも問題。

**Comment by JG1VPP** [comment]
現在、`Join`関数を自動的に呼ぶ処理は取り外しています。

**Comment by JG1VPP** [comment]
皆さんで相談して、文字列を結合する方針が良いということになったら、Chotto Wakaru CWプラグインを使って、解読結果の時系列を複数通り作成し、それらを正しく結合するアルゴリズムをコンペしてみると良さそう。

**Comment by jucky154** [comment]
@ibuki2003 @Graphium314 @taka231 
上のアルゴリズムに関して意見をいただけるとありがたいです

**Comment by jucky154** [comment]
現在のchotto wakaruをインストールし、試しました
加減としてはよさそうですが、これはjoinがないからということですよね？

https://user-images.githubusercontent.com/58735989/200166656-36003735-668e-4eff-b6f5-500aab67d40a.mp4

**Comment by JG1VPP** [comment]
`Join`関数の実行を削除しました。なので、結合処理を行なっていません。

**Comment by jucky154** [comment]
そういえば、現状はSTFTですけど、waveletにしたらどうなるんでしょうか？
https://github.com/nextzlog/todo/issues/133#issuecomment-1304759729
waveletで2を適応しても同じでしたっけ？（waveletが記憶の彼方へ）

**Comment by JG1VPP** [comment]
ウェーブレット自体を選ぶ必要や、スケールの調整など、考慮すべき事項はありますが、計算量はnでSTFTのnlognよりも有利です。とは言え、上に挙げた課題は、デジタル信号処理の根本的な問題であり、ウェーブレット変換にしたところで解決するものではありません。

**Comment by jucky154** [comment]
気にしていたのはwaveletで「信号を切り出した際の端部」が問題になったかどうかを忘れてしまいました…
端部がさほど問題ないのであれば、思ったのは、録音時間を超えてしまった場合には、「最初からある程度の部分（立ち下がりで区切る）」は解析の中間段階である「有音or無音, 何秒」という形式で保持し、音声データとしては削除する。次の解析(長音か短音か）ではそれを頭につけて解析するとかすれば、時間のかかりそうな音がon/offの解析の長時間化は回避できるのかなと考えました。
（もちろん、非常に長くなれば長音か短音かの解析で時間を食うようになるのかもしれませんが）

そして、無音になったら全てを削除し、finishをtrueにする感じにすれば良いのかなと思いました

**Comment by jucky154** [comment]
上の方法を採用するなら、何度かの解析で同じ文字として出されたものは正しいと判断して、文字と文字の間で区切って、前半を削除する（結果表示の際には文字を先頭に追加）とかの方が、長音か短音かの解析も消えて楽か？

**Comment by JG1VPP** [comment]
要件定義をしておきましょう。

1. 符号語が途切れている文字は、次の解析周期で文字が確定するまで非表示とする
2. 送信が開始されてから、送信が完了するまで、ひとつながりの文字列で表示する

1点目については、以下のように常に確実な解析結果が表示されるということです。

1. J
2. JA
3. JA1
4. JA1Z
5. JA1ZL
6. JA1ZLO

2点目については、以下のようにスクロールして消えることがないということです。

1. JA1ZLO
2. A1ZLO
3. 1ZLO

**Comment by taka231** [comment]
昨日 @ibuki2003 とちょっと考えたのですが、一回の解析で、
stftの返り値をqueue状に保持する
文字が確定したら、文字を解析結果に追加し、確定した分だけ上記の保持していたデータから取り除く
とするのはどうでしょうか？

**Comment by jucky154** [comment]
> 2は信号を切り出した際の端部の処理が問題。例えば、ある瞬間までを切り出してフィルタ処理した場合、その次の瞬間に出現する波形を考慮しないので、全く異なる波形になり得るし、単純にパディングの長さも問題。

という関係でその手法はできない物だという解釈なんですけどどうでしょうか？

つまりは「ある一定程度のバッファーが貯まると、前までのデータと結合してSTFTをする」というのが現在の手法ですけど、それだと「バッファーにSTFTをかけて、結合していく」という手法ですよね
その場合は、パディングとかでまずいことにならないでしょうか？（モールスが入っているのに立ち上がりが遅れて無音とされるとか）

**Comment by taka231** [comment]
stftの仕組みを余り良く分かっていないのですが、数hop size分の音声データを余分に持っておいて、それを解析するデータの前にくっつければ、端部の問題は解決出来るのかなと思いました。

**Comment by ibuki2003** [comment]
STFTの端部処理はこんな感じで対応できました。実際に全体を繋いだままSTFTした結果と変化ないことを確認しています。

<details>
<summary>コード差分</summary>

```diff
type Monitor struct {
 	MaxHold int
 	Decoder Decoder
-	samples Samples
+	last Samples
 }
```

```diff
 func DefaultMonitor(SampleRateInHz int) (monitor Monitor) {
-	shift := int(math.Round(0.02 * float64(SampleRateInHz)))
+	shift := 512
 	return Monitor{
```
時間解像度に直接寄与するものではないので、適当な値(FrameLenの1/2か1/4程度?)を定数で書いてしまって良いと思いますが、いかがでしょうか?

```diff
+func max(a, b int) int {
+	if a > b {
+		return a
+	} else {
+		return b
+	}
+}
+
 /*
  音声からモールス信号の文字列を抽出します。
 */
 func (m *Monitor) Read(signal Samples) (result []Message) {
-	m.samples = append(m.samples, signal...)
-	result = m.Decoder.Read(m.samples)
-	if len(m.samples) > m.MaxHold {
-		m.samples = m.samples[len(signal):]
-	}
+	signal = append(m.last, signal...)
+	m.last = signal[max(0, m.Decoder.STFT.NumFrames(signal)*m.Decoder.STFT.FrameShift):]
+	if len(signal) < m.Decoder.STFT.FrameLen { return }
+	result = m.Decoder.Read(signal)
 	return
 }
```

</details>

`Decoder`部の対応がまだですが、アイデア出しの過程ということでとりあえず省略します。逐次連結で対処できると思います。

**Comment by jucky154** [comment]
@ibuki2003 
上の件ってどういう感じで確認しましたか？
（年末年始で作業を進めようと思ったので）

@JG1VPP 
上のコードを反映させ、いい感じにキュー的にしていく方法はありますかね…

**Comment by jucky154** [comment]
@JG1VPP 
文字と音データを一対一対応（どこからがトンツーの始まりかで対応）させて保持し、確定した文字（この辺は適切に考える必要があって、二回同じ文字になったら速度によっては微妙説があるので、現在更新中の文字の2文字前かつその文字は二度の解析で同じ文字になっているくらい）は音データから削除していくとかでどうしょうか？

**Comment by ibuki2003** [comment]
@jucky154 
> どういう感じで確認
- ライブラリのコードを読むと分割して流し込む処理が確認できたため、分割の仕方をそのまま写す
- 念のため該当部分を切り出し、適当なwavファイルを流し込み比較

というような流れです

**Comment by JG1VPP** [comment]
皆さんの取り組みを参考に、以下の改善を施した解析プログラムを[Gist](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a)に置きました。また、ZyLOに反映させたところ、大幅に性能が向上しました。

- STFTをオンライン実行する
- `Message`構造体にはSTFTの結果を格納して逐次結合
- 瞬間的に特定の周波数のモールス信号を見失っても`MaxMiss`回までは`Message`を保持し続ける

K-meansの計算量は信号の長さNに対しO(N)なので、ざっくり計算ですが、1時間ほど連続で貯めても表示周期に間に合うはず。試作段階ながらほぼ実用段階に達したという判断で、このIssueは閉じます。解析に失敗した際にノイズが表示される問題は残ってますが、UIの改善や、より高機能なプラグインの開発を、引き続きお願いします。
