### ISSUE TITLE
新ドメイン

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#143]
## 問題意識

無線部開発班のドメイン https://pafelog.net は、pafelogの開発が終了して以降、あまり意味をなしていない。実態に即したドメインを取得し直したい。

## トップレベルドメイン

|TLD|用途|備考|
|---|---|---|
|.dev|開発者用|Googleで1400円/年|
|.sh|セントヘレナ|1万円|

## ドメインに使う文字列

- 無線部開発班の代表的な製品名で、かつ今後も開発・提供が続けられるもの
- 事前知識のないユーザがドメインを見た時に、その意味がわかりやすいもの

**Comment by JG1VPP** [comment]
## 有力案

### zlog

zLog公式と並べた時にわかりやすい。関係者に了承を得る必要があるかも？

### allja1

ALLJA1にフォーカスし過ぎなので、望ましくない。サブドメインにする分には良い。

### ats4

代表的な製品ではあるが、今後ATS-5の開発が始まると微妙。

### zylo

zLogのモジュールであることを考えると、サブドメインにする程度が妥当。

**Comment by jucky154** [comment]
ツイッターのアカウントであるnextzlogとかは結構良さそうに見えます

**Comment by JG1VPP** [comment]
ここだけの話、昔失効した allja1 . net は、一時期、売りに出されていたが、今見たところ消失している。ドメインを手放すリスクはそこまで考えなくて良さそう。

**Comment by JG1VPP** [comment]
> ツイッターのアカウントであるnextzlogとかは結構良さそうに見えます

2012年頃はzLogの次期バージョンを作る意気込みでした。あと、nextと.devは意味が被るんですよね...

**Comment by JG1VPP** [comment]
## サブドメイン

### 無印

内容は自由。編集権限を組織で共有。

### book

記事のPDFを集める
- https://pafelog.net

### ats4

ATS-4の公式ドキュメント
- Scaladoc
- README

### zylo

ZyLOの公式ドキュメントを集約。
- https://pafelog.net/zylo
- https://zylo.pafelog.net

**Comment by JG1VPP** [comment]
next . zlog . dev

**Comment by JG1VPP** [comment]
Google曰く、 
- zlog.dev は *このドメイン名には一般的な単語が含まれていないため、覚えにくく、入力しづらい可能性があります*
- nextzlog.dev と allja1.dev は *このドメイン名は発音しやすく、聞いて入力しやすいです*

**Comment by jucky154** [comment]
どうでもいいかもしれませんけど、
CW解析システムの名前を**Automatic Translation of CW(ATC-1)**とかにすると、ATS-4と合わせてtrain series とか名乗れそうな気がしますね

**Comment by JG1VPP** [comment]
nextzlog.devに固まりつつありますが、何か良い代案ありますかね？autodyne.devもオサレ感あって良さそう

**Comment by JG1VPP** [comment]
nextzlog.dev 取得！pafelog.netは今年いっぱいで廃止予定です！
