### ISSUE TITLE
CW解読プラグインにおいて、稀にクラッシュする

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#155]
## 概要
CW解読プラグインにおいて、稀にクラッシュする

## 再現手順・設定
いっぱいCW解析をしているとまれにzLogごと落ちる
defer reiwa.DisplayPanic()
も働かないので原因がわかっていない

たとえば、解析時間（およそ200ミリ秒）が伸びてしまい、INTERVAL_MS=400ミリ秒を超えてしまい、クラッシュしているとか？

## 期待される動作
クラッシュしない
（正確には原因を特定し、そのバグ取りが必要）

## 対応期限
完成品公開まで

**Comment by JG1VPP** [comment]
`defer reiwa.DisplayPanic`が記述されていないスレッドで何か`panic`が発生したということでしょう。考えられるのは、イベントハンドラを渡している部分です。例えば、

```go
onRecvFrames := func(out, in []byte, framecount uint32) {
	go decode_main(readSignedInt(in))
}
```

が該当します。で、`decode_main`関数は`panic`の対策をしていますが、このイベントハンドラではしてないですよね？もしこの部分で`panic`が発生するなら、`readSignedInt`で発生していることになりますが。

**Comment by jucky154** [comment]
CWプラグインがCW4ISRに移行しているのでcloseが適切だと考え、closeします。
（必要であれば、再度開きますし、開いてください）
