### ISSUE TITLE
モールス信号解読アプリ

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#156]
## 問題意識

モールス信号解読プラグインはzLogの起動が必要で不便という現役部員の声。モールス信号解読機能自体は便利に使ってるとのこと。

## 解決方法

以下の要件を備えたモールス信号解読アプリを開発する。

- クロスプラットフォームで動作
- zLog令和版の宣伝機能を有する

**Comment by JG1VPP** [comment]
GUIツールキットは [andlabs/ui](https://github.com/andlabs/ui) が良さそう？

**Comment by JG1VPP** [comment]
## 完成イメージ

![image](https://github.com/nextzlog/todo/assets/23717324/d4c0f856-7a04-46cb-9623-b75cb2fb7f64)

**Comment by jucky154** [comment]
https://cws.connpass.com/event/283550/
なんか、前ATS-4やZyLOについて紹介したイベントで、CWに関する公演もあるようです

**Comment by JG1VPP** [comment]
## 現状

![image](https://github.com/nextzlog/todo/assets/23717324/c49ec383-0f9c-459b-845d-ad7764661f42)

DEJA0BZEはしばしばJAが聞き取れない場合がありますが、波形を見れば納得ですね
DEとJA0BZEの間にも特に間隔がないですね

**Comment by JG1VPP** [comment]
## 現状

![image](https://github.com/nextzlog/todo/assets/23717324/a3ee0473-cd86-476f-822c-258d813b34ab)

DEJA0BZEはしばしばJAが聞き取れない場合がありますが、波形を見れば納得ですね
DEとJA0BZEの間にも特に間隔がないですね

**Comment by jucky154** [comment]
ちなみにDEとコールサインの間がなかったりするのでコールサインをクリックした時に移動させる機能は本当に困るんですよね…
（DE以下を移動させる場合、JA1DEXやDE1XXXみたいな局がダメだったり、他にも5NNや1OO1O5, 1をAしたりするのはコンテストナンバーの形式とか国内/世界のコンテストとかをcfgからDLLに移さない限り、表記揺れ問題と同じように処理できないんですよね…

**Comment by JG1VPP** [comment]
> 上をzLog側のDLLでもできるようにするべきという感じですかね？　（どう実装したものか…）

一応、プラグインはプロセス間通信によってモールス信号解読アプリとzLogの連携を行う機能に専念する、という方針もあり得ます。

**Comment by jucky154** [comment]
そういう方針の方が、いろんな意味では良さそう？
（通常交信で信号解読アプリの使い方などに慣れてもらったり、問題点の洗い出しをしてもらい、それをコンテストでも便利に使いたいならzLogを使いましょうという流れにしておけばzLog userも増える？）

**Comment by JG1VPP** [comment]
それで良いのであれば、そのように整備します。単体のアプリとして見たとき、どんな機能があると便利そうでしょうか？

**Comment by jucky154** [comment]
単体アプリとしても（現状のzLog側のDLLにもありますけど）、過去の解析結果を別の欄に残す機能は欲しいですね

他にあると良い機能
- 和文・英文切り替え（コンテストで使うなら不要ですが、単体のアプリならあっても良い）
- 特殊文字や定形の対応 (HHは（訂正) などで表示, コンテストであまり使われないが通常でよく出てくる、FBやGMやBKなどの文字の間が省略されやすい文字列は登録)
- TESTや5NNなどの高速で打たれやすい部分（コンテストではTESTや5NNは定形なのでここだけ+9WPMする局が多い）の何らかしらの対応

あったらいいなこんな機能
- リグコンやUSBIFとの連携（ここまでくるとリグコンしてCW打てて欲しい）
- ハムログ出力

というか上の機能は全て
https://ja3clm.sakura.ne.jp
である機能の羅列ですね…（解析率がよく、チューニングが不要なのが我々で、リグコンはないですけどUSBIF連携・ハムログ連携があるのが向こうですね。　まぁ、zLogと連携すればUSBIF・リグコン連携したようなものですけど）

**Comment by JG1VPP** [comment]
- 日本語対応はTTFの埋め込みなど面倒ですが、和文をアルファベットで表示する程度なら可能です。
- リグコントロールはzLog本体のものを使うより、[hamlib](https://github.com/Hamlib/Hamlib)を活用する方がメンテしやすそう。

**Comment by jucky154** [comment]
あと、現役部員から言われたのはchottoを使っていると文字列がある一定以上を超えるとwindowサイズを超えるので...になって何が解読されたか分からなくなる
そのため、windowサイズを超えたら、折り返すなどの処理をして欲しいとか

個人的に必要かなと思ったのは確定までの時間が長いなと言う感じですね（どう対策するのがいいか悩み中）

**Comment by JG1VPP** [comment]
- [chotto-macOS](https://github.com/nextzlog/zylo/releases/download/nightly/chotto-macOS)
- [chotto-Windows.exe](https://github.com/nextzlog/zylo/releases/download/nightly/chotto-Windows.exe)

読み取り速度・精度とも改善しています。なお、終了時にゴミが発生するのは、ノイズ判別アルゴリズムの変更に伴うもので、調整中です。

**Comment by jucky154** [comment]
上をmorse runnnerで遊んでみましたが、解読はそれなりにうまくいくのですが、ノイズだけの時でも解析結果が表示される（それも6個くらい）ので、モールスの解析結果がどこにいったのかを探すのが大変でした。
ノイズ判別アルゴリズムの調整が結構必要そうだなという感じでした。（morse runnnerで調整して、morse runnnerで遊んだ結果を見せてこのアプリの広報に使うとかがいいかもしれません）
