### ISSUE TITLE
リアルタイムコンテストの参加案内

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#16]
説明のPDFを作ったのでそれを.mdにしてgithubなり適切な位置に設置する。
[リアルタイムコンテストの参加方法.pdf](https://github.com/nextzlog/zylo/files/7574706/default.pdf)

**Comment by JG1VPP** [comment]
↑ヘルプ画面に追加しますか？

**Comment by jucky154** [comment]
ヘルプ画面に載せるのがいいと思います

**Comment by JG1VPP** [comment]
ヘルプ画面:

![image](https://user-images.githubusercontent.com/23717324/184344993-5535ec80-459b-41be-b6b1-ef12b8d6a3a4.png)

[zLogを利用する場合](https://github.com/nextzlog/zylo/blob/master/plugins/rules/rttest/README.md)
