### ISSUE TITLE
電通大コンテストのシングルバンドの得点計算でエラーが出る

### ISSUE THREAD

**Issue by fjdj-1515** [nextzlog/todo#181]
## 概要
表記の通り、オールバンド部門で正常に得点計算できるログファイルをシングルバンド部門に入れると以下のようなエラーが出現します。
オールバンドとSWLでは問題なく得点計算できています。

```
(NoMethodError) undefined method `include?' for #<Java::QxslDraft::Band:0x3d7e4627>
```

![image](https://github.com/nextzlog/todo/assets/50458845/39842f85-7a3c-44e0-b7a4-4ae57ece9041)

## 再現手順・設定
念のためテストログを添付させていただきます
https://nextcloud02.fjdj.dev/s/dzXAeG7MD5Rf35q

## 期待される動作
正常に得点計算ができる。

## 対応期限
急で大変申し訳ないのですが、金曜日までにお願いしたいです。

**Comment by JG1VPP** [comment]
ご不便をおかけしています。対応しましたので、最新のイメージを`docker pull ghcr.io/nextzlog/ats4:master`で取得して、ATS-4を起動し、動作確認をお願いいたします。

**Comment by fjdj-1515** [comment]
対応ありがとうございます。
最新のイメージで起動し、シングルバンドでも正常に得点計算が行われることを確認しました。

ありがとうございました。
