### ISSUE TITLE
完全に無音の時の対応

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#183]
## 問題意識
（以前、どこかで議論しただけなので、解決済みかもしれませんが…）
リグとPCを繋ぎ、リグ側でセミブレークインでCWを送出していると、PC側の音声にはモールスの音声が入ってこず、完全に無音（信号強度が0)となる。
その際に、アプリ側は音は継続していると判断してしまうので、その際の処理を検討する必要がある。

## 解決方法
信号強度が完全に0になることを100ms続いたら、区切りとするという処理が必要

**Comment by JG1VPP** [comment]
信号の強度が完全に0になるという保証はあるのでしょうか？一応、読み取った符号語が変化しなくなる瞬間を送信の終了として検出しています。

**Comment by JG1VPP** [comment]
信号の強度が完全に0になるという保証はあるのでしょうか？ちなみに、読み取った符号語が変化しなくなる瞬間を[送信の終了として検出](https://github.com/nextzlog/CW4I/blob/7fbe53becc13d6b6c7175722a50d6380e1040b00/core/morse/decoder.go#L56-L71)しています。

```go
func (d *Decoder) Read(signal []float64) (result []Message) {
	for _, next := range d.Next(signal) {
		for _, prev := range d.List.Present {
			if next.Freq == prev.Freq {
				next = prev.Merge(next)
				next = d.Scan.Scan(next)
				if next.Code == prev.Code {
					next.Miss = prev.Miss + 1
				}
			}
		}
		result = append(result, next)
	}
	d.List.Push(result)
	return
}
```

**Comment by jucky154** [comment]
>ちなみに、読み取った符号語が変化しなくなる瞬間を[送信の終了として検出](https://github.com/nextzlog/CW4I/blob/7fbe53becc13d6b6c7175722a50d6380e1040b00/core/morse/decoder.go#L56-L71)しています。

であればこの問題は発生しないので問題なさそうですね
(よって閉めます）

完全に0になる保証はリグによるという感じですね
一応、あの録音はFTDX3000とIC7300の録音なので、あれの無音の時の信号強度が0ならば0ある程度のリグは0になると言えます
