### ISSUE TITLE
マニュアルのmarkdownについて

### ISSUE THREAD

**Issue by jr8ppg** [nextzlog/todo#187]
## 問題意識

markdownの方で \$Q や \$V を入力しても、use.zlog.orgにデプロイされると表示がイマイチ。  もちろん\\でエスケープもしている。  
\$ ～ \$の間がフォント変更の様な動きになっている。生成されているhtmlを確認しても特に問題は無いように見える。  

![image](https://github.com/nextzlog/todo/assets/56021425/9acf5a85-5cbc-4fbd-bd4c-afaa8ae5588b)

意図したとおりに出るところもある。  

![image](https://github.com/nextzlog/todo/assets/56021425/179c25df-acbe-40c8-b8f6-341da8b13681)

どうしてですか？？

**Comment by jucky154** [comment]
https://b1san-blog.com/post/vscode/vscode-md-math/
TeXやMarkdownだと「$」で挟まれた領域はインラインの数式入力であると判断されます。
そのため、表示が数式表示のためのフォント・文字が斜めになります。

$Xが正しく表示されているのはその後に
$がもう一度やってこないからですね。

こうやって改行をしていればその機能は無効かされるみたいです。

`/`でescapeしようとしていますが、予約文字である$をescapeはできないので、こうなっているのかなと直感的には思いました。
{% raw %}$ {% endraw %}みたいにしたり、`%24`を使ってみましたが意味はありませんでした。

@JG1VPP は何か対策方法をご存知ないですか？

**Comment by jr8ppg** [comment]
` &dollar; を試したら &dollar; の & が &amp; にされてしまいました・・・`

**Comment by jr8ppg** [comment]
`&#36; で良さそう`

**Comment by jr8ppg** [comment]
だめだ、同じ行に 二つあると KaTex になってしまう

**Comment by jr8ppg** [comment]
`$\text{\textdollar}$ `でKaTexの$が出ました。これで代替。
![image](https://github.com/nextzlog/todo/assets/56021425/e4fe4149-f8c0-464c-b1c5-23ded8acadfc)

**Comment by JG1VPP** [comment]
zLogのマニュアルでKaTeXを使用する必要性はないでしょうから、無効化するのが良いと思います。

```yaml
kramdown:
  math_engine: null
```

**Comment by jr8ppg** [comment]
うーん、_config.yamlが更新されているのは確認しましたが、変わりませんね。

**Comment by JG1VPP** [comment]
KaTeXのレンダラーはJekyllテーマの方で呼び出してました。それを無効化しました。ブラウザのキャッシュを消去すると反映されます。
