### ISSUE TITLE
リセットボタンの再度導入

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#189]
## 問題意識

> 表示がカオスになると詰む

という身も蓋も無い問題提起が現役部員からありました。
解決手法は「下の調整のやつは最大にして、一度切ってください。　そして、再起動して、ちょっとずつ左にずらしていき、文字が出たタイミングで止めてください。　それが最適くらいです。　文字がいっぱい出てくると、もう止まりません。（ボリュームを右にしても、解析がずっと回り続けるやつがいて、効果がない)」という感じ

> CW解読機リセットボタン欲しいかも〜

という意見もありました

## 解決方法
そのため、リセットボタンを再度導入し、文字が無限に出ても解析を終了させ、ボリュームの調整を聞くようにすれば良いのでは無いか
また、リセットボタンは他人の交信を受信中に、トーンが同じだと送信している局が変わった（速度が変わった）のに、同じ局であると処理が進んでしまうのを、リセットをかけることで分離をかけることができる。

なぜ、最新バージョンでリセットを消したか不明ですが、表示を消すのが良く無いという思想であれば、解析だけ停止させ、表示はそのままにするなどという手法があるような気がします。

**Comment by JG1VPP** [comment]
まず、当初の**clear**ボタンの機能は、リストを消去することであって、解析を中断する機能はありません。従って、

> 文字が無限に出ても解析を終了させ

このような機能はそもそもありません。その上で、

> ボリュームの調整

これは、リセットボタンではなくボリューム側で対応すべきでしょう。

**Comment by JG1VPP** [comment]
対応しました。
