### ISSUE TITLE
コンテスト対応の依頼

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#199]
## 問題意識
とあるコンテストから, ATS-4を使用したいという連絡がXで来ました. 
詳細については, XのDMで送りましたのでご確認のほどよろしくお願いいたします. (@JG1VPP )

**Comment by JG1VPP** [comment]
https://github.com/nextzlog/todo/issues/135 を案内。Docker利用のためVPSの契約が必要である点を伝えた。

**Comment by jucky154** [comment]
サーバにdocker方式だけでなく, ローカル方式も案内した方がいいかもしれません.

**Comment by JG1VPP** [comment]
## ダウンロード

[ats4-agc.zip](https://github.com/user-attachments/files/15821489/ats4-agc.zip)

## 必要な環境

- インターネット接続 (Dockerイメージの自動ダウンロードに必要)
- [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- WSL2

## WSL2の準備

- [Windows＋WSL2でDocker環境を用意しよう](https://www.kagoya.jp/howto/cloud/container/wsl2_docker/)に従ってWSL2とUbuntuを準備する。

## Docker Desktopの準備

- [公式サイト](https://www.docker.com/products/docker-desktop/)からWindows版をダウンロードしてインストールする。

## 実行方法

1. Docker Desktopを起動しておく
2. `ats4-agc.exe`をダブルクリックで実行する
3. ブラウザが自動的に開きATS-4の画面が表示される

## 実装

[Gist](https://gist.github.com/JG1VPP/2e67b4e54f567e7f85f8251d669c9aaf)

**Comment by JG1VPP** [comment]
## ダウンロード


## 必要な環境

- インターネット接続 (Dockerイメージの自動ダウンロードに必要)
- [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- WSL2

## WSL2の準備

- [Windows＋WSL2でDocker環境を用意しよう](https://www.kagoya.jp/howto/cloud/container/wsl2_docker/)に従ってWSL2とUbuntuを準備する。

## Docker Desktopの準備

- [公式サイト](https://www.docker.com/products/docker-desktop/)からWindows版をダウンロードしてインストールする。

## 初回起動

1. Docker Desktopを起動しておく
2. `ats4-agc-update.exe`をダブルクリックで実行する
3. ブラウザが自動的に開きATS-4の画面が表示される

## 実行方法

1. Docker Desktopを起動しておく
2. `ats4-agc.exe`をダブルクリックで実行する
3. ブラウザが自動的に開きATS-4の画面が表示される

## 実装

[Gist](https://gist.github.com/JG1VPP/2e67b4e54f567e7f85f8251d669c9aaf)

**Comment by JG1VPP** [comment]
## ダウンロード

[ats4-agc.zip](https://github.com/user-attachments/files/15823357/ats4-agc.zip)

## 必要な環境

- インターネット接続 (Dockerイメージの自動ダウンロードに必要)
- [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- WSL2

## WSL2の準備

- [Windows＋WSL2でDocker環境を用意しよう](https://www.kagoya.jp/howto/cloud/container/wsl2_docker/)に従ってWSL2とUbuntuを準備する。

## Docker Desktopの準備

- [公式サイト](https://www.docker.com/products/docker-desktop/)からWindows版をダウンロードしてインストールする。

## 実行方法

### 初回起動

1. Docker Desktopを起動しておく
2. `ats4-update.exe`をダブルクリックで実行する
3. `ats4-agc.exe`をダブルクリックで実行する
4. ブラウザが自動的に開きATS-4の画面が表示される

### 初回以降

1. Docker Desktopを起動しておく
2. `ats4-agc.exe`をダブルクリックで実行する
3. ブラウザが自動的に開きATS-4の画面が表示される

## 実装

[Gist](https://gist.github.com/JG1VPP/2e67b4e54f567e7f85f8251d669c9aaf)

**Comment by jucky154** [comment]
### FYI-1 ログの提出方法
ログを提出方法する方法は [https://www.youtube.com/watch?v=Yb6QY7BI4kA&t=149s](https://www.youtube.com/watch?v=Yb6QY7BI4kA&t=140s) (2:29以後)

### FYI-2 管理者としてコンテスト受付期間外でもログの提出を行う場合
ATS-4の画面としてはALL JA1コンテストのトップページと同じものが表示される。
黒枠内になる管理というボタンを押すと、管理者画面に移ることができる。
![unnamed](https://github.com/nextzlog/todo/assets/58735989/7a119821-0031-4c3e-b7e3-0bcd5ae76375)
それに対応して黒枠内も管理者画面に対応したものが表示される。黒枠内の書類提出を押す。
![unnamed-2](https://github.com/nextzlog/todo/assets/58735989/6eae1ada-e4fb-4f05-8b02-d50dd1a361e4)
書類提出画面が出る
![unnamed-3](https://github.com/nextzlog/todo/assets/58735989/d859d59e-f423-480d-8df1-4819259d27bf)
以後の提出方法は [https://www.youtube.com/watch?v=Yb6QY7BI4kA&t=149s](https://www.youtube.com/watch?v=Yb6QY7BI4kA&t=140s) (2:29以後)

### FYI-3 管理者としてコンテストのランキングの取得（表彰状の発送やランキングの公開に用いる）
ATS-4の画面としてはALL JA1コンテストのトップページと同じものが表示される。
黒枠内になる管理というボタンを押すと、管理者画面に移ることができる。
![unnamed](https://github.com/nextzlog/todo/assets/58735989/7a119821-0031-4c3e-b7e3-0bcd5ae76375)
現在のランキングを見ることができる。
ランキングのコールサインをクリックするとその局の詳しい内容が表示されます。
![unnamed-4](https://github.com/nextzlog/todo/assets/58735989/4f015987-66f2-4069-98b1-37e52bbdf61c)
一番下まで行くと、以下のようにデータ出力というボタンがあり、それを押すと、CSV(エクセルなどを用いると開ける方式）でデータが出力される。　（再計算は規約をコンテスト期間中に修正した場合などに使うものなので、基本的には使用不要。　全書類消去はコンテスト期間前にテストのために様々なログを提出したときに、コンテストに備えてログを消すために使う）
![unnamed-5](https://github.com/nextzlog/todo/assets/58735989/5d66277a-6e45-4a88-8dfc-aed6b5576b31)

CSVはエクセルから開くことからできる。エクセルを起動し、データ→データファイル→データソースの選択でCSVを選ぶ。
![unnamed-7](https://github.com/nextzlog/todo/assets/58735989/c2576252-e5c2-4dbe-8b41-80438e860358)

![unnamed-8](https://github.com/nextzlog/todo/assets/58735989/da9beaa5-0cb2-4495-a7f2-634108a21b49)

データソースへの接続という画面が出る。 ローカルファイルを選択から先ほどダウンロードした結果のCSVを選ぶ。
![unnamed-9](https://github.com/nextzlog/todo/assets/58735989/30026dfc-b21c-406b-97a7-2f161551e38b)

すると、CSVファイルの読み込み方について選択肢が出る。文字化けせず綺麗に整形される区切り記号(コンマ)/ファイル形式(MacはUTF-8, WindowsはANSI　だと思われるが適切に選択)を選んで読み込ませる
![test](https://github.com/nextzlog/todo/assets/58735989/a2732f2d-04c4-4bc5-9e40-3f5b512ed3d9)

その結果、コールサイン/参加部門/メールアドレスが並べて結果が表示される。
(一部、感想にエンターが存在することなどでズレが存在する場合があるので適切に整形が必要)

このメールアドレスの一覧を使うことでメールを容易に送信できる
同じ内容(受理したことのみ)であれば, [https://bmb.jp/maildeliver/excel-mail](https://t.co/a8D6aDtM0s) を参考に
内容を相手に対して適切に変更するのであれば、[https://support.microsoft.com/ja-jp/office/宛名の差し込みを使用して一括メール-メッセージを送信する-0f123521-20ce-4aa8-8b62-ac211dedefa4?ui=ja-jp&rs=ja-jp&ad=jp](https://support.microsoft.com/ja-jp/office/宛名の差し込みを使用して一括メール-メッセージを送信する-0f123521-20ce-4aa8-8b62-ac211dedefa4?ui=ja-jp&rs=ja-jp&ad=jp)のようなOutlookなどで差し込みを使用して一括メールをすることが可能。

### FYI-4 一部読めないサマリーシートが存在する時の対応
古いzLogが作るJARL ver1.0などの場合、適切に読み込めない場合がある。
原因 : JARL サマリーの定義不足
JARL サマリーシートの要件に関するページ : [https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/e-log.html](https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/e-log.html)　の通り、サマリーシートのログがかかれる部分は必要な内容のみが記載されているのみで、「書き方が定義されておりません」
例えば, ログの順番を59 10(受信) 59 10(送信) AM JS2FVO(送信) JA1ZLO(受信) 2023-12-31 12:00のようなよくわからない順番にしても問題ない。
ログを作るソフト(zLogやCTESTWIN)によってサマリーの作り方が違う状況である。さまざまなバージョンのログソフトを入手し、そのJARLサマリーシートを集めることで、 ATS-4は対応している
このような問題から、基本的にはJARLサマリーよりも.ZLOや.LG8というファイルでの提出をATS-4では推奨している。

すぐに対応できる手法は以下の3つ手法がある。

- ATS-4はzLogの場合は.ZLOや.ZLOXというファイルが読み込める。 ZLOGのサマリーの場合は.ZLOや.ZLOXをCTESTWINのサマリーの場合は.LG8をメールに添付して（住所などの情報はメールに記載してもらう)、再度送っていただくように依頼する。

- 若干手がかかるが、 [https://contest.jarl.org/summarymaker.htm](https://contest.jarl.org/summarymaker.htm) の一番下に行くと、「ログシート入力画面を開いて入力する場合」というボタンがあるので、そこを押す。すると、ログシート入力画面 が出てくるので、そこのローカルファイルから読み込みで、JARLサマリーのファイルを読み込ませる。そして、DATE(JST), TIME, BAND, MODE, CALLSIGN, SENTNo,RCVDNoがyyyy-mm-dd hh:mm (バンドの数字 MHz) (モード) 59 (ナンバー) 59 (ナンバー)という適切な形式になるように修正をする。その後、ローカルファイルへ保存と押すと、おそらくそのまま読み込むことのできる形式のものが出力される。

- 一番手がかかる手法、ログを真似して、CTESTWINなりZLOGでログファイル(.zloや.lg8であれば適切に読み込めるので, そのまま提出)を作るという方法

**Comment by jucky154** [comment]
### JARLサマリーで住所入力は慎重に 
JARLサマリーを用いた場合には、郵便番号を入力すると、自動読み込みされた住所が消えてしまいます。
原因としてはATS-4の開発の歴史的経緯が挙げらる。ATS-4はHPに提出する形であるが故に、ログ提出者によって住所の書き方が異なる。その際に郵便番号を書いていただける方と書かない方が存在し、表彰状を発送する際に住所形式の修正や郵便番号の検索が必要になっていた。そのため、HPの提出画面で郵便番号を入力してもらう形にした。 郵便番号によって住所の丁目までが特定できることから、住所の自動入力サービスを提供した。

ATS-4はJARLサマリーシートのみでなく、zLogの.ZLOやCTESTWINの.LG8に対応している（こちらを基本としている）ことから、 住所の入力が必要であった。一方で、JARLサマリーを提出される方にとっては、2回住所(サマリー出力, 提出)を書かないといけないという煩雑さから、JARLサマリーなのだから住所入力は簡略化して欲しいという要望があった。その結果、 JARLサマリーの場合に住所を読み込むようにした。
以上の二つが衝突したことで、「JARLサマリーから住所読み込む→郵便番号を入れる→住所が自動入力され, サマリーで読み込んだ住所が変更されてしまう」という状況である。
そのため、住所入力は不要だと思わないようにすることが必要。

**Comment by jucky154** [comment]
### LocalでATS-4を使う場合のメール自動送信について
使用しているメールサーバの設定をATS-4に入力することで、技術的にはローカル版でもメールの自動送信は可能。
しかし、サーバの設定を変更する技術が必要なことやセキュリティの面からおすすめはできない。
