### ISSUE TITLE
JARLサマリーシートの郵便番号と運用地の取り込み

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#201]
## 問題意識

現在の仕様では、JARLサマリーシートをアップロードすると、氏名や住所は自動的にフォームに記入されるが、郵便番号と運用地は記入されないため、大量のサマリーシートを処理する必要がある場合は不便。

## 解決方法

Ajaxの処理を改良して、住所から郵便番号を抽出し、部分一致した運用地を選択するようにする。
https://github.com/nextzlog/ats4/blob/master/app/views/comps/file.scala.html

**Comment by jucky154** [comment]
問題意識が「大量のサマリーシートを処理する必要がある場合は不便」というところにあるのであれば, JARLサマリーのCATEGORYCODE を読み込んで, 参加部門も対応することも同時に考えた方がいいかもしれませんね…
(ALL JA1やUECの場合は複数参加できてしまうので, その場合参加部門の書き方がおかしくなるので, 対応が難しいですが, こういう参加部門が一つ系コンテストなら書き方はある程度一意に近いので, ある程度は便利？)

**Comment by JG1VPP** [comment]
JARLサマリーシートの住所欄から郵便番号を抽出してフォームに自動入力する機能を追加しました。住所欄からは郵便番号が除去されます。郵便番号は以下の正規表現に従います。

```scala
val postal = "[\\u3012\\u3020]\\s*?\\d{3}-?\\d{4}".r
```

従って、単なる数字の羅列は郵便番号とは認識されません。

**Comment by JG1VPP** [comment]
部門や運用地は[レーベンシュタイン距離](https://qiita.com/ktamido/items/d29362cf33dba0df6cb0)により、尤もらしい候補を選択する実装とします

**Comment by jucky154** [comment]
コンテストによっては, 部門コード（ex. 電信電話のマルチオペのオールバンドがXMAのような感じ）が存在し, そこを配慮して書いてくださる人もいるので, その辺も抽出した方が良いかもしれません. (部門コードのあるコンテストでは, まず部門コードで検索をかけるみたいな）

**Comment by JG1VPP** [comment]
もともとATS-4はサマリーシート提出を前提にした設計でないため、部門コードという概念がありません。将来的に何らかの対応をするにしても、まずは部門名の編集距離をベースにした実装になります。

**Comment by JG1VPP** [comment]
JARLサマリーシートから`<CATEGORYNAME>`または`<CATEGORYCODE>`を抽出して、最適な部門を選ぶ機能を追加しました。

```xml
<SUMMARYSHEET VERSION=R2.1>
<CATEGORYNAME>55MHz</CATEGORYNAME>
</SUMMARYSHEET>
<LOGSHEET TYPE="ZLOG">
</LOGSHEET>
```

![image](https://github.com/user-attachments/assets/35641bd6-bccc-4463-8873-8fe6bc47c13b)

**Comment by jucky154** [comment]
運用地問題は結構面倒な気がしてきましたね…
(移動局の対応をどうするか…)
一般には、コンテストナンバーから取り出せばいいでしょと言われそうですが、いろんなコンテストに対応することを目的にしていると、コンテストナンバーから情報取り出すのは変ですし…

`<OPPLACE>運用地</OPPLACE>`というのがありますけど、ちゃんと書いてくれているか（運用地欄をちゃんと書くように周知するのはATS4利用者側の注意事項で周知すべきですね）

**Comment by JG1VPP** [comment]
JARLサマリーシートから`<OPPLACE>`を抽出して、最適な運用地を選ぶ機能を追加しました。

```xml
<SUMMARYSHEET VERSION=R2.1>
<CATEGORYNAME>55MHz</CATEGORYNAME>
<OPPLACE>東京都府</OPPLACE>
</SUMMARYSHEET>
<LOGSHEET TYPE="ZLOG">
</LOGSHEET>
```

![image](https://github.com/user-attachments/assets/f456f6a6-deaf-4547-8be9-97dcb8e23693)
