### ISSUE TITLE
メールの送信テスト機能

### ISSUE THREAD

**Issue by fjdj-1515** [nextzlog/todo#205]
## 問題意識
ATS-4でメール設定の検証がやりづらい

## 解決方法
管理画面で、テストメールの送信ができるようになるとうれしいと思います。

**Comment by JG1VPP** [comment]
具体的には、管理画面に任意のメールアドレスに任意の件名・本文でメールを送信できる画面を追加すれば良いでしょうか？

**Comment by fjdj-1515** [comment]
そうですね
任意で本文を入力できるようにしてもいいですし、This is a test message とか決め打ちの内容でもよいと思います。

**Comment by jucky154** [comment]
ここにぶら下げるべきか怪しいですけど、「メールの送信テスト機能」に付随して 「一斉メール機能」があると便利かもしれません

参加者全員に「暫定結果公表・異議申請に関する連絡」や「確定結果の公表・表彰に関する連絡」や「昨年度の参加者へ今年も参加を依頼」をするときに毎回BCCを使っているのですが、CCにしてしまう失敗が怖いので…

**Comment by JG1VPP** [comment]
管理画面にメール送信機能を追加しました

![image](https://github.com/user-attachments/assets/3a8a4135-dff8-4fe1-bce2-39d77025d073)
