### ISSUE TITLE
電通大コンテストの書類提出の運用地選択ですべての市区町村が表示される

### ISSUE THREAD

**Issue by fjdj-1515** [nextzlog/todo#207]
## 概要
電通大コンテストの書類提出で、例年運用地は都府県支庁までを選択してもらっていたが、プルダウンメニューにすべての市区町村が表示される。

## 再現手順・設定
・最新版のATS-4イメージ
・電通大コンテスト
・書類提出をしようとする

## 期待される動作
運用地を選択するプルダウンメニューには、都府県支庁までの一覧が表示される

## 対応期限
今週末くらい

**Comment by fjdj-1515** [comment]
直接集計に影響のあるクリティカルな問題ではありませんが、対応いただけると幸いです。

**Comment by fjdj-1515** [comment]
すみません、自己解決しそうです。
最新版では環境変数でATS4_RULE_FILEを指定しているところを、requireで変にやっていそうなので、これをちゃんとしてやれば解決する気がしてきました。

**Comment by JG1VPP** [comment]
ATS-4に内蔵の電通大コンテストの定義を使用すれば、ご要望の通りに表示されます。

![image](https://github.com/user-attachments/assets/38f4cde2-f6a0-48dc-be55-c3f81247eb41)

[README](https://github.com/nextzlog/ats4?tab=readme-ov-file#regulation)にある通り、

```yaml
environment:
  ATS4_RULE_FILE: /rules/uec.rb
```

または、`ats.conf`ファイルで、

```ini
ats4.rules = "/rules/uec.rb"
```

などと設定し、ATS-4を起動してください。
