### ISSUE TITLE
結果のCSVが参加者の"/n"や","によって崩れてしまう

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#209]
## 概要
参加者が感想欄や住所欄において、「改行を用いると、CSVファイルでは改行が行われると次の行になり」「,を使うと右にずれてしまう」
その結果、多少のCSVを整形し、その後に表彰状に必要なデータの取り出しなどを行う必要がある

## 再現手順・設定
現状のALL JA1の結果をエクセルからCSVファイルを読みとる

## 期待される動作
住所欄や感想欄で使われた「\n」は削除, 「,」は「、」に変更することで, 上の問題を解決する？

**Comment by JG1VPP** [comment]
CSV出力をエスケープ処理すると同時に改行文字を除去するように修正しました。
