### ISSUE TITLE
WW RTTYコンテストへの対応

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#213]
http://jarts.jp からATS-4を導入したいという依頼がありました
連絡先などの情報はXで添付した通りです

**Comment by jucky154** [comment]
https://github.com/jr8ppg/zLog/issues/619
この判定ロジックに従って、エンティティや大陸を判断する必要があると思われる

**Comment by jucky154** [comment]
https://www.country-files.com
にCTY.datが落ちていましたが、すごいファイルですね

どういう書き方をしているのか、すごくわかりにくい（コンピュータで読むにはどうするのが良いか…）

**Comment by JG1VPP** [comment]
JARTS側からはメンバーで検討する旨の連絡を受けたが、そのまま結局コンテスト当日を過ぎたので、このIssueは閉じます

**Comment by jucky154** [comment]
一応、聞いた話では来年のWW RTTYに導入するという感じだった記憶ですが…
