### ISSUE TITLE
QRPコンテストの規約実装

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#214]
## 概要

依頼によりQRPコンテストの規約を実装する。

**Comment by JG1VPP** [comment]
## ダウンロード

[ats4-qrp.zip](https://github.com/user-attachments/files/17446721/ats4-qrp.zip)

## 必要な環境

- インターネット接続 (Dockerイメージの自動ダウンロードに必要)
- [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- WSL2

## WSL2の準備

- [Windows＋WSL2でDocker環境を用意しよう](https://www.kagoya.jp/howto/cloud/container/wsl2_docker/)に従ってWSL2とUbuntuを準備する。

## Docker Desktopの準備

- [公式サイト](https://www.docker.com/products/docker-desktop/)からWindows版をダウンロードしてインストールする。

## 実行方法

### 初回起動

1. Docker Desktopを起動しておく
2. `ats4-update.exe`をダブルクリックで実行する
3. `ats4-qrp.exe`をダブルクリックで実行する
4. ブラウザが自動的に開きATS-4の画面が表示される

### 初回以降

1. Docker Desktopを起動しておく
2. `ats4-qrp.exe`をダブルクリックで実行する
3. ブラウザが自動的に開きATS-4の画面が表示される

## 実装

[Gist](https://gist.github.com/JG1VPP/2e67b4e54f567e7f85f8251d669c9aaf)

**Comment by JG1VPP** [comment]
提出方法の詳細は [こちら](https://github.com/nextzlog/todo/issues/199#issuecomment-2165890676)

**Comment by jucky154** [comment]
**自作のログシートの場合の対応方法**
JARLのログ提出方法としては
サマリーシート（参加者の情報入力）とログシート（交信記録）を合わせたものになっている
サマリーシート部分はある程度定義されているが、ログシート部分は自由形式になってしまっている
ATS-4はさまざまなロギングソフトを入手し解析することで、ログシートの書き方に対応しているものの、自作の書き方は対応ができない。

そのような自作の書き方のログが提出された際の対応方法としては、JARLのサイトに一度投げると適切な形式であるかを確認することがわかりやすい

[https://contest.jarl.org/summarymaker.htm](https://contest.jarl.org/summarymaker.htm%E3%80%80)
の（２）ログシート入力画面を開いて入力する場合を選びログ入力（https://contest.jarl.org/cgi-bin/logsheetform.cgi 　)に飛ぶ、 ローカルファイルから読み込みで提出されたログを読み込ませる。
そして、表示されているログが適切に全て読まれたか（YYYY-MM-DDか？　 HH:MMか？　BANDは周波数（MHz）か？）を確認する。（問題があれば修正する）問題なければローカルファイルへ保存で適切な形にされたログシートを入手できる。

うまく読み込まれなかったりしたときは手で入力していく。
局数が多い時は参加者に上記のサイトを案内しそこでログを作ってもらう。
