### ISSUE TITLE
zLog Additional I/Oで交信記録の読み書きが不可

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#218]
## 概要

https://github.com/jr8ppg/zLog/issues/701#issuecomment-2441170559

## 再現手順・設定

Import/Exportメニューから適当な書式で交信記録の読み書きを試みる。

## 期待される動作

任意の書式で読み書きができる。

## 対応期限

未定

**Comment by JG1VPP** [comment]
## 原因

Go 1.19で採用された[提案](https://github.com/golang/go/issues/38736)が原因

**Comment by jucky154** [comment]
テストをしてもらったところ以下のことがわかりました

・エクスポートは概ねうまくいってそうだが、Ctestwin の txt はバイナリが吐かれる模様。また、lg8 型式で吐いたものをCtestwinで読みこむことができない。
・インポートは何一つ上手くいかない。このプラグインで書きだしたadiファイルも"not suported" などと表示される。

ご確認のほどよろしくお願いします

**Comment by JG1VPP** [comment]
## 再現

zLog 2.9.2.5を初期化してzLog Additional I/Oプラグインをインストールし、以下に記載する書式でExport/Importを実施

|書式|エクスポート|インポート|
|---|---|---|
|Sub ADIF (ADI)| 正しく出力された | 正しく読み取れた |
|Sub ADIF (ADX) | 正しく出力された | 正しく読み取れた |
|CTESTWIN (LG8) | CTESTWINで読み取れた | 正しく読み取れた |
|CTESTWIN (TXT) | CTESTWINと同じ出力 | 正しく読み取れた |
|Turbo HAMLOG (HDB) | HAMLOGで読み取れた | 正しく読み取れた |
|JARL R2.0| ZLOファイルが出力された | 正しく読み取れた* |
|QXML | 正しく出力された | 正しく読み取れた |

*: 内容はZLOファイル

JARL R2.0の不具合は、最近のQxSLの変更でJARL R2.1という名称に変更したのが原因です。←解消済み

## テストデータ

```xml
<?xml version="1.0"?>
<list xmlns:qxsl="qxsl.org">
  <item qxsl:call="JA1AAA" qxsl:mode="CW" qxsl:time="2024-11-04T23:41:00+09:00[Asia/Tokyo]" qxsl:band="1900">
    <rcvd qxsl:code="10H" qxsl:rstq="599"/>
    <sent qxsl:code="10H" qxsl:rstq="599"/>
  </item>
  <item qxsl:call="JB1BBB" qxsl:mode="CW" qxsl:time="2024-11-04T23:41:00+09:00[Asia/Tokyo]" qxsl:band="1900">
    <rcvd qxsl:code="11H" qxsl:rstq="599"/>
    <sent qxsl:code="10H" qxsl:rstq="599"/>
  </item>
  <item qxsl:call="JC1CCC" qxsl:mode="CW" qxsl:time="2024-11-04T23:41:00+09:00[Asia/Tokyo]" qxsl:band="1900">
    <rcvd qxsl:code="12P" qxsl:rstq="599"/>
    <sent qxsl:code="10H" qxsl:rstq="599"/>
  </item>
  <item qxsl:call="JD1DDD" qxsl:mode="CW" qxsl:time="2024-11-04T23:42:00+09:00[Asia/Tokyo]" qxsl:band="1900">
    <rcvd qxsl:code="13L" qxsl:rstq="599"/>
    <sent qxsl:code="10H" qxsl:rstq="599"/>
  </item>
  <item qxsl:call="JE1EEE" qxsl:mode="CW" qxsl:time="2024-11-04T23:42:00+09:00[Asia/Tokyo]" qxsl:band="1900">
    <rcvd qxsl:code="14M" qxsl:rstq="599"/>
    <sent qxsl:code="10H" qxsl:rstq="599"/>
  </item>
</list>
```

**Comment by JG1VPP** [comment]
## 仕様

### 送信ナンバー

zLogで送信ナンバーが未設定の場合は、JARL R2.1で空欄となり、それをQxSLを使用したソフトで読み込む際に受信RSTが送信ナンバーに格納される不具合が生じます。これは未定義動作であり、そもそも送信ナンバーが未設定である交信記録はJARL R2.1の仕様に反しています。

### 空中線出力

H,M,L,PはzLogで送信ナンバーと独立した属性であり、これらはQxSLでの書式変換時に無視されるため、引き継がれません。

## 解説

zLog Additional I/OはZLOファイルを一時保存してから、それをQxSLで変換する仕組みです。従って、ZLOファイルに出力する時点で送信ナンバーが未設定であれば、上記の問題が起こります。

**Comment by JG1VPP** [comment]
JARL R2.1でエクスポートするとZLOファイルが出力される問題を解消しました。

> ・エクスポートは概ねうまくいってそうだが、Ctestwin の txt はバイナリが吐かれる模様。

再現しません。

> また、lg8 型式で吐いたものをCtestwinで読みこむことができない。

再現しません。ただし、QSOが0件の場合はCTESTWIN側でエラーとなるのを確認しました。

> ・インポートは何一つ上手くいかない。このプラグインで書きだしたadiファイルも"not suported" などと表示される。

再現しません。上記の通りです。

**Comment by JG1VPP** [comment]
上記の通り、多くの書式でインポート・エクスポートは期待通りに動作しました。

**Comment by js2ggd** [comment]
何度か、プラグインを消去し当該プラグインのインストールのやり直し、zlogwinフォルダの置き場所の変更なども試しましたが問題は解消されませんでした。あとで気づきましたが、Ctestwin型式(lg8)以下のエクスポートメニューでは、txtも含めて拡張子だけが書き換えられ、中身はzloファイルそのままになっているようです。
インポートに関しては、過去に実際に用いたCtestwinにおけるファイルの読み込みも含め、全く成功しません。上記の xml型式のテストデータを試そうとしましたがそもそもインポートができないので他形式に変換も出来ません。なおテストは v.2.9.2.5 で行っています。

**Comment by JG1VPP** [comment]
zLog Additional I/Oプラグインはqxsl.exeを呼び出すだけなので、qxsl.exeがWindowsによりブロックされるとエラーになり得ます。確認のため、qxsl.exeをダブルクリックで実行すると、瞬間的にウィンドウが開いて閉じるか確認いただけますでしょうか？

**Comment by js2ggd** [comment]
コマンドプロンプトから直接 qxsl.exe を実行したら、問題無く Usage:.... が表示されました。
\qxsl.exe test.zlo test.lg8 cbin
を実行したところ、生成したtest.lg8 は Ctestwin で読み込めました。qxsl.exe 自体は機能していそうです。

**Comment by JG1VPP** [comment]
@js2ggd zLogの設定でプラグインのフォルダをデフォルト（zlog.exeと同じ場所）から変更していませんか？手元の環境でも同様に設定すると`qxsl.exe`の起動ができず、"not supported"のエラーダイアログが表示されました。

**Comment by js2ggd** [comment]
現在の「標準」は plugin フォルダになっていますので、qxsl.exe も plugin フォルダにインストールされます。もしそれがダメだとなると、プラグイン側かzlog本体側のいずれかで何らかの対応が必要になります。

**Comment by jr8ppg** [comment]
@JG1VPP 
qxsl.exeの起動元はDLLですので、DLLの所在地となるフォルダ下のqxsl.exeを起動するようにはできませんか。

**Comment by JG1VPP** [comment]
ZyLOにはDLLの配置場所を確認する直接的な手段はありませんが、`zlog.ini`に、DLLのパスを設定する項目があります。

```ini
[zylo]
path=C:¥Users¥JA1ZLO¥Documents¥zLog
```

これを`GetINI`関数で取得し、それを起点にパスを指定する実装になります。

**Comment by js2ggd** [comment]
現在の実装では、[zylo]内のpath はプラグインのサブフォルダを示す相対パスになっていますので、それを前提に実装して頂きたいです。元々の実装であった絶対パスの表記では、zlog本体のフォルダのポータビリティがこのプラグインのために失われ、都合が悪いです。

**Comment by jr8ppg** [comment]
Win32APIが呼べるなら、GetModuleFileName()でも取得できます。
https://learn.microsoft.com/ja-jp/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea

**Comment by JG1VPP** [comment]
zLog 2.8.8.2及び2.9.2.5で上記の修正の動作確認を行いました。プラグインをアップデートして試していただけますか？

**Comment by js2ggd** [comment]
インポート、エクスポートの一部を試したところ、問題無く動作しました。対応ありがとうございます。
