### ISSUE TITLE
LoadZLO関数がZLOXをZLOとして処理する

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#226]
## 概要

ZLOXファイル（1件384バイト）をZLOファイル（1件256バイト）として処理するため、プラグイン起動時に渡されるQSOに誤りが生じる。

## 再現手順・設定

保存済みのZLOXファイルを開き、得点計算系のプラグインを起動する。

## 期待される動作

保存された件数のQSOが保存された通りの内容で`OnInsertEvent`関数に渡される。

## 対応期限

修正済み。

**Comment by jucky154** [comment]
https://github.com/nextzlog/todo/issues/220
この問題と関係ありますか？
（正しい件数の交信が読まれないのであれば、日数が減りそうではありますが…）
