### ISSUE TITLE
QSO入力UIの検討

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#30]
**問題意識**

ATS-4では、工数がかかるのでQSOの編集用UIを実装していないが、必要な場合が出てきた:

- 運営側での修正作業
- 参加者側で紙ログ等からの入力

**解決方法**

[JARLのログシート入力ページ](https://contest.jarl.org/cgi-bin/logsheetform.cgi)を参考に所定のUIを検討する。入力を終えた交信記録は、提出ボタンを押すことで従来の書類提出ページに移動できるように配慮する。その際、ファイルアップロード機能は、入力用UIに移動する。

**Comment by jucky154** [comment]
**要望**
基本思想はJARLログシート入力ページで問題ないと思います。（自分も違和感なく使っています）
JARLログシート入力ページだと時刻のhh:mmを9:7みたいに一桁で入力できてしまったり、バンドも6mや50.717みたいな適合しないものを入力できてしまいます。そのため、二桁かどうかのチェックやアマチュア無線で使用可能なバンド(MHz)かどうか（バンドはなんなら選択式にする）を確認するシステムが必要だと思います

**Comment by JG1VPP** [comment]
日付は日付のデコーダを修正するだけで対応できます。もっとも、日付の入力はDateTimePickerを使えば良いので、問題ではありません。

**Comment by jucky154** [comment]
https://github.com/nextzlog/qxsl/blob/master/src/main/resources/qxsl/ruler/allja1.lisp#L5
モードもこの辺を使って、コンテストで可能な周波数のみを選べるようにする感じにすれば良さそうですね
（参加者側に自由度を与えすぎると事故が多い気がします…）

**Comment by JG1VPP** [comment]
[bootstable.js](https://github.com/t-edson/bootstable)

**Comment by JG1VPP** [comment]
## 検討事項

QSO入力UIにアップロードした交信記録ファイルが読み取れない場合の挙動が課題。従来のUIでは、読み取れなかった場合でもそのまま提出できるが、QSL入力UIでは、読み取れなかった場合は、そのまま破棄されてしまう。

**Comment by JG1VPP** [comment]
## 検討事項

QSO入力UIと、従来のUIの整合性。

QSO入力UIは、交信記録ファイルが複数あった場合に、その内容を単一のテーブルに統合する。この時点で、交信記録は不可逆的に変換されており、ありのままの交信記録ファイルをシステムは受け取れない。つまり、ファイルが読み取れなかった場合の救済手段が限られる。

**Comment by JG1VPP** [comment]
## 検討事項

そもそも提出ページにQSO入力UIは必要なのか？

### 案

交信記録ファイル毎に編集用URLを発行し、運営側では適宜そのURLで交信記録を編集可能とする。読み取れなかったファイルに対しては、空のテーブルを表示して、更新ボタンが押されると、テーブルの内容でファイルが置換される。

**Comment by JG1VPP** [comment]
## まとめ

QSO入力UIと従来のファイルアップロードUIは相容れない。運営側では、参加者がどのようなファイルを提出してきたかに興味があり、ありのままのファイルを受け取る必要がある。QSO入力UIでは、参加者側でファイルを編集してしまうため、ありのままではない。

**Comment by JG1VPP** [comment]
## 代替案

QSO入力UIと提出ページを完全に分離する。QSO入力UIはファイルのアップロードを受け付けず、純粋に、編集可能なテーブルと、ダウンロードボタンを用意する。ダウンロードボタンを押すことで、テーブルの内容がAjaxで送信され、その内容がZLOやLG8等のフォーマットに変換され、送り返される。

**Comment by JG1VPP** [comment]
## 別の課題

運営側で、提出書類を再提出する際に、まず交信記録をダウンロードしてから、ファイル選択し直す必要がある。このUIは、実装がシンプルだがユーザビリティが悪く、改善の必要性を感じていた。

### 解決策

運営用の再提出画面からファイル選択機能を外す。また、確認画面に、交信記録を個別に削除するボタンと、交信記録を追加するファイル選択ボタンを用意する。

**Comment by JG1VPP** [comment]
ファイルを選んだ状態のフォームをサーバからクライアントに送り返すことは禁止されているので、交信記録をセットした状態でフォームを送り返すには、hidden dataにbase64でエンコードしたファイルを持たせるか、フォームとは別にファイルを受け取り、データベースに登録する必要がある。後者は、ファイルとフォームを結び付ける手段が問題。

**Comment by JG1VPP** [comment]
## 最終案

### 提出画面

従来通りのファイル添付型UIとする。ただし、QSO入力UIへのリンクを配置する。読み取れないファイルでもそのまま受け付ける。

### QSO入力画面

編集可能なテーブルと、ダウンロードボタンを配置する。ダウンロードボタンはフォーマットを選べる。提出画面にシームレスに移動する機能は、上記の経緯により省略する。

### 管理画面

再提出画面から、ファイル選択を削除する。また、交信記録ファイルは個別に削除・追加を可能とする。削除・追加はAjaxで実行する。削除・追加に成功すると、管理画面が更新される。その際に、得点が再計算される。

**Comment by JG1VPP** [comment]
@jucky154 何か良い案はありますか？

**Comment by JG1VPP** [comment]
## 課題

運営側では、参加者がどのようなファイルを提出してきたかに興味があり、ありのままのファイルを受け取る必要がある。QSO入力UIでは、参加者側でファイルを編集してしまう。

## 解決策

### 提出画面

従来通りのファイル添付型UIとする。ただし、QSO入力UIへのリンクを配置する。読み取れないファイルでもそのまま受け付ける。

### QSO入力画面

編集可能なテーブルと、ダウンロードボタンを配置する。ダウンロードボタンはフォーマットを選べる。提出画面にシームレスに移動する機能は、削除する。

**Comment by JG1VPP** [comment]
#50 BootStrap5への移行が優先される。現状のBootstrap4と互換性がなく、先にBootstrap5に移行してからでなければ、大幅な書き換えが必要。

**Comment by jucky154** [comment]
今見ました。
解決策の案が良いと思います。（実際、JARLもそういう形ですし）

**Comment by JG1VPP** [comment]
テーブルに編集用のUIを直接組み込むライブラリは、かなりトリッキーな処理をしており、メンテナンス性に不安がある。

普通のテーブルと、その下にQSO入力用のフォームを配置して、ボタンを押すとQSOを追加していく方式にした方が良い。

**Comment by JG1VPP** [comment]
![image](https://user-images.githubusercontent.com/23717324/183245484-c15d7479-bdd1-4fc9-a3ea-55971017c3c3.png)

**Comment by JG1VPP** [comment]
実装完了

![image](https://user-images.githubusercontent.com/23717324/183255811-08fdba8d-51d7-42f5-8517-22bdd143d741.png)
