### ISSUE TITLE
【電通大コンテスト】シングルバンド部門で異なる2バンドのログ提出を可能にしてほしい

### ISSUE THREAD

**Issue by karyuda** [nextzlog/todo#31]
**問題意識**
電通大コンテストにおいて、シングルバンド部門に参加する局は異なる2つのバンドまでログ提出が可能であるが、ATS-4でのバンド選択が1バンドしか選択できない。
**期待する動作**
バンド選択の欄を増やして、2バンドまでログの提出を可能にする。

**Comment by JG1VPP** [comment]
対応方針を検討します。開催は明日ですか？19時頃までに結論と実装案を提示します。

**Comment by jucky154** [comment]
電通大コンテストはただいま開催中です…

**Comment by JG1VPP** [comment]
マ？聞いてない...

**Comment by jucky154** [comment]
現状、ZGPさんも規約の運用の方で受付部分の対策はされていますが、集計時には二つの部門に参加できるようにしておく必要があると思います…
以下、規約のページ(https://www.ja1zgp.com/uectest_public_info/uectest_rule/uectest-rule-41/ )より

【変更前】
シングルバンド部門に参加する局は異なる 2 つのバンドまでログ提出が可能．その際ログは，電子ログの場合 2 通に分けて送信し，紙ログの場合サマリーシートとログシートをバンド別に分けて 2 セット作成すること
【変更後】
シングルバンド部門に参加する局は異なる2つのバンドまでログ提出が可能。その際ログは、電子メールにて 2 通に分けて送信すること。
ATS-4で提出する場合は部門の選択が1つしかできないため、電子メールのみにて異なる2つのバンドのログ提出を受け付ける。
ATS-4で提出した場合、2回に分けて提出すると上書きされて、最後に提出した書類のみ受け付けされることに注意すること。

**Comment by JG1VPP** [comment]
@karyuda この対応は緊急案件ですか？それとも次回の電通大コンテストまでの要望ですか？納期を教えてください。それによって対応が変わります。

**Comment by JG1VPP** [comment]
簡単な方法は、以下の通りです:

[entry.scala #L37'(https://github.com/nextzlog/ats4/blob/96b701468a3b226596dd549f5a9a23a048b6e820/app/views/pages/entry.scala.html#L37)を以下の通りに変更する:

```html
      @choice(form(s"section[${idx*2+0}]"), sectOpts=Rule.rule.filter(_.code == code))
      @choice(form(s"section[${idx*2+1}]"), sectOpts=Rule.rule.filter(_.code == code))
```

これで複数の部門に提出できますが、オールバンド部門に2重に提出できるなど、UIには不適切な部分が残ります。また、管理画面で書類の修正を行う際に、2個目の部門が正しく自動選択されないので、そこは手動で選んでください。

**Comment by JG1VPP** [comment]
↑とりあえず上の通りに変更すれば、今回の分は凌げる筈です。

> ATS-4に実装されている電通大コンテストの規約は、(多摩川コンテストもそうですが)あくまでATS-4のデモ用途で、本番で使う想定ではなかったので、その点はご容赦ください。

以下、次回の電通大コンテストに向けて、どのような改修が必要かを検討していきます。

**Comment by JG1VPP** [comment]
まず、↑の対応でATS-4の挙動に問題が発生してる部分を整理します。

## 書類の修正提出画面

![image](https://user-images.githubusercontent.com/23717324/179348805-cafa46c1-dab9-4e3e-814e-97d3971031da.png)
2個目の部門と運用地が正しく自動選択されない。デフォルト値（オールバンド部門, 運用地未選択) となる。

これだけですね。

**Comment by JG1VPP** [comment]
ATS-4の仕組み上、提出時さえクリアすれば、残りの部分に問題は発生しません。修正提出画面の問題は、一般の参加者からは見えず、ZGP部員にしか関係がありません。

**Comment by JG1VPP** [comment]
さて、ATS-4は、コンテストに特有の処理はDSLで実装します。何部門まで参加可能かは、DSLで定義する必要があります。厳密に言えば、`qxsl.ruler.Contest`または`Section`のプロパティとして実装する方針になりますが、もちろん現時点でそのような機能はありません。これはATS-4の外側で定義されているので、変更箇所が多岐に渡ることになります。

**Comment by JG1VPP** [comment]
`Section`は7MHz部門や14MHz部門に相当する単位です。で、個別の`Section`がどの`Section`と同時にエントリー可能かを何らかの形で定義しなければなりません。ATS-4では、`Section.code`が同じ部門は、どれかひとつしか参加できず、異なる部門であれば、同時参加可能としています。

**Comment by JG1VPP** [comment]
今回の件では、`Section.code`毎に、何部門まで参加可能かをDSLで定義できるように、QxSLライブラリを改修する必要があるということです。最も差分の少ない方法は、`Contest.getNumberOfSectionsWhichCanBeEntriedParallel(code)`というような関数を追加して、それをATS-4側で読み取るという形でしょうか。また、7MHz部門に2回エントリーできるのは、ATS-4のフォーム検証で、同じ部門が2回選択されたらエラーにすれば良さそうですね。

これ、電通大コンテストではうまくいくと思いますが、他の一般的なコンテストでも同じ実装方針で対応できるでしょうか？
@jucky154

**Comment by jucky154** [comment]
@JG1VPP 
ただいま調査しております。ぱっと、D大コンテスト以外で2部門参加できるコンテストを考えると、
オール兵庫コンテスト　：　http://hyogo27.sakura.ne.jp/653/contest/contest2022/2022-ALL-HG_rule.pdf
とかがあります。それは対応できない可能性があります。(Sectionで二つのときもあるし、Sectionを跨いで二つもあるという感じです）

**Comment by JG1VPP** [comment]
ALLJA4と兵庫コンテスト、ともに*バンドが重ならない組み合わせ*で2部門まで参加できるようですね。
これ、
1. バンドが重ならない組み合わせであること
2. 2部門まで参加できること
は、互いに依存関係になく直交してます。

このような設定が一般的だと仮定します。

1.は、`Contest.checkDuplicate(Section...sections)`というような関数を用意して、DSL側で適当に`for`ループでも回して確認してもらうのが良さそうですね。
2.は、↑の方針で大丈夫です。

**Comment by jucky154** [comment]
@JG1VPP 
シングルバンド部門二つ参加可能というのだと以下の3つくらいのグループがありそうですね…

https://www.jarl.com/kyoto/contest/KT/kiyaku66.pdf
の京都コンテストは現状案で対応可能です。 (ほぼD大コンテストと同じで、シングルなら二部門・マルチなら一部門）

http://ja4test.mydns.jp/ja4test_03.html
ALL JA４が微妙ですね(シングルなら二部門・マルチなら一部門だけでなくマルチでもHFとVUなら二部門OKという条件が…）

https://www.jarl.com/wakayama/cntest.html
和歌山だと、ALLJA1と同じ感じで行けそうです。　HFとVUから一部門ずつ（片方不参加でもOK)

**Comment by JG1VPP** [comment]
例えば、
- 14MHz部門と21MHz部門と50MHz部門は同時に参加できる
- 14MHz部門と28MHz部門と50MHz部門は同時に参加できる
- 21MHz部門と28MHz部門は同時に参加できない
とか言われると無理なんですが（UI上もややこしくなってクレームが付きそう）

**Comment by jucky154** [comment]
21MHzと28MHzを同時運用することに親を…？
（それをやるのであれば読み取り時には21MHzと28MHzを同じバンドであると認識さればできないことはなさそう）

バンドがかぶらない　＆　二部門までの案でコンテストカレンダーをだいたい調査した限りでは対応できていると思います…

**Comment by JG1VPP** [comment]
実装方針が固まったところで、電通大さんに伺いたいのですが、納期はいつに設定すれば良いですか？

**Comment by karyuda** [comment]
返信が遅れて申し訳ございません。
受付期間が終了した後でアップデートを行い、電子メールで来たログをATS-4に入れる予定でいますので、
8月末までにお願いしたいと考えております。
よろしくお願いします。

**Comment by jucky154** [comment]
@karyuda 
ATS-4の良さの一つとして、締め切りと同時に暫定結果発表が可能であるという点があるので、電子メールでのログを含めた暫定結果を発表するのであれば8/31よりもう少し前に納品する必要がありそうですね…

**Comment by karyuda** [comment]
ログ受付期間の途中でフォームを変更することは避けたいため、アップデートは受付期間終了後に行い、
締め切りから数日後にはなりますが、電子メールで来たログを入れ終わった後で暫定結果の発表を行いたいと考えております。

**Comment by JG1VPP** [comment]
## 状況

[96b7014](https://github.com/nextzlog/ats4/commit/0bb75295c2b724331a0dc302b6b922024835a963)にて対応完了。

## 修正

- 複数部門で登録可能に。
- ZLOファイルのタイムゾーン問題の解消。
- 修正提出画面で部門の自動選択の不具合の修正。

ちなみにALLJA1とリアルタイムコンテストもこの修正の恩恵で、部門選択の検査が厳しくなってます。

**Comment by JG1VPP** [comment]
## 余談

海上のコンテストナンバーの修正も含めてます。[835fdcd](https://github.com/tomato3713/qxsl/commit/5c6bbbee1210e910b7adac612f542ad19e4c9faa)で`city.ja`に項目を追加しているようですが、正しくは、`city.ja`と同じフォーマットで適当なファイルを作成し`uec.rb`から読み込むか、今回の修正のように`LocalCityItem`をアドホックに作成してリストに加える形で実装するべきです。

**Comment by JG1VPP** [comment]
@karyuda 以上で対応を完了しますが、確認いただけますか？他にも不具合があれば遠慮なく教えてください。

**Comment by karyuda** [comment]
テスト実行をしてUIが対応していることを確認いたしました。
ご対応ありがとうございます。

**Comment by JG1VPP** [comment]
もし、H2DBをRDBMSに設定している場合は、`/data`以下にある`ats4.mv.db`を必ずバックアップして、うっかり消去しないようにしてから、システムだけを差し替えてください。別途DBサーバを立てている場合は、大丈夫です。

**Comment by JG1VPP** [comment]
`ats4.mv.db`の場所は、起動モードにより変わります。開発モードの場合はレポジトリ直下に、本番モードの場合は`target/universal/stage`以下になります。注意してください。

**Comment by jucky154** [comment]
@karyuda 一応メンションしておきます

**Comment by jucky154** [comment]
「修正提出画面で部門の自動選択の不具合の修正」←ありがとうございます

多分、参加している一番上の部門と総合部門のみ自動選択が正しくてそれ以外は不参加になっているぽい？みたいなのは追跡できていたんですが、再現性がうまく出せていなくて報告していませんでした…

**Comment by karyuda** [comment]
わかりました。
ありがとうございます。
