### ISSUE TITLE
チェックログ

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#32]
**問題意識**
ATS-4にはチェックログ提出が存在しないため、チェックログ提出に対応していない

**解決方法**
部門としてチェックログという部門(ALL JA1だと総合部門のクラス）を作り、得点計算をしない・クロスチェックでは含めるという形にする
https://uectest.ja1zgp.com/forum　(のJJ2QXIさん)や ALL JA1にもチェックログ提出という人が数名いらっしゃる

**Comment by JG1VPP** [comment]
不参加で提出すれば参加扱いにならない筈です。

**Comment by jucky154** [comment]
ALL JA1だと総合部門に不参加という部門がないです。

https://uectest.ja1zgp.com/calls
みたいにどの部門にも不参加ですが案外あるのはチェックログなんですかね…（ADIによる500error提出かもしれませんが…）

**Comment by JG1VPP** [comment]
対応しました！

![image](https://user-images.githubusercontent.com/23717324/180796329-faf50cc8-301b-4e89-ae78-1975ecf33811.png)

**Comment by JG1VPP** [comment]
対応しました！

![image](https://user-images.githubusercontent.com/23717324/180827650-bec631d9-6176-4609-ad3a-d62fd15e6f5f.png)

**Comment by jucky154** [comment]
ありがとうございます！

**Comment by jucky154** [comment]
とはいえ、よくよく考えつ

**Comment by JG1VPP** [comment]
`ja1.rb`で以下のように`Contest.conflict`を実装することで対応しました:

```rb
def conflict(entries)
	muls = entries.map{|e| e.name.include?("団体")}
	alls = entries.map{|e| e.name.include?("総合")}
	in1s = entries.map{|e| e.name.include?("1エリア内")}
	js1s = entries.map{|e| /1エリア内 .+ 総合/.match?(e.name)}
	return true if muls.any? and not muls.all?
	return true if in1s.any? and not js1s.any?
	not alls.any? and not entries.empty?
end
```
