### ISSUE TITLE
ALLJA1: 総合部門の運用場所の検査

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#35]
**問題意識**

運用場所が時間により1エリア内・外を移動した場合、総合部門は1エリア外にすべき。

**解決方法**

`Contest.conflict`を実装することで可能。

**Comment by jucky154** [comment]
> 6.1. 個人部門
> 
> HIGHバンド部門/LOWバンド部門/デジタル部門において、各1部門まで参加可能
> 
> 個人部門での参加者は、全員自動的に個人総合部門（後述）にも参加となる
> 
> HIGHバンド部門/LOWバンド部門/デジタル部門は別の場所で運用できる
> ただし、時間によって運用地が1エリアの内外にまたがる場合は、1エリア内総合部門として扱う

そのため、1エリア内としてください。そうでないと、1エリア外との交信（1エリア内での運用時間)が0点になりますし、1エリア外との交信ができるので有利になってしまいます

**Comment by jucky154** [comment]
https://github.com/nextzlog/todo/issues/32
そのconflict検知する時に、個人 or 団体のどこかに参加していた場合 と　総合部門をチェックログは検知するようにしてもらえれば解決する？

また、総合部門の欄には「総合部門は全参加者が自動的に参加する部門です。どこかの部門に参加した場合は不参加を選択できません」と書いておく必要がありそうです

**Comment by JG1VPP** [comment]
`ja1.rb`で以下のように`Contest.conflict`を実装することで対応しました:

```rb
def conflict(entries)
	muls = entries.map{|e| e.name.include?("団体")}
	alls = entries.map{|e| e.name.include?("総合")}
	in1s = entries.map{|e| e.name.include?("1エリア内")}
	js1s = entries.map{|e| /1エリア内 .+ 総合/.match?(e.name)}
	return true if muls.any? and not muls.all?
	return true if in1s.any? and not js1s.any?
	not alls.any? and not entries.empty?
end
```

**Comment by jucky154** [comment]
総合部門の欄には「総合部門は全参加者が自動的に参加する部門です。どこかの部門に参加した場合は不参加を選択できません」的な文言を表示していただけると幸いです

**Comment by JG1VPP** [comment]
#59 で対応します。
