### ISSUE TITLE
Menuの下にMenuを追加する件について

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#45]
**概要**
https://github.com/jucky154/soumuAPI/issues/1#issuecomment-974664792
を実装中なのですが、
if msg.Message = w32.WM_COMMAND {　が　if msg.Message == w32.WM_COMMAND { 出ないと動かないのは置いておいて、

> hMenu1 := w32.HMENU(GetUI("MainForm.MainMenu"))
	hMenu2 := w32.CreateMenu()
	w32.AppendMenu(hMenu1, w32.MF_POPUP, hMenu2, "総務省API")

においてエラーを吐きます。理由としては、AppendMenuの3つ目の引数はuintptrでないといけないのに、HMENUがきているからです
対処方法を教えていただけると幸いです。
**再現手順・設定**
上の方法
**期待される動作**
適切にメニューが作られる
**対応期限**
なし

**Comment by JG1VPP** [comment]
これでどうですか？

![image](https://user-images.githubusercontent.com/23717324/181273067-5983b02c-adf7-4cc3-8959-453ed95ef053.png)

```go
package main

import (
	"unsafe"
	"github.com/gonutz/w32"
)

func init() {
	OnLaunchEvent = onLaunchEvent
	OnWindowEvent = onWindowEvent
}

func onLaunchEvent() {
	hMenu1 := w32.HMENU(GetUI("MainForm.MainMenu"))
	hMenu2 := w32.CreateMenu()
	w32.AppendMenu(hMenu1, w32.MF_POPUP, uintptr(hMenu2), "総務省API")
	w32.AppendMenu(hMenu2, w32.MF_STRING, 10001, "ウィンドウを開く")
	w32.AppendMenu(hMenu2, w32.MF_STRING, 10002, "利用規約")
	w32.DrawMenuBar(w32.HWND(GetUI("MainForm")))
}

func onWindowEvent(ptr uintptr) {
	msg := (*w32.MSG)(unsafe.Pointer(ptr))
	if msg.Message == w32.WM_COMMAND {
		switch msg.WParam {
 		case 10001:
			DisplayModal("OK!")
		case 10002:
			DisplayModal("come on!")
		}
	}
}
```

**Comment by jucky154** [comment]
ありがとうございます。
想定した動きになりました。（uintptrという関数があるのか…　w32の方をずっと探してしまいました）

**Comment by JG1VPP** [comment]
単に型変換しただけです。[w32.HMENU](https://pkg.go.dev/github.com/gonutz/w32/v2#HMENU)の定義を見るとわかりますが、これは`uintptr`のエイリアスなので、`uintptr`に型変換すれば問題なくコンパイルが通ります。

**Comment by jucky154** [comment]
成果です
![menu](https://user-images.githubusercontent.com/58735989/181288809-6c40c751-2f21-411f-a570-8ee170b31ef2.png)
![kiyaku](https://user-images.githubusercontent.com/58735989/181288831-5fb6d5d9-9a63-453e-93ee-e203f6c0fe4e.png)
![checklist](https://user-images.githubusercontent.com/58735989/181288845-ed4c7ca7-2674-4cda-96e8-4aa0be2b54d0.png)

**Comment by jucky154** [comment]
https://github.com/jr8ppg/zLog/blob/ZLOG2820/zlog/main.pas#L248
から情報を得ているのを
https://github.com/jr8ppg/zLog/blob/ZLOG2820/zlog/main.pas#L328
に切り替えてそのままappendすれば、Windowsタブにメニューを追加できる感じでしょうか？

**Comment by JG1VPP** [comment]
その通りです。Delphiのフォームは[dfmファイル](https://github.com/jr8ppg/zLog/blob/ZLOG2820/zlog/main.dfm)で定義されているので、そちらで確認する方が構造的でわかりやすいです。

**Comment by jucky154** [comment]
@JG1VPP 
以下のようにしてみたのですが、適切に出てきてくれません…
```
package main

import (
	"unsafe"
	"github.com/gonutz/w32"
)

func init() {
	OnLaunchEvent = onLaunchEvent
	OnWindowEvent = onWindowEvent
}

func onLaunchEvent() {
	hMenu1 := w32.HMENU(GetUI("MainForm.MainMenu.Windows1"))
	hMenu2 := w32.CreateMenu()
	w32.AppendMenu(hMenu1, w32.MF_POPUP, uintptr(hMenu2), "総務省API")
	w32.AppendMenu(hMenu2, w32.MF_STRING, 10001, "ウィンドウを開く")
	w32.AppendMenu(hMenu2, w32.MF_STRING, 10002, "利用規約")
	w32.DrawMenuBar(w32.HWND(GetUI("MainForm")))
}

func onWindowEvent(ptr uintptr) {
	msg := (*w32.MSG)(unsafe.Pointer(ptr))
	if msg.Message == w32.WM_COMMAND {
		switch msg.WParam {
 		case 10001:
			DisplayModal("OK!")
		case 10002:
			DisplayModal("come on!")
		}
	}
}
```

**Comment by JG1VPP** [comment]
複数のプラグインが同じIDでメニューを追加することはできません。また、zLog本体と競合する場合もあり得ます。IDを指定せずにメニューを追加できる、`InsertMenuItem`関数を代わりに使ってください。[w32.InsertMenuItem](https://github.com/gonutz/w32/blob/v2.5.0/v2/functions.go#L1896) [標準Windows API](http://wisdom.sakura.ne.jp/system/winapi/win32/win80.html)

**Comment by JG1VPP** [comment]
```MainForm.Windows1```です。

ところで、複数のプラグインが同じIDでメニューを追加することはできません。また、zLog本体と競合する可能性もあり得ます。IDを指定せずにメニューを追加できる、`InsertMenuItem`関数を代わりに使う手もあります。[w32.InsertMenuItem](https://github.com/gonutz/w32/blob/v2.5.0/v2/functions.go#L1896) [標準Windows API](http://wisdom.sakura.ne.jp/system/winapi/win32/win80.html)

**Comment by jucky154** [comment]
以下のようにしてもダメでした
```
package main

import (
	"unsafe"
	"github.com/gonutz/w32"
)

func init() {
	OnLaunchEvent = onLaunchEvent
	OnWindowEvent = onWindowEvent
}

func onLaunchEvent() {
	hMenu1 := w32.HMENU(GetUI("MainForm.Windows1"))
	w32.AppendMenu(hMenu1, w32.MF_STRING, 10001, "ウィンドウを開く")
	w32.AppendMenu(hMenu1, w32.MF_STRING, 10002, "利用規約")
	w32.DrawMenuBar(w32.HWND(GetUI("MainForm")))
}

func onWindowEvent(ptr uintptr) {
	msg := (*w32.MSG)(unsafe.Pointer(ptr))
	if msg.Message == w32.WM_COMMAND {
		switch msg.WParam {
 		case 10001:
			DisplayModal("OK!")
		case 10002:
			DisplayModal("come on!")
		}
	}
}
```

また、`InsertMenuItem`は`InsertMenuItem(m HMENU, item uint, byPos bool, newItem *MENUITEMINFO) bool `ですけど、
mに追加する場所、itemはなんでもいいインデックス番号、byPosはtrue、newItemはhttps://github.com/gonutz/w32/blob/v2.5.0/v2/types.go#L1057
で作る（TypeData だけUTF-16で入れれば良い？？？）というかんじでしょうか？

**Comment by JG1VPP** [comment]
原因はよくわかりませんが、`TMenuItem`をWinAPI経由で編集しても反映される様子がありませんね。そもそも、プラグインはPluginsメニューにまとめられるべきなので、そのメニューのIDを共有できるようにZyLO側にAPIを追加します。

**Comment by JG1VPP** [comment]
原因はよくわかりませんが、`TMenuItem`をWinAPI経由で編集すると、API上は設定が変更されていますが、画面で反映される様子がありませんね。

そもそも、プラグインはPluginsメニューにまとめられるべきなので、そのメニューのIDを共有できるようにZyLO側にAPIを追加します。

**Comment by JG1VPP** [comment]
原因はよくわかりませんが、`TMenuItem`をWinAPI経由で編集すると、API上は設定が変更されていますが、画面で反映される様子がありませんね。可能性としては、メニューを表示する際に、`TMenuItem`のプロパティを参照して、内容をWindows APIに反映させているのかも知れません。

そもそも、プラグインはPluginsメニューにまとめられるべきなので、そのメニューのIDを共有できるようにZyLO側にAPIを追加します。

**Comment by JG1VPP** [comment]
DLLからVCLを操作するのは、Delphiのコードに委ねた方が楽そうですね。極端な話、zLog側にコールバックを作ることもできますが、それだとzLog側がスパゲッティになるので、DLLを作りましょう。DelphiでDLLを作る資料は[こちら](http://oto.chu.jp/a.oto.chu.jp/kujira/text/delphi/dll.htm)。

**Comment by JG1VPP** [comment]
DLLからVCLを操作するのは、Delphiのコードに委ねた方が楽そうですね。極端な話、zLog側にコールバックを作ることもできますが、それだとzLog側がスパゲッティになるので、今必要な関数を用意したDLLを作って、プラグインのDLLからリンクしましょう。DelphiでDLLを作る資料は[こちら](http://oto.chu.jp/a.oto.chu.jp/kujira/text/delphi/dll.htm)。

**Comment by JG1VPP** [comment]
[VCLフォームを含むDLLを作る](https://konishih.hateblo.jp/entry/2020/03/23/210303)

[HWNDからメインアプリケーションのTFormを取り出すのは危険だという話](https://stackoverflow.com/questions/8190224/how-to-get-instance-of-tform-from-a-handle)

**Comment by jucky154** [comment]
うーんと、これは結局どうすればいいんでしょうか？

[VCLフォームを含むDLLを作る](https://konishih.hateblo.jp/entry/2020/03/23/210303)だと、本体からhWndを渡していますけど、[HWNDからメインアプリケーションのTFormを取り出すのは危険だという話](https://stackoverflow.com/questions/8190224/how-to-get-instance-of-tform-from-a-handle)だとBPLにしろだったり、すべてのコンパイラのver合わせろだったり、インターフェースかCOMを使えだったりいっていて、頭が混乱しております…

**Comment by JG1VPP** [comment]
VCLとは直接関係ないですが、LazarusのVCL相当実装であるLCLでWindows APIを操作している部分はGitHubで閲覧できます

[lcl/interfaces/win32/win32wsmenus.pp](https://github.com/User4martin/lazarus/blob/main/lcl/interfaces/win32/win32wsmenus.pp)

VCLのソースコードは...探しておきます

**Comment by JG1VPP** [comment]
VCLのソースコードはRAD Studioに付属してますね。Community Editionを入手すれば誰でも閲覧できます。

**Comment by JG1VPP** [comment]
非公開レポジトリに置く手もありますが（公開レポジトリに置くのはライセンス違反）

**Comment by JG1VPP** [comment]
Community Editionを入手して、VCLのソースコードを確認しました。当たり前ですが、`TMenuItem`の中身はDelphiのプロパティで持っていて、それが適当なタイミングでWindows Formに反映されています。

DLL側はこのプロパティにアクセスできないので、結論としては、Delphiのコードを実装するしかありません。

Delphiには、実行時型情報を操作する機能があるので、それを利用して任意のプロパティを変更する方向性で検討してみます。

**Comment by JG1VPP** [comment]
例えば、DLL側で以下の関数を呼ぶと、zLog側でRTTIによって、プロパティが変更されるのを想像しています。

```go
UpdateProperty("MainForm", "Text", "FOOBAR"); // property type can be obtained via TRttiProperty.PropertyType
UpdateProperty("MainForm", "Height", "114514");
```

**Comment by JG1VPP** [comment]
## 状況確認

Community Editionを入手して、VCLのソースコードを確認しました。
当たり前ですが、`TMenuItem`の中身はDelphiのプロパティで持っていて、それが適当なタイミングでWindows Formに反映されています。

## 結論

DLL側はこのプロパティにアクセスできないので、結論としては、Delphiのコードを実装するしかありません。

## 代替案

Delphiには、[実行時型情報を操作する機能](https://docwiki.embarcadero.com/Libraries/Sydney/en/System.Rtti)があるので、それを利用して任意のプロパティを変更する方向性で検討してみます。
例えば、DLL側で以下の関数を呼ぶと、zLog側でRTTIによって、プロパティが変更される、という感じです。

```go
UpdateProperty("MainForm", "Text", "FOOBAR"); // property type can be obtained via TRttiProperty.PropertyType
UpdateProperty("MainForm", "Height", "114514");
```

文字列、整数、浮動小数点数などのプリミティブ型に最低限対応しようと思いますが、たぶん[`TValue`で`implicit`演算子が定義されている範囲](https://docwiki.embarcadero.com/Libraries/Sydney/en/System.Rtti.TValue)で用意すれば良さそうですね。

**Comment by jucky154** [comment]
代替案のものは　#43 の最後にあるメニューの表示名を変えるものでしょうか？
それとも、追加するものでしょうか？

**Comment by JG1VPP** [comment]
@jucky154 [zLog v2.8.3.0z2](https://github.com/nextzlog/zlog/releases/tag/v2.8.3.0z2)で`RunDelphi`関数を利用可能になりました。以下のように使うことで、zLogに安全にメニューを追加できます。

```go
package main

func init() {
	OnLaunchEvent = onLaunchEvent
}

func onLaunchEvent() {
	RunDelphi(`PluginMenu.Add(op.Put(MainMenu.CreateMenuItem(), "Name", "MyMenu"))`)
	RunDelphi(`op.Put(MainMenu.FindComponent("MyMenu"), "Caption", "My Menu")`)
	HandleButton("MainForm.MainMenu.MyMenu", func (num int) {
		DisplayModal("Clicked!")
	})
}
```

なお、Win32APIを利用しても同様の結果になります。

```go
package main

import (
	"unsafe"
	"github.com/gonutz/w32"
)

func init() {
	OnLaunchEvent = onLaunchEvent
	OnWindowEvent = onWindowEvent
}

var cmd int

func onLaunchEvent() {
	RunDelphi(`PluginMenu.Add(op.Put(MainMenu.CreateMenuItem(), "Name", "MyMenu"))`)
	cmd = RunDelphi(`op.Put(MainMenu.FindComponent("MyMenu"), "Caption", "My Menu").Command`)
}

func onWindowEvent(ptr uintptr) {
	msg := (*w32.MSG)(unsafe.Pointer(ptr))
	if msg.Message == w32.WM_COMMAND {
		switch int(msg.WParam) {
 		case cmd:
			DisplayModal("OK!")
		}
	}
}
```

**Comment by jucky154** [comment]
初歩的な質問で申し訳ないのですが、
`PluginMenu`
がhttps://github.com/nextzlog/todo/issues/45#issuecomment-1200113922　で想定されているプラグインのメニューをまとめるところということでしょうか？

ひたすらに、衝突とか気にしないで（もちろん、ある程度衝突しないように引数のStringは考えるべきでしょうけど、前みたいにという意味で）PluginMenuにaddしていけばいいという感じですか

**Comment by JG1VPP** [comment]
その通りです。PluginMenuは、プラグインが提供するメニュー項目をまとめたメニューです。普段は非表示ですが、プラグインをインストールするとメニューバーに追加されます。

名前の衝突ですが、[`TComponent.Name`](https://docwiki.embarcadero.com/Libraries/Alexandria/ja/System.Classes.TComponent.Name)がコンポーネントの名前です。
([`TMenuItem`](https://docwiki.embarcadero.com/Libraries/Alexandria/ja/Vcl.Menus.TMenuItem)は`TComponent`を継承しています。)
で、この`Name`が、このコンポーネントを所有する親コンポーネント(この場合は`MainMenu`)の中で競合しなければ大丈夫です。

プロパティの設定は、`op.Put(オブジェクトまたはコンポーネント, "プロパティの名前", プロパティの値)`という関数で行います。これは、Delphi風に書けば、

```delphi
オブジェクト.プロパティの名前 := プロパティの値
```

となりますが、`RunDelphi`関数では、Delphiの小さなサブセットしか使えず、代入構文が使えません。そこで、`op.Put`という組み込み関数を用意してます。詳細は[ドキュメント](https://zylo.pafelog.net/manual)を参照してください。

コンポーネントの命名規則は工夫する必要があると思います。
例えば、

```delphi
PluginEsInfoMenu // Pluginは接頭辞, EsInfoはプラグインの名前, Menuはそのプラグイン内で通じる名前
```

という感じでしょうか。

**Comment by jucky154** [comment]
承知しました。そのように書いていきます。

**Comment by jucky154** [comment]
![PluginsMenu](https://user-images.githubusercontent.com/58735989/189534574-d9a39fa7-72b4-4c94-afc0-a9972469752c.png)
完全に理解しました。

https://github.com/jr8ppg/zLog/pull/345
が対応され次第、コードを上げておきます。

**Comment by jucky154** [comment]
ダメですね…

普通に何かが衝突しました…
総務省APIとEs情報を同時に行うとウィンドウは先に開いた方しか、動かないという問題が発生しました…。

[infoEs.txt](https://github.com/nextzlog/todo/files/9542848/infoEs.txt)
[soumuAPI.txt](https://github.com/nextzlog/todo/files/9542851/soumuAPI.txt)

**Comment by JG1VPP** [comment]
ZyLOとzLogの実装に問題があるようには見えません。あと、`HandleButton`関数を使う方が良いと思います。

```go
func onLaunchEvent() {
  RunDelphi(`PluginMenu.Add(op.Put(MainMenu.CreateMenuItem(), "Name", "PluginEsInfoWindow"))`)
  RunDelphi(`op.Put(MainMenu.FindComponent("PluginEsInfoWindow"), "Caption", "Es情報 ウィンドウ")`)

  RunDelphi(`PluginMenu.Add(op.Put(MainMenu.CreateMenuItem(), "Name", "PluginEsInfoHow"))`)
  RunDelphi(`op.Put(MainMenu.FindComponent("PluginEsInfoHow"), "Caption", "Es情報 利用方法")`)

  HandleButton("MainForm.MainMenu.PluginEsInfoWindow", func (num int) {
    abort = make(chan struct{})
    makewindow()
    EsUpdate()
    go UpdateLoop()
  })  
  
  HandleButton("MainForm.MainMenu.PluginEsInfoHow", func (num int) {
    dialog.Message("%s", "このシステムはNICTのサイトから情報を取得しています。\n15分毎に自動更新しています。").Title("利用方法").Info()
  })  
}
```

**Comment by JG1VPP** [comment]
例えば、[menu.dll](https://github.com/JG1VPP/menu)を`menu1.dll`,`menu2.dll`というように複製し、メニュー項目の`Name`も別々にした上で両方ともzLogから読み込ませてみたところ、それぞれのメニューは特に問題なく動作しました。

**Comment by jucky154** [comment]
[infoEs.txt](https://github.com/nextzlog/todo/files/9543011/infoEs.txt)
[soumuAPI.txt](https://github.com/nextzlog/todo/files/9543012/soumuAPI.txt)

このように書き換えてもダメでした。
dialogの方は適切に動くのですが、windowの方は片方動かすともう片方は開かないという問題が発生しています。
winc32の何かが良くないような気がします

**Comment by JG1VPP** [comment]
とりあえずどの行で落ちているかを分析してみてはどうでしょうか？

**Comment by jucky154** [comment]
[infoEs.txt](https://github.com/nextzlog/todo/files/9557790/infoEs.txt)
クラッシュしている行を見つけるためにひたすらにトーストを出すタイミングを至彼処に追加しました
結果としてはbefore newformまでは表示されてafter newformまでいかないので
	mainWindow = winc.NewForm(nil)
で落ちていることがわかりました。

表示を更新するためにmainWindowをグローバル変数にし、変数名を使っていることがダメなんでしょうか…

**Comment by JG1VPP** [comment]
DLLの変数は共有されません。

**Comment by jucky154** [comment]
## 症状の整理
wincのFormによるウィンドウを使うDLLで、menuからそのウィンドウを開くようにした場合、先に開いたウィンドウのみしか使えない

つまり、AというDLLのウィンドウを先に開いた場合は、Aのウィンドウを閉じてもメニューからAのウィンドウを開けるが、Bのウィンドウは開けない
（newFormで落ちている模様）

**Comment by JG1VPP** [comment]
新しい`zbuild`では、特定のバージョン以降のzLogで使える機能を使うにはバージョン指定が必要になったので注意してください。

```sh
$ zbuild compile # 2.8.0.0以降の全てのバージョンで使える (つまりRunDelphiは使えない)
$ zbuild compile 2.8.3.0 # RunDelphiが使える
```

同様にGitHub Actionsでも

```yaml
- uses: nextzlog/zylo@master
  with:
    token: ${{secrets.GITHUB_TOKEN}}
    version: 2.8.3.0
```

などと設定する必要があります。設定しない場合、やはりzLog 2.8.0.0を指定したものとなります。

**Comment by jucky154** [comment]
https://github.com/jucky154/real/issues/2
大昔あったのはGCが悪さをして、Newcontestをすると、Windowが全部消えるというのがあったが、今回は2つ目のDLLでNewFormができないなのでGCが原因ではない？　そもそもGCはDLLごとに走っているので関係ないはず。

他に考えられる事象NewFormを呼んだ時にnilを使っているが、別にwindowが存在するのでエラーを吐いている？？
（DLLは別だからありえんはず）

エラーも何も表示できないので、原因がわからないですね…

**Comment by jucky154** [comment]
現状は2.8.0.0を使う物が公開されているので、2.8.3.0以降のものをgithubにあげた際にhttps://github.com/nextzlog/todo/issues/45#issuecomment-1246991390
は対応します

**Comment by JG1VPP** [comment]
悪さをしているソースコードは絞れているので、それを移植して試すのが手っ取り早いと思いますが... 大文字で始まるメソッドはそのままプラグイン側にコピペしても使えますよ

**Comment by JG1VPP** [comment]
[winc/form.go](https://github.com/tadvi/winc/blob/33fdab6e7e584572a0ddf0313a9d8ec84b07f381/form.go#L65-L68)にある以下の2行が問題です。

```go
RegClassOnlyOnce("winc_Form")
fm.hwnd = CreateWindow("winc_Form", parent, w32.WS_EX_CONTROLPARENT|w32.WS_EX_APPWINDOW, w32.WS_OVERLAPPEDWINDOW)
```

ここで、同じウィンドウクラスで複数のDLLがウィンドウを作成すると、落ちます。

**Comment by JG1VPP** [comment]
例えば、次のようにウィンドウを作成してみれば、特に落ちることはありません。

```go
fm := new(winc.Form)
winc.RegClassOnlyOnce("winc_Form")
fm.SetHandle(winc.CreateWindow("winc_Form", nil, w32.WS_EX_CONTROLPARENT|w32.WS_EX_APPWINDOW, w32.WS_OVERLAPPEDWINDOW))
w32.SendMessage(fm.Handle(), w32.WM_CHANGEUISTATE, w32.UIS_INITIALIZE, 0)
winc.RegMsgHandler(fm)
fm.SetFont(winc.DefaultFont)
fm.SetText("Form1")
fm.Show()
```

**Comment by JG1VPP** [comment]
例えば、次のように実装すれば、特に問題なくウィンドウが表示されます。

```go
fm := new(winc.Form)
winc.RegClassOnlyOnce("winc_Form_infoEs")
fm.SetHandle(winc.CreateWindow("winc_Form_infoEs", nil, w32.WS_EX_CONTROLPARENT|w32.WS_EX_APPWINDOW, w32.WS_OVERLAPPEDWINDOW))
w32.SendMessage(fm.Handle(), w32.WM_CHANGEUISTATE, w32.UIS_INITIALIZE, 0)
winc.RegMsgHandler(fm)
fm.SetFont(winc.DefaultFont)
fm.SetText("Form1")
fm.Show()
```

**Comment by JG1VPP** [comment]
さて、このウィンドウクラスは、wincライブラリ全体にわたってハードコーディングされています。類似のwalkライブラリでも同様です。つまり、wincを丸々フォークして、グローバル変数で適当な接尾辞を設定すれば、特に競合せずに動作するはずです。

**Comment by JG1VPP** [comment]
[jg1vpp/winc](https://github.com/jg1vpp/winc)を代わりに使ってください。その際に、以下のようにDLLの名前を設定してください。

```go
func init() {
  winc.DllName = "infoEs"
}

**Comment by jucky154** [comment]
![二つ同時](https://user-images.githubusercontent.com/58735989/190702628-b205bb0a-ec27-4fec-a8bb-02a7fb1ec747.png)
適切に動きました！
ありがとうございます。これで、menuに追加する系の案件は終わったと思うのでcloseします。
