### ISSUE TITLE
再提出用のURL発行

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#53]
**問題意識**

不正防止のため、提出済みの呼出符号への上書き提出を禁止すべきでは？

**解決方法**

以前に発行されたUUIDと、URLから回収されたUUIDが一致する場合に限り、上書き提出可能とする。
再提出用のURLの再発行は、専用のフォームに、登録済みのメールアドレスを入力することで行う。

**是非**

この方法の是非を問う。ずばり、参加者側でトラブルが頻出するのではないか？

**Comment by jucky154** [comment]
参加者側でトラブル多発だと思います。（不安なので2回出される方が多いですし…）

不正防止の観点からすれば、再提出時にメールアドレスと郵便番号が一致しているか検査する。そこに誤りがある提出をしてしまった場合は管理人に連絡とかの方がいい気がします（メールアドレスだけでない理由はjarlのメアドの場合だと容易に突破されること、郵便番号は総務省APIの市区町村までのものでは推測できず、数字なのでブレが少ないかなと…（とはいえ、ハイフン入れるかとか半角全角問題があるのでそこら辺は制限する入力フォームにすべきかと…）


それかトラブルを防ぐなら、再提出専用のページを作成し、メールに来るリンクを踏んでくださいなど事細かに説明した後にメールアドレスを入力させるとかがいい気がします
