### ISSUE TITLE
【電通大コンテスト】SWLのログ提出

### ISSUE THREAD

**Issue by karyuda** [nextzlog/todo#55]
**概要**
電通大コンテストにおいてSWL部門が存在しますが、呼出符号の欄にSWLナンバー(例: JAx-xxxx)を記入した場合、「記載に漏れがあるか、修正の必要があります。」の表示 がされてログ提出ができません。

**再現手順・設定**
ATS-4で呼出符号の欄にSWLナンバー(例: JAx-xxxx)を記入して提出する。

**期待される動作**
呼出符号の欄にSWLナンバーを記入した場合のログ提出を可能にする。

**対応期限**
8月末までにお願いしたいと考えております。

**Comment by jucky154** [comment]
https://github.com/nextzlog/qxsl/blob/44bb9eb0aaee226e0a10384525fcf171d1f1ad0d/src/main/java/qxsl/draft/Call.java#L23
でコールサインの正規表現チェックをしているようなので、SWLナンバーの正規表現に関する情報を調査しました。

http://motobayashi.net/callsign/untold/swl.html
によるとSWLナンバーは JA(エリアナンバー）-(4 or 5桁の数字）のようです。

@JG1VPP ご対応よろしくお願いいたします。

**Comment by JG1VPP** [comment]
対応済み。8月31日にJA1ZGP側でどのようなアップデート作業が必要かは、今後共有します。
