### ISSUE TITLE
【電通大コンテスト】SWLのログフォーマットにてのログ提出

### ISSUE THREAD

**Issue by karyuda** [nextzlog/todo#60]
## 概要
SWLのログにおいて、コンテストナンバーを送った局、相手局、レポート、ナンバーを記録するため、UR RST(送信)の欄にコールサインを入れます。
その場合のATS-4へのログ提出ができません。

.lg8ファイルでは、「この交信記録は対応済みです。受理可能です。」と表示されましたが、提出すると500errorが出て受け付けされませんでした。その際、再提出の警告の警告には、「どの部門にも未登録です。」と表示されました。
JRALサマリーシートでは、「交信記録の書式が崩れているか、未対応です。」と表示されました。

## 再現手順・設定
CTESTWINにおいて、UrRST欄に受信局の相手局を入力したログを作成し、その.lg8ファイルをATS-4に提出する。
また、その.lg8ファイルを用いて、JRAL電子ログシート出力の設定画面にて「SWLログ(UrRSTを相手局に)」にチェックを入れて作成したJARLサマリーシートをATS-4に提出する。

## 期待される動作
以下のフォーマットに準拠したSWLのログ提出を可能にする。

ctestwinのQ&A(http://e.gmobb.jp/ctestwin/CTWFAQ.html)
102. JARL主催コンテストにSWLとして参加したい。

ロギング時にはUrRST欄に受信局の相手局を入力してください。JARL提出用に電子ログを作成する場合は、設定画面の「SWLログ(UrRSTを相手局に)」にチェックを入れてください。

JARLの規定(https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/e-log.htm)
SWLのログ
SWLの場合は、下の例のようにコンテストナンバーを送った局、相手局、レポート、ナンバーを入れます。
```
2016-04-23 21:53 50 SSB JA2Y** JA1RL* 59 20L 20 1
2016-04-23 21:53 50 SSB JA1RL* JA2Y** 59 10L 10 1
2016-04-23 22:15 7 CW JE3*** JR1**K 599 25M 25 1
```

## 対応期限
8月末までにお願いしたいと考えております。

**Comment by JG1VPP** [comment]
DSL側でRSTプロパティに599以外の文字列を格納することは認められませんが、デコーダ側でRSTとして無効な文字列を呼出符号(以下Withと呼ぶ)として処理することは可能です。また、ATS-4の確認画面にて、RSTとWithを別の欄とすることは可能です。

**Comment by JG1VPP** [comment]
## 状況整理

### CTESTWIN

CTESTWINでエラーになる原因は、UrRSTをRSTとコンテストナンバーに分離する際に、RSTが599のようなフォーマットでないために、エラーになります。なぜなら、SWLのログにはRSTがないからです。

### JARL R2.0

JARL R2.0でエラーになる原因は、下の表のように、項目の位置がずれているからです。

||1|2|3|4|5|6|7|8|9|10|11|
|---|---|---|---|---|---|---|---|---|---|---|---|
|通常|日|時|周波数|モード|呼出符号|送信RST|送信ナンバー|受信RST|受信ナンバー|マルチ|得点|
|SWL|日|時|周波数|モード|呼出符号|相手局|RST|ナンバー|マルチ|得点||

## 感想

CTESTWINはともかく、JARL R2.0の方は、どうしてこういう仕様なんでしょうか？マルチ・得点は必須ではなく、RSTとコンテストナンバーはともに数字の列なので、ログシートを見ても、それがSWLなのか、SWLでないのかを形式的に判別することが不可能です。

## 以上を踏まえて

これらをエラーなく処理するには、デコーダ及びDSLに、この交信記録ファイルがSWL特有の書式であることを知らせる必要があります。そして、QxSL及びATS-4の設計段階で、そのような処理は想定していません。対応するのに大きな手間がかかります。本件の対応は、いったん再検討します。

**Comment by jucky154** [comment]
JARL R2.0の方がなぜそういう形式かは、おそらく手書きシートがそういう感じだったからだと思います
[SWLのログシート](https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/qp/log-swl.pdf)
[普通のログシート](https://www.jarl.org/Japanese/1_Tanoshimo/1-1_Contest/qp/log.pdf)

そして、メールで送ってきた時にどうするのかというのは、一応JARLはコンテストの部門ごとにコードを決めているので、それに応じて処理しているんじゃないでしょうか…　（実際それを察してかALL JA1にもコンテストの部門ごとのコードを決めたらどうかという要望を受けたことがあります）

ATS-4だと最初にログを提出してもらっていて、受け付けられない形式だった時に全て記入してからそれに気付いて対応するより労力を減らしていますよね。
その辺と衝突していますね…

**Comment by jucky154** [comment]
あまり賢い手法ではないですけど、rubyのコンテスト定義のところにswl_on(swl_code string)という関数を作り、これを呼ばれたコンテストの場合にはJARLサマリーシートが提出された時の検査の時に「サマリーシートの<CATEGORYCODE>を読み込み、SWLまたはswl_code(関数の引数）と一致する文字列」が入っていた場合にはJARLサマリーシートをSWL形式で読むとか…

**Comment by JG1VPP** [comment]
ATS-4では、交信記録ファイルはまずデコーダで`List[Item]`に変換してから、得点計算用のDSL（つまり`uec.rb`）に渡されます。で、`uec.rb`はさらに`jautil.lisp`を呼び出して、`Item`を整形し、フォーマット間の差異を吸収してます。

```ruby
class SectionUEC < Section
	def initialize(name, band)
		super()
		@name = name
		@band = band
	end
	def name()
		@name
	end
	def getCityList()
		CITYDB
	end
	def verify(item)
		verify_item(JAUTIL.normalize(item, nil), @band) #ここ
	end
	def unique(item)
		unique_item(item)
	end
	def entity(item)
		entity_item(item)
	end
	def result(list)
		score,mults = list.toArray
		score > 0? score * mults.size: 0
	end
end
```

UrRSTをRSTとコンテストナンバーに分離する処理は、まさにここで行なわれるのですが、その際に、変換元の書式（今は`nil`）を引数で渡すことができます。これを、例えば`"SWL"`とできます。なので、CTESTWINについては、SWLに特化した処理を差し込むことができます。

残る問題はJARL R2.0ですが、仕方ないですね。RSTがRSTとしては無効だが、呼出符号としては有効な場合は、SWLモードに切り替えるようにデコーダを実装し、コンテストナンバーの欄にその内容を書き込んでDSLに渡すようにすれば、CTESTWINと同様に処理できます。

**Comment by JG1VPP** [comment]
テストデータ:

```
DATE (JST) TIME   BAND MODE  CALLSIGN      SENTNo      RCVDNo      Mlt    Pts  
2017-06-04 09:00    14 CW    QP3GES        100110      599 26      -        1    
2017-06-04 09:01    21 CW    QC1UUB        100110      599 100121  -        1    
2017-06-04 09:01    50 CW    QL1GXQ        100110      599 134410  -        1    
2017-06-04 09:02    14 CW    QO1HKK        100110      599 1113    -        1    
2017-06-04 09:02    14 CW    QP3GES        100110      599 26      -        1 
```

**Comment by JG1VPP** [comment]
対応完了
