### ISSUE TITLE
交信記録作成においてSWLは作成できない

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#65]
## 概要
交信記録がATS-4で作成できるようになったが、SWL形式(sentにコールサインを入れると出力できない）
原因としては、sent欄は数列でないといけないからだと考えれる

## 再現手順・設定
SWL形式で作成する

## 期待される動作
SWL形式のJARL ver2.1が作成される

## 対応期限
なし

**Comment by JG1VPP** [comment]
仕様です
