### ISSUE TITLE
リアルタイムコンテストの時間

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#67]
## 問題意識
ハムフェアおよびunivradioでリアルタイムコンテストの体験を行うために、コンテストの時間を0-24時としたい

## 解決方法
(defun time? it (<= 13 (時刻 it) 15))
https://github.com/nextzlog/qxsl/blob/9d3a799e93cc07c7fdd2a9c54aafbd186bced497/src/main/resources/qxsl/ruler/online.lisp#L9
の変更をお願いしたいです

**Comment by JG1VPP** [comment]
これは永久的な変更ですか？その場合、テストケースも作り直そうかと思います。

**Comment by jucky154** [comment]
永久的ではありません。
上記イベント中の体験や広報後に体験してもらうためです

**Comment by JG1VPP** [comment]
であれば、ATS-4側で対応します。

**Comment by JG1VPP** [comment]
対応完了
