### ISSUE TITLE
csvについて

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#68]
## 概要
先ほど、リアルタイムコンテストのcsvを見たところ
JA1ZGP,東京都,個人 電信電話 部門,{1+getRank(ranking)}位,,0,電通大クラブ,
のような結果表示になっていました。

## 再現手順・設定
現在のリアルタイムコンテストのcsvをご確認ください

## 期待される動作
ランキングが正しい順位のcsvを吐き出す

## 対応期限
なし

**Comment by JG1VPP** [comment]
対応完了
