### ISSUE TITLE
交信記録作成のバイナリファイルについて

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#70]
## 概要
ats4においてバイナリ系（zlo/zlox/lg8/hdb)で交信記録を作成し、ats4にそのまま提出すると崩れているとエラーを吐く

## 再現手順・設定
上述の通り

## 期待される動作
バイナリでも出せるか、表示しないことが求められる

## 対応期限
なし

**Comment by JG1VPP** [comment]
原因は判明しており、対応を検討しています。

そもそもこの機能、どこまで必要性があるかがわかりません。
ロギングソフトの代替として使う想定はしていませんし、作成済みもしくは提出済みの交信記録を編集する機能もありません。

**Comment by JG1VPP** [comment]
原因は判明しており、対応を検討しています。

そもそもこの機能、どんな状況で必要なのかがわかりません。
ロギングソフトの代替として使う想定はしていませんし、作成済みもしくは提出済みの交信記録を編集する機能もありません。

**Comment by jucky154** [comment]
使用を想定しているのは、ロギングソフトが使えない方に、ログ提出の際にどうすれば提出すればいいのかわからない（zLogもよくわからない。個人的にはzLogはgithubに上がっていますし、基本英語でできており、難しいと思われがちなので…）と言われた場合に、ここから入力して、それを出してくださいというものです。

いわば、【セーフティーネット】です

そのため、対象はコンピュータが苦手な人なので、妙に対応していない.zloとか.zloxとかあると間違えてダウンロードして提出してしまうかなと思った次第です。

**Comment by JG1VPP** [comment]
編集機能は必要なく、確実に提出できる方法だけが欲しいのであれば、提出画面に直結した方が良さそうですね。
1. フォームに隠しデータを追加して、そこに手入力の交信記録を記入し、送信
2. サーバでは、隠しデータから交信記録を取得して、書類提出の処理を行う
3. エラーがある場合は、受け取った交信記録を表にレンダリングして、フォームを返す

**Comment by jucky154** [comment]
編集機能は必須ではないと考えています。ATS-4は自分の知る限りのロギングソフトには対応しているので、それよりかは自作ログ・紙ログ基本の人たちに、主催者の代わりにいい感じのログを作ってもらうことがいいのかなと思います。

そのため、現在提案されている手法で十分だと思います。
