### ISSUE TITLE
zLogのチュートリアルページの追加

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#75]
## 問題意識

zLogの使い方を手取り足取り教えるチュートリアルが不足しており、ユーザ数が伸び悩んでいる。
一方で、GitHubのWikiは、エンドユーザにとっては敷居が高く感じるようだ。

## 解決方法

ZyLOの公式サイトに、チュートリアルページを追加する。
GitHubのWIkiをソースとして、その内容をユーザフレンドリーなUIで表示する。
GitHubのWikiを編集することで、チュートリアルページの内容も更新できる。

**Comment by JG1VPP** [comment]
ZyLOの公式サイトはJekyllを使っているので、Wikiのレポジトリごと適当なディレクトリに突っ込めば、そのまま転載できます

**Comment by jucky154** [comment]
## zLog本体について
[リグコントロール](https://github.com/jr8ppg/zLog/wiki/リグコントロール)や[zLogを用いたCQマシーン](https://github.com/jr8ppg/zLog/wiki/CQマシーンの利用)で、リグとの接続が書かれているものの、いまいちやり方がわかりにくいという話もありました

正確には、「リグごとに」「道具をすべて書き」「ウィンドウの表示が変わったりするタイミングごとに画像を添付した説明（矢印などつけて）」して欲しいということでした

なので、一応自分のもっているIC7300とFT991A(多分、この無線機二つが日本で一番多いので対応しておけばOKかなと思ってるリグ）を使って色々説明しようとは思っているのですが、その辺も表示できるようにしたいです。

## ZyLO系について
高校アマチュア無線連盟にzLog令和edition＋ZyLOで高校コンテストの得点計算ができるという紹介をしたら、その事務局の局長がZLOのOBだったので、やり方を説明するメール（メールアドレスはslackに）なりを送ってくれれば、ctestwinと同様に高校コンテスト推奨ロギングソフトとして紹介してもらえることになりました。

リアルタイムコンテストの案内と同じ資料を送れば、いい感じにしてもらえるかもしれません

**Comment by jr8ppg** [comment]
まずはですね、COMポートとはなんぞやから必要な気がするのですよ。
最近のPCは装備していないので、買うか作るかしないと駄目なんですよと。
さらにUSB接続と言ってもケーブルがUSBってだけで実体はCOMポートなので、初心者の方が？？？となるのは仕方ないところです。

**Comment by jucky154** [comment]
おそらく、ハムフェアで話した方の考えとしてはFT8を使える感じで説明して欲しいということだと思います。

http://www2s.biglobe.ne.jp/~m-nagase/ft8test/pdf/111.pdf
のような、「FT991なら無線機の設定は画像の通り、PCやソフトウェアはyaesuからインストールしてこうしてください。」みたいな感じですね。

USB接続する人(FT991やIC7300を使う人）向けには丁寧に、COMポートがどういうものか分からなくても使えるようにする

その他の無線機の場合でCOMポートを使う人には、これを買ってください・用意してください

という感じの説明するのが必要なのかなと思っています。

**Comment by JG1VPP** [comment]
@jucky154 https://zylo.pafelog.net/wiki を開くと、https://github.com/nextzlog/zylo/wiki と同じ内容が表示されます。試しに編集してみてください。Wikiを編集するたびにGitHub Actionsのワークフローが起動して、内容が反映されます。インデックス機能は今のところないです。ページ内の目次は`{:toc}`で表示できます。

**Comment by JG1VPP** [comment]
ZyLOのWikiの編集者の制限を解除しました。アカウントがあれば誰でも編集できる状態です。

**Comment by JG1VPP** [comment]
ZyLO公式サイトはzLogの新たなポータルサイトを目指します。
ということで、必要な機能は #79 にまとめていきます。
自由にコメントしてください。

**Comment by JG1VPP** [comment]
ちなみに某wikiをソースにすることも考えましたが、ページ間のリンクが絶対パスで指定されており、相対パスに変換するのが面倒だったというのが主な理由で見合わせてます。

**Comment by JG1VPP** [comment]
ちなみに某wikiをソースにすることも考えましたが...

**Comment by JG1VPP** [comment]
ちなみに某wikiをソースにすることも考えましたが...Wikiを管理してるレポジトリにCIのジョブを仕込む必要があって、かつレポジトリ間でジョブを連携させるためにはトークンをGitHubユーザー毎に発行する必要があって、運用面で面倒ですね

**Comment by JG1VPP** [comment]
https://zylo.pafelog.net/lesson に移動しました
