### ISSUE TITLE
ZyLO公式サイトの機能

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#79]
## 概要

[ZyLO公式サイト](https://zylo.pafelog.net)は、zLogの新たなポータルサイトとして、わかりやすくzLogの各種情報を提供するサイトを目指す。ここでは、必要な機能を検討する。

**Comment by JG1VPP** [comment]
## 既に存在する機能

- [zLogのバージョン履歴](https://zylo.pafelog.net/builds)
- [zLogのチュートリアル (Wiki)](https://zylo.pafelog.net/wiki)
- [プラグインの一覧](https://zylo.pafelog.net/market)
- [ZyLOのチュートリアル](https://zylo.pafelog.net/lesson)
- [ZyLOのAPIマニュアル](https://zylo.pafelog.net/manual)

**Comment by JG1VPP** [comment]
## DAT作成機能

zLogのDATファイルを最新のJCC/JCGコードに基づいて作成する機能。チェックボックスで編集する。なお、当該機能を通じたトラフィック増大を避けるため、必要なJCC/JCGリストは、GitHub Actionsでページをデプロイする際に取得しておく。

**Comment by JG1VPP** [comment]
## コンテスト単位の案内

コンテスト単位でzLogのセットアップやCFG/DATファイル、場合によってはプラグインのインストールまでの流れをウェブページに記載する。JI6DUEによるCFG/DATファイルが利用可能な場合は、そのリンクを、プラグインが必要な場合は、その操作を画像付きで表示する。どちらが利用可能かは、適宜ZyLOのレポジトリに配置したJSONファイルで管理する。

**Comment by JG1VPP** [comment]
## コンテスト単位の案内

コンテスト単位でzLogのセットアップやCFG/DATファイル、場合によってはプラグインのインストールまでの流れをウェブページに記載する。JI6DUEによるCFG/DATファイルが利用可能な場合は、そのリンクを、プラグインが必要な場合は、その操作を画像付きで表示する。以上のレンダリングは自動で行われる。コンテスト毎の設定は、Wikiに専用のフォーマットのテーブルを配置して、それで管理する。

|Contest|CFG|DAT|Plugin|
|---|---|---|---|
|Foo|https://example.com/foo.cfg|https://example.com/foo.dat|
|Bar|||pkg.bar|

**Comment by JG1VPP** [comment]
zlog.org の再編により、[ZyLO公式サイト](https://zylo.pafelog.net)は単にZyLOのリファレンスマニュアルと`market.json`を公開する役割に縮小。

- [zLog令和版ユーザーズガイド](https://use.zlog.org)
- [zLog開発情報](https://dev.zlog.org)

**Comment by jucky154** [comment]
@jr8ppg さんのwikiをどういう立ち位置に置くか検討が必要な気がします

また、現状のユーザーズガイドは散逸的
ex. 
[大見出し8のPlugin Manager](https://use.zlog.org/manual/Plugin-Manager)と[便利な機能のZyLO拡張機能](https://use.zlog.org/manual/ZyLO拡張機能)は本質的には同じものを指しています
おそらくは、上の方は単なる機能説明、下の方は新機能やzLogの売りぽい感じがしますが、統一した方がいい気がします。

、リグコントロールとCQマシーンとCWキーイングと交信の方法（CW)がバラバラに似たようなことを言っている（本質的には違うことなのは理解していますが、USB一本でできる場合は同じことになってしまう）ので、なんらかの軸を持って整理されるべきなのかなと感じました。

**Comment by jr8ppg** [comment]
同じところはまとめちゃっていいですよ

元々は完成している（みんなが知っている）zLogがあって、それ＋の部分から作り始めたが下段のところなので新機能的なものが多いです。
上段は、それだけじゃ誰もわからないので暇見て書いていますが、軸みたいなものは考えずに思いつくままなので見ての通りと言ったところです。

**Comment by jr8ppg** [comment]
私の方のWikiは use.zlog.org への案内としました。
新しい方はテーブルが崩れるところがあって、どうしたらいいのですかね。
例えばCWキーイングのCOMポート仕様のピンアサインの表

CWキーイング・・・・zLogでのキーイング
CQマシーン ・・・・・いわゆるボイスメモリーです（SSB,AM,FM）
リグコントロール・・・CWには関係無く、周波数取得などのリグ制御です。

**Comment by jucky154** [comment]
> COMポート仕様のピンアサインの表

![1664867157048@2x](https://user-images.githubusercontent.com/58735989/193756365-41f5ab6a-14bb-4e03-b249-ad571863e738.jpg)
ぱっと見は正しそうに見えますけど、どういうものを想定していますか？

CWキーイングなどの件は、タイトルで違和感を覚えたんだと思います。
装置のセットアップなのか・zLogのセットアップなのか・使い方なのかがわかりにくいなと思いました。

[交信方法（CW）](https://use.zlog.org/manual/%E4%BA%A4%E4%BF%A1%E6%96%B9%E6%B3%95%EF%BC%88%EF%BC%A3%EF%BC%B7%EF%BC%89)がCWキーイング機能の使い方で
[CWキーイング](https://use.zlog.org/manual/CW%E3%82%AD%E3%83%BC%E3%82%A4%E3%83%B3%E3%82%B0)が、装置・zLogのセットアップという感じでしょうか？

そして、同じページに装置がごちゃごちゃ書いてあると見にくいので、この装置の場合はこうやって接続しますと分離した方がいいのかなと思いました

**Comment by jr8ppg** [comment]
ごめんごめん
ピンアサインの表が崩れるのは直りました。markdownの仕様がちょっと違うみたい。使い方が違ったのかな。履歴見ればわかります。

**Comment by JG1VPP** [comment]
前後に空白行を設ければ問題ないと思います

**Comment by JG1VPP** [comment]
新ポータルサイトに移行したので、このIssueは閉じます。
