### ISSUE TITLE
プラグインをインストールした際に一部のイベントハンドラが呼ばれない

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#90]
## 概要

プラグインをインストールした際に`OnLaunchEvent`は呼ばれるが、`OnAttachEvent`や`OnInsertEvent`は呼ばれない。

## 再現手順・設定

Maplotライブラリをインストールしてウィンドウを表示すると何も表示されないのは、`OnInsertEvent`関数が呼ばれないため。

## 期待される動作

上記の関数が呼ばれる。

## 対応期限

未定

**Comment by jucky154** [comment]
Maplotに関しては小手先の解決方法かもしれませんけど、`OnLaunchEvent`の段階で、`OnInsertEvent`と同じことをすればいい気がします。
現状だと、自分の位置がプロットされないので、どこからどこまで飛んだのかが分かりにくいです（特に1局目は相手局の近くしか見えない）
そのため、自局のナンバーをcfgかiniから拾ってきて`OnLaunchEvent`で`OnInsertEvent`でやっていることを自局ナンバーでやれば良いと考えます

**Comment by JG1VPP** [comment]
`OnInsertEvent`については、プラグインが別途ログファイルを読み取る必要があります。リアルタイムコンテストのプラグインもそのように実装されています。一方で、`OnAttachEvent`は呼び出すように改修します。

**Comment by JG1VPP** [comment]
既に実装済みで、次のPRに盛り込む予定です。
