### ISSUE TITLE
モールス符号の自動解読

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#91]
## 概要

パラメータが未知のモールス符号のビート波形データから、モールス符号を解読する。誰か実装して。

## アルゴリズム

1. 全時間FFTでビート周波数を検知
2. ウェーブレット変換で信号の強度の時系列を抽出
3. 強度時系列を微分してエッジを抽出
4. エッジの時系列からビットの持続時間の時系列を算出
5. WPMを探索
6. 解読

簡単ダルルォ？

**Comment by JG1VPP** [comment]
競技プログラマならこれくらいは朝飯前のはず

**Comment by JG1VPP** [comment]
もっと単純に、スライディングウィンドウで波のエネルギーの時系列を生成し、エッジ抽出して解読するのが良さそう。

**Comment by jucky154** [comment]
https://github.com/jucky154/cwListener

1だけやりました
直流成分が存在するので、100Hz~3000Hzの範囲で最も大きい周波数をビート周波数とするとかした方が良さそうですね

wavelet変換に関してはいい感じのgolangのライブラリが見つからずという感じです

**Comment by JG1VPP** [comment]
[サンプルプログラム](https://github.com/jucky154/cwListener/issues/1)

```sh
$ go run fft.go 
cut_off 45.22485535942758
 .--- .- .---- --.. .-.. ---
```
