### ISSUE TITLE
モールス信号関連パッケージ

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#93]
## 問題意識

モールス信号関連の機能をライブラリの形でプラグインから分離してメンテナンスする。

## 解決方法

エンコーダ及びデコーダを`github.com/nextzlog/zylo/morse`というライブラリとして公開する。これを利用する形でプラグインを再整備する。

**Comment by jucky154** [comment]
http://e.gmobb.jp/ctestwin/ctestwin_main.html

ctestwinできることが多すぎる…

**Comment by jucky154** [comment]
そういえば、デコードを作るときに気がついたのですが
https://github.com/nextzlog/zylo/blob/master/modules/morse/MORSE
は、Xと*が同じ符号を使っています。
エンコードは問題ないのですが、デコードの際には気をつけてください

**Comment by JG1VPP** [comment]
[zylo/modules/morse](https://github.com/nextzlog/zylo/tree/master/modules/morse)に実装済み。エンコードはテスト完了。

**Comment by jucky154** [comment]
デコーダのテスト用音声です

- 一局version

https://user-images.githubusercontent.com/58735989/193465325-a8a83d07-0f89-4894-a3d7-6f911df7e598.mp4

- パイルアップversion

https://user-images.githubusercontent.com/58735989/193465372-743923ef-0478-454c-b502-553c2e36dcb9.mp4

**Comment by jucky154** [comment]
現状のverで悩んでいることとして、BPFをwidthをどれくらいで何回かけるべきかというのがわかってしません。
その辺の調整をお願いしたく存じます。

**Comment by JG1VPP** [comment]
[Gist](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a)に試作しました。これをコピペして使ってみてください。

**Comment by JG1VPP** [comment]
`decoder.py`, `encoder.py`, `symbols.py`を`cwListener.go`と同じ場所に置き、`cwListener.go`ではFFTによる周波数の推定を行い、デコーダを呼び出してください。これらのファイルは、いずれpkg.go.devに公開します。

**Comment by JG1VPP** [comment]
@jucky154 どうでしたか？

**Comment by jucky154** [comment]
同じ場所に置くと「found package main (cwListerner.go) and morse (decoder.go) in C: 場所」みたいなことを言って作業が始まりませんね…

**Comment by jucky154** [comment]
そして、同じ場所にmorseというディレクトリを作り、その中に入れるとなんかコンパイルの時はその中を読むのですが、関数は呼べない（importでmorseとか使うと怒ってくるのに）という状況ですね…

**Comment by JG1VPP** [comment]
Gistから拾って来れば問題ないと思いますが、Goではディレクトリレベルでパッケージを管理しているので、`main`と`morse`は同居できません。`main`パッケージに統一してください。

**Comment by jucky154** [comment]
場所を特定しました
https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a#file-decoder-go-L95
の後にtoastを入れると何も出ずに、
https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a#file-decoder-go-L89
の後にtoastを入れるとトーストが出ました

よって、この`gokmeans.Train(nodes, 2, d.epochs)`が周りが悪さをしていそうです…

**Comment by JG1VPP** [comment]
`nodes`は空ということはないですか？

**Comment by jucky154** [comment]
逆ですね
非常に多いです。[ここに
](https://gist.github.com/JG1VPP/b95770597171a801317b2a078b82150a#file-decoder-go-L89)`len(nodes)`をトーストするような文章を入れたんですが、2048とか1900とかでました…

音に入っているノイズが悪いのか、BPFやLPFが悪いのか

自分のコードの場合には生波形→BPF→二乗→LPFなのですが、今のコードは生波形→二乗→LPF→BPFですよね
その辺が影響してるんでしょうか？

**Comment by JG1VPP** [comment]
ああ、順番を間違えているので、並べ替えてください。

**Comment by jucky154** [comment]
```Go
	for i, val := range signal {
		val -= signal[0]
　　　　  val = select1.Apply(val)
　　　　  val = select2.Apply(val)
　　　　  val = select3.Apply(val)
　　　　  val = select4.Apply(val)
　　　　  val = select5.Apply(val)
　　　　  val = select6.Apply(val)
		val *= val
		val = smooth1.Apply(val)
		val = smooth2.Apply(val)
		val = smooth3.Apply(val)
		squared[i] = val
	}
```
BPFを6段、LPFを三段にすれば、二つの局を解析できました

ただ、実際のモールス音はもっと汚いので、「kmeansでエラーが起きたときのエラーハンドリングが必須機能」（zLogだとzLog本体ごと落ちるので、実際のコンテスト中だと本当にまずい）だと思います

![smoothed-4](https://user-images.githubusercontent.com/58735989/194341719-45d7c71d-6a52-4840-8974-1933794dfb21.png)

**Comment by jucky154** [comment]
その他の報告
現状のプラグインは無音になると解析を始めますけど、それ以外に任意のタイミングで解析を止めたいときがあります（パイルアップ中に、早めにコールを終えた局に応答したいが遅い局がいて、解析が始まらない）
そういう場合に対応するボタンの設置がプラグイン側には必須なのかなと思っています

**Comment by JG1VPP** [comment]
ん？`gokmeans.Train`ではエラーハンドリングをやっていますが、具体的に何か問題が起こっていますか？

**Comment by jucky154** [comment]
以前のモールスが解読できなかった（正確には[ここ](https://github.com/nextzlog/todo/issues/93#issuecomment-1268811016)のようなぐちゃぐちゃな波形を入れた）ときはなぜzLogが落ちたのかという疑問があります…
その落ちた時を調査すると`gokmeans.Train`まではコードが動いたものの、それ以降落ちるという感じでした…

**Comment by JG1VPP** [comment]
まず、エラーハンドリングは行なっているので、`panic`だと思います。それは、言わばハンドリングのしようのないエラーなので、対策できません。具体的に何がトリガーとなっているのかを把握できませんか？

**Comment by jucky154** [comment]
現状としてわかっているのは、BPFとLPFによって綺麗にした結果でもモールス信号には似つかわしくないような波形が出た場合は落ちます…
（例えば、Windowsだと音量をGUIで変更したり、トーストが出るとポーンという音がしますけど、あの音をプラグインに入れると落ちますね…　プラグインはsoundflowerみたいなもので実行している都合上、不意にこういうので落ちると困りますね…）

仮説として、考えられるのはモールスに見えないものは`detect`で空のstiringがreturnされて（okがtrueの時しかresultはないけどいいのか？）、CodetoTextでも空のstringが帰ってきて、listビューにするときに空なのでpanicするとか？

**Comment by jucky154** [comment]
上は違いますね、そもそもCodetoText関数まで行けていないんですよね…
やはり、変な音を入れると`gokmeans.Train`の周辺が怪しいようです
もう少し調査します

**Comment by jucky154** [comment]
`gokmeans.Train`は原因でなさそうでした… 
どこまで実行できたかもう一度精査します

**Comment by jucky154** [comment]
何か見えました…
解析結果をModalしたところ、表示したい文字列は[ETT]の3文字なのにlenは4文字という状況が判明しました

つまり、
https://github.com/nextzlog/todo/issues/94#issuecomment-1256404306
と同様にnill文字がリターンされているようです…

**Comment by jucky154** [comment]
前回と同様の作業をすることでpanicで落ちないようになりました…

**Comment by jucky154** [comment]
**状況**
綺麗にすると以下のような波形の音声（windowsの音量とかを調整すると出てくるポーンという警告音）を入れる
![smoothed-5](https://user-images.githubusercontent.com/58735989/194612933-d96b405a-fa24-403e-a427-e7bbdc3e12c9.png)

簡単に言えば`CodetoText(Decode())`をしてあげるとnill文字の含まれた文字列が返される

そのためにこれまではlistviewが落ちていた
**理由**
私も知りたいです…
```Go
func CodeToText(code string) (result string) {
	for _, s := range strings.Split(code, " ") {
		result += string(reverse[s])
	}
	return
}
```
がコードですけど、codeが意味のある文字列でなければ、resultには何も入りません。　それが原因とかあり得ますか？　最初にresult = ""とかしておけば解決するような気もしますけど…

**Comment by JG1VPP** [comment]
なるほど、それが原因だと思います。丁寧にやるなら、

```go
if val, ok := reverse[s]; ok {
  result += string(reverse[s])
}
```

ですが、現時点では、そのように実装されているので、それを使えば問題は起きないはずです。

**Comment by jucky154** [comment]
zyloでこれを公開する際には

```Go
if val, ok := reverse[s]; ok {
  result += string(val)
}
```
にしてもらえるとありがたいです。現場はそうしています。（それで、無線機接続で落ちる問題の一部も解決しました… ）
今まで使っていたものは最後の部分がnill文字のときにそれを処理できるようなものでしたが、現状の`CodetoText`はいろんなタイミングでnill文字が出るので落ちていたようです…

**Comment by JG1VPP** [comment]
既にそのようになっています。

**Comment by JG1VPP** [comment]
@jucky154 以下のように使用してください。

```go
package main

import (
	"fmt"
	"zylo/morse"
)

func main() {
	fmt.Println(morse.TextToCode("JA1ZLO"))
}
```
