### ISSUE TITLE
モールス信号解読プラグイン（改善：パイルを捌く能力）

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#96]
[ここから](https://github.com/nextzlog/todo/issues/94)問題の一部を分離
## 問題意識
現在の[モールス信号解読プラグイン](https://github.com/jucky154/cwListener)では、パイルアップした際には解読精度が落ちてしまう
それを改善することが求められる

## 解決方法
読んでくる人の周波数が違うと言う前提に立ち、LPFをかける前にBPF（[こういう](https://www.utsbox.com/?page_id=523)のでよい？）をかけて分離をする

FFTをかけて値が大きい3つの周波数で作ったBPFとLPFにかけて、lsitviewに横に並べて表示すれば良いか？
@JG1VPP UIや機能に関してご意見いただけると嬉しいです。

**Comment by jucky154** [comment]
https://github.com/jucky154/cwListenerBPF/blob/main/bpf.go
試験的に、一つの音声にバンドパスフィルタをかけても、いつものような波形(矩形波）が出るかを確認するためのコードを書いた

また、FFTの結果に関して、ピーク検知をしているのは今後、二つのピークを持つような音声（パイルアップを模擬）を使った場合にはその二つともが大体きれいになっているか確認できるように、その準備としてそのようにしている…

しかし、結果としてはなぜかdiffのような結果が出てきてしまい困惑している。 

@JG1VPP これは、diffとして扱っていいのか、どこかで修正すべきことがあるんでしょうか？
![smoothed](https://user-images.githubusercontent.com/58735989/193022239-2cf5f8a1-46fd-4984-b25f-793bab96b503.png)

**Comment by JG1VPP** [comment]
FIRフィルタのようなありふれた処理はライブラリを使うのが筋だと思いますが、それはそれとして、せっかくFFTでピーク周波数を求めるので、そのピーク周波数の近辺だけを残して、逆FFTで他の周波数をカットした信号を取得すれば良いだけだと思います。試してみてください。

**Comment by jucky154** [comment]
今使っている関数はhttps://github.com/mjibson/go-dsp/blob/11479a337f12/spectral/pwelch.go#L74
なので、周波数とパワーを返してくれるのですが、このライブラリをForkして書き換える必要があります…

また、現在使っているライブラリの大元のFFTは、https://github.com/mjibson/go-dsp/blob/11479a337f1259210b7c8f93f7bf2b0cc87b066e/fft/fft.go#L25 なのですが、逆変換(
https://github.com/mjibson/go-dsp/blob/11479a337f1259210b7c8f93f7bf2b0cc87b066e/fft/fft.go#L30 )の引数がfloat64なので、いまいち現在、VPPさんがおしゃっている方法を実現する手法が思いついていません…

**Comment by JG1VPP** [comment]
以下のようにすれば良いと思います。

```go
cut_width := 10
spectrum := FFTReal(source_signal)
for n := range spectrum {
  freq := float64(n) * Fs / float64(pad)
  if freq < peak_freq - cut_width {
    spectrum[n] := 0 + 0i
  } else if freq > peak_freq + cut_width {
    spectrum[n] := 0 + 0i
  }
}
target_signal := IFFT(spectrum)
```

**Comment by JG1VPP** [comment]
以下のようにすれば良いと思います。

```go
band_width := 10
spectrum := FFTReal(source_signal)
for n := range spectrum {
  freq := float64(n) * Fs / float64(pad)
  if freq < peak_freq - band_width {
    spectrum[n] := 0 + 0i
  } else if freq > peak_freq + band_width {
    spectrum[n] := 0 + 0i
  }
}
target_signal := IFFT(spectrum)
```

**Comment by jucky154** [comment]
**報告**
現状のプログラムでなぜいけないのか分かりました…

```Go
	Signal64 := make([]float64, len_sound)
	SquaredSignal64 := make([]float64, len_sound)
	for i, val := range SoundData {
		Signal64[i] = float64(val)
		SquaredSignal64[i] = float64(val) * float64(val)
	}

	powerarr, freqarr := PeakFreq(Signal64, rate_sound)
	test := DetectPeakFFT(float64(0.5), powerarr)
	
	ave_num := 6 * int(float64(rate_sound)/freqarr[test[0].index])

	bpf_freq := freqarr[test[0].index]
	smoothed := BPF(SquaredSignal64, float64(rate_sound), bpf_freq, float64(0.1))
	smoothed = LPF(LPF(LPF(LPF(smoothed, ave_num), ave_num), ave_num), ave_num)
```
と二乗した波形にBPFをかけていましたが本当にするべきは

```Go
	Signal64 := make([]float64, len_sound)
	SquaredSignal64 := make([]float64, len_sound)
	norm := float64(1.0) / float64(funk.MaxFloat32(SoundData))
	for i, val := range SoundData {
		Signal64[i] = float64(val) * norm
	}

	powerarr, freqarr := PeakFreq(Signal64, rate_sound)
	test := DetectPeakFFT(float64(0.5), powerarr)

	bpf_freq := freqarr[test[0].index]
	Signal64 = BPF(Signal64, float64(rate_sound), bpf_freq, float64(0.1))
	
	for i, val := range(Signal64){
		SquaredSignal64[i] = float64(val) * float64(val) * norm * norm
	}

	ave_num := 6 * int(float64(rate_sound)/freqarr[test[0].index])
	smoothed := LPF(LPF(LPF(LPF(SquaredSignal64, ave_num), ave_num), ave_num), ave_num)
```
以上のように「生波形」に対してBPFをかけるべきでした…

**結果の画像**
ピーク周波数に合わせた時
![smoothed](https://user-images.githubusercontent.com/58735989/193065299-aae60d82-c750-4b13-b56b-21a012550895.png)
ピーク周波数から外した時(600Hzに対して500Hzを中心とするBPF)
![smoothed](https://user-images.githubusercontent.com/58735989/193066242-4264acc1-d297-4d72-b1b6-42ec13191bed.png)
縦軸が揃っていませんが3%まで落ちているので実際には100Hzの差のある音なら区別できるようですね

**今後**
上のFFTのversionも実装してみます
100Hzで3%だと不十分なので、±10Hzの幅とかで書いてみます。

**Comment by jucky154** [comment]
ピーク周波数±10Hzの幅
![smoothed](https://user-images.githubusercontent.com/58735989/193073237-87ae10d6-8e27-46d1-bb94-45d35be07149.png)

ピーク周波数±30Hzの幅
![smoothed](https://user-images.githubusercontent.com/58735989/193073400-08ab3e9e-1ad9-4438-a37c-914dabda0ed7.png)

500±30Hzの幅
![smoothed](https://user-images.githubusercontent.com/58735989/193073773-40e33c42-12ad-419e-aafa-9bf443c7deed.png)


うまくじっそ腕着ているような気がします

**Comment by jucky154** [comment]
上だときれいな波形ですけど、しただと少し汚い波形になってしまいますね…
どちらがいいんでしょうか？

**Comment by JG1VPP** [comment]
上と下というのは何を比べていますか？実装がわかりません。あと、フィルタの特性を比較するのであれば、実際の波形とスペクトルを可視化すべきですね。

**Comment by jucky154** [comment]
**やりたいこと**
どちらの謎のFIRフィルタと逆フーリエを用いたBPFのどちらを採用するべきか判断したい

**BPF**
```Go
	Signal64 := make([]float64, len_sound)
	SquaredSignal64 := make([]float64, len_sound)
	norm := float64(1.0) / float64(funk.MaxFloat32(SoundData))
	for i, val := range SoundData {
		Signal64[i] = float64(val) * norm
	}

	powerarr, freqarr := PeakFreq(Signal64, rate_sound)
	test := DetectPeakFFT(float64(0.5), powerarr)

	bpf_freq := freqarr[test[0].index]
	Signal64 = BPF(Signal64, float64(rate_sound), bpf_freq, float64(0.1))
	
	for i, val := range(Signal64){
		SquaredSignal64[i] = float64(val) * float64(val) * norm * norm
	}

	ave_num := 6 * int(float64(rate_sound)/freqarr[test[0].index])
	smoothed := LPF(LPF(LPF(LPF(SquaredSignal64, ave_num), ave_num), ave_num), ave_num)
```
![smooth](https://user-images.githubusercontent.com/58735989/193088661-d8a706d8-6035-41ea-9b6d-dd3618425226.png)
波形


![fft](https://user-images.githubusercontent.com/58735989/193088243-2d931921-b896-4029-838a-95d0802e751b.png)
スペクトル

**IFFTを使ったBPF**
```Go
	Signal64 := make([]float64, len_sound)
	SquaredSignal64 := make([]float64, len_sound)
	norm := float64(1.0) / float64(funk.MaxFloat32(SoundData))
	for i, val := range SoundData {
		Signal64[i] = float64(val) * norm
	}

	powerarr, freqarr := PeakFreq(Signal64, rate_sound)
	test := DetectPeakFFT(float64(0.5), powerarr)

	peak_freq := freqarr[test[0].index]
	
	band_width := float64(30)

	pad := len(Signal64)
	Fs := float64(rate_sound)
	x := Signal64
	spectrum := fft.FFTReal(x)
	
	for n := range spectrum {
  	    freq := float64(n) * Fs / float64(pad)
  	    if freq < peak_freq - band_width {
    	       spectrum[n] = 0 + 0i
 	     } else if freq > peak_freq + band_width {
	       spectrum[n] = 0 + 0i
  	     }
	 }
	 target_signal := fft.IFFT(spectrum)
```
![smoothed](https://user-images.githubusercontent.com/58735989/193085634-7cdd111f-278a-4008-a4e5-0aabac25f8f8.png)
波形

![fft](https://user-images.githubusercontent.com/58735989/193087663-ed266546-5898-4716-ae79-ebcd5185fdcf.png)
スペクトル

**Comment by jucky154** [comment]
**もう一つの問題点**
テストデータを作っているのですが
https://drive.google.com/drive/folders/1-KdqGvesVxPQUC2EowUXiTo2xIE68wD3?usp=sharing
のようにJA1ZLO.wavとJA1YWX.wavの音の単純な足しあわせでは、途中で大きな音が出て、結果がおかしくなります
FFTのピークも339Hzになります（実際は600Hzと700Hz)

波形は以下のような感じです
![wave](https://user-images.githubusercontent.com/58735989/193093043-54213bdd-4b39-4387-86a4-ab7c47129d2d.png)

どのようにテストデータを作るべきでしょうか？

**Comment by JG1VPP** [comment]
FFTは定常信号を想定しているので、モールス信号に対しては特性が悪そうですね。その点、双二次フィルタは忠実な波形を取り出せると思いますが、今回は急峻な特性を得たいので、IIR2次フィルタを使うのが良いと思います。

**Comment by jucky154** [comment]
現状のFIRフィルタでは
![wave](https://user-images.githubusercontent.com/58735989/193100722-6ab51a6e-b611-4c00-bd20-6a1a0e5116b1.png)
という二つの音声の重ね合わせを
![smooth](https://user-images.githubusercontent.com/58735989/193100768-db9bfd1d-9f6c-4839-b102-b7d99ae335bc.png)
くらいまでにはできるようです…

**Comment by jucky154** [comment]
IIR二次はgolangにパッと調べた限りはライブラリがなさそうですね…

https://pkg.go.dev/github.com/bitmark-inc/bitmarkd/difficulty/filters#IIR.Filter
は、main branchではなさそうですし、なんかすでに係数が入っているので使いにくい…

**Comment by JG1VPP** [comment]
基本的には、双二次フィルタを多段接続して、望みの特性を得ることになります。

**Comment by jucky154** [comment]
双二次フィルタ(https://github.com/moutend/go-equalizer というライブラリを使いました）を5段接続して、以下のような波形の音声から
![wave](https://user-images.githubusercontent.com/58735989/193227227-624eb883-9bfa-40fa-968a-9429364d7373.png)
したのような波形を抽出し
![bpf](https://user-images.githubusercontent.com/58735989/193227325-48a2ce6c-aae6-42da-8d2d-4593bc3d5838.png)
そしてパワーにすると
![smooth](https://user-images.githubusercontent.com/58735989/193227394-d25a9337-c35d-4acb-91f2-e4d53f5b081e.png)
ちょっと歪ですが（morse runnerで作ったのでノイズが背景にあるためその影響か？）、おそらくモールスを解読できそうな感じにはなりました。

プラグインの方に実装してみます

**Comment by jucky154** [comment]
プラグインの方に実装しました

https://drive.google.com/file/d/1Mepga44Sl7TJw4OnUW-gvHtR5Q6InRv0/view?usp=sharing
という音声を入れてみたところ
![pileup](https://user-images.githubusercontent.com/58735989/193252820-d3131a89-80ea-4c98-ae15-15da3e0c1d51.png)
このような感じで二つの周波数で、こういう二つの文字列があるよということがわかります。

信号の描画がbottomに設置したリストビューによって見えなくなっていますが、

![smoothed0](https://user-images.githubusercontent.com/58735989/193253010-7267f581-8734-4478-a550-c77bce5d7459.png)
![smoothed1](https://user-images.githubusercontent.com/58735989/193253015-586d5cbb-a844-429f-b092-4d74bfa11113.png)
こういう感じできれいに解析できていそうです
