### ISSUE TITLE
モールス信号解読プラグイン（改善：途切れなくモールスを解読）

### ISSUE THREAD

**Issue by jucky154** [nextzlog/todo#97]
## 問題意識
[ここから](https://github.com/nextzlog/todo/issues/94)問題の一部を分離
![morserunner](https://user-images.githubusercontent.com/58735989/192333274-a6f3dbeb-95aa-4f6a-9bd0-6cf233773192.png)
試しに作ったプラグインでmorse runnerをやってみた
感じた問題点としては

- リアルタイムではないため一瞬応答が遅れる（これに関しては精度と引き換えなので仕方がない；諦める）

- morse runnerのコンテストのやり方になれていないので応答に失敗する（これは開発者が慣れましょうと言う感じ）

- 相手からの送出が終わっていないのに、録音が終了してしまい解読に入ってしまい、文章やコールサインが途切れてしまう
-- 一応は、現状の描画なしでやってみたものの解読にも体感0.1秒はかかるので、JがEとMにわかれてしまう。
-- この感じだと繰り返しコールサインやナンバーを聞くことができる呼び回りにおいては強い力になりそう（特に新人育成とか）

## 解決方法
考える必要あり

![1664210995167@2x](https://user-images.githubusercontent.com/58735989/192335227-4a50294d-4df2-4704-8bbf-99f507c7e586.jpg)
こう言う感じで2つの録音を同時にやって解読をいい感じのタイミングでやる？（タイミングは計らないとヤバそう）

@JG1VPP どうでしょうか？

**Comment by JG1VPP** [comment]
そもそも今の実装はなぜ毎度デバイスを初期化しているのでしょうか？最初に一度だけ初期化して、その後はコールバック関数が呼ばれ続けるので、そこで音声データを受け取り、一定程度蓄積したら解析し、追加の文字列を検出して、それを表示すれば良いと思います。また、無音の時間が一定程度続いたら、バッファをクリアすれば良いでしょう。

**Comment by jucky154** [comment]
**毎度デバイスを初期化している理由**
- デバイスをコンボボックスで選択しているので、コンボボックスの選択に変更があった時でも毎度初期化する実装なら簡単
- デバイスとの接続が切れたとしても初期化するときにerrorが発生するので切れたことを検知でき、その対応ができる
-- コールバック関数ではerrorはでず、録音中に音声デバイスとの接続が切れた場合はどうなるか挙動がよくわからない。（単純に落ちるとzLogごと落ちるので保存されていないデータがあったとき問題になるので結構保守的に書きました）

**解決する方法について**
最初はウィンドウを作るときに `device`はグローバル変数にして以下のような初期化&録音開始を実行する（一部引数とかはコピペなので適宜修正しますが…）
```
func initdevice(){
　　ctx, err := malgo.InitContext(nil, malgo.ContextConfig{}, func(message string) {
		DisplayToast(message)
	})
	if err != nil {
		DisplayToast(err.Error())
		err_result := make([]int32, 0)
		return err_result, err

	}

	deviceConfig := malgo.DefaultDeviceConfig(malgo.Duplex)
	deviceConfig.Capture.Format = malgo.FormatS32
	deviceConfig.Capture.Channels = 1
	deviceConfig.Playback.Format = malgo.FormatS32
	deviceConfig.Playback.Channels = 1
	deviceConfig.SampleRate = samplerate
	deviceConfig.Capture.DeviceID = availabledevices[machinenum].deviceid
	deviceConfig.Alsa.NoMMap = 1

	var capturedSampleCount uint32
	pCapturedSamples := make([]byte, 0)

	sizeInBytes := uint32(malgo.SampleSizeInBytes(deviceConfig.Capture.Format))
	onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {

		sampleCount := framecount * deviceConfig.Capture.Channels * sizeInBytes

		newCapturedSampleCount := capturedSampleCount + sampleCount

		pCapturedSamples = append(pCapturedSamples, pSample...)

		capturedSampleCount = newCapturedSampleCount

	}

	captureCallbacks := malgo.DeviceCallbacks{
		Data: onRecvFrames,
	}
	device, err := malgo.InitDevice(ctx.Context, deviceConfig, captureCallbacks)
	if err != nil {
		DisplayToast(err.Error())
		err_result := make([]int32, 0)
		return err_result, err
	}

	err = device.Start()
	if err != nil {
		DisplayToast(err.Error())
		err_result := make([]int32, 0)
		return err_result, err
	}
　　return
}
```

次に録音や解析については `pCapturedSamples`をグローバル変数にして以下の関数を一定時間ごとに行うということでしょうか？
```
func record_analysis(){
	Signalint := make([]int32, len(pCapturedSamples)/4)
	buffer := bytes.NewReader(pCapturedSamples)
	binary.Read(buffer, binary.LittleEndian, &Signalint)
　　
　　if Signalint[-ある程度の長さ].Max < 閾値 {
		//無音と考えてバッファーをクリア（ここの問題点は閾値をうまくしないと永遠とバッファークリアされないので溜まっていく…）
		pCapturedSamples := make([]byte, 0)
	}

	Signalintでモールスを解析
　　モールスの解析結果で、前と違う文字列のところから表示（ここの問題点は解析精度によっては全く違う文字列になって、前解析されたのに表示された文字が出てくるが、よいのか）
}
```

そして、コンボボックスで録音機器の変更があったときには
[コンボボックスの変更を検知する関数](https://pkg.go.dev/github.com/scroot/winc#ComboBox.OnSelectedChange)の中に
```
func comboboxchange(){
	device.Uninit()
	initdevice()
}
```
と言う感じでしょうか？

**Comment by JG1VPP** [comment]
`onRecvFrames`関数は少しずつサンプルを受け取っているんですよね？そのサンプルが無音であるかは、周波数領域でのパワーの分布が平坦であるかどうかによって決まります。サンプルが無音であった場合は、そのサンプルを捨て、バッファの内容をgoroutineに引数で渡して解析すれば良いでしょう。それと同時にバッファをクリアします。これで、遮られることなく常時録音され続けるはずです。

コンボボックスについては、通常、コンボボックスの値が切り替わった時にデバイスを初期化するというような処理を組むはずです。なので、一定時間毎に初期化をする必要はありません。録音時間のコンボボックスはもはや不要です。

**Comment by JG1VPP** [comment]
> そして、コンボボックスで録音機器の変更があったときには [コンボボックスの変更を検知する関数](https://pkg.go.dev/github.com/scroot/winc#ComboBox.OnSelectedChange)の中に
> 
> ```
> func comboboxchange(){
> 	device.Uninit()
> 	initdevice()
> }
> ```
> 
> と言う感じでしょうか？

はい。コンボボックスの値が切り替わるたびに初期化すれば十分です。

> 次に録音や解析については `pCapturedSamples`をグローバル変数にして以下の関数を一定時間ごとに行うということでしょうか？
> 
> ```
> func record_analysis(){
> 	Signalint := make([]int32, len(pCapturedSamples)/4)
> 	buffer := bytes.NewReader(pCapturedSamples)
> 	binary.Read(buffer, binary.LittleEndian, &Signalint)
> 　　
> 　　if Signalint[-ある程度の長さ].Max < 閾値 {
> 		//無音と考えてバッファーをクリア
> 		pCapturedSamples := make([]byte, 0)
> 	}
> 
> 	Signalintでモールスを解析
> 　　モールスの解析結果で、前と違う文字列のところから表示
> }
> ```

いいえ。`onRecvFrames`関数の中で、受け取った音声データが無音であれば、それまでに録音した内容を解析すると同時に、バッファをクリアするだけです。

```go
onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {
	// ここでint32に変換しておく
	Signalint := make([]int32, framecount)
	buffer := bytes.NewReader(pSample)
	binary.Read(buffer, binary.LittleEndian, &Signalint)

	if IsSilent(pSample) {
		go Decode(pCapturedSamples)
		pCapturedSamples = make([]byte, 0)
	} else {
		pCapturedSamples = append(pCapturedSamples, buffer...)
	}
}
```

`capturedSampleCount`などは不要な変数なので消してください。`framecount`は、モールス信号の速度と比べても十分に小さな値ですよね？無音であるかは、周波数領域でのパワーの分布が平坦であるかどうかによって決まります。これで、遮られることなく常時録音され続けるはずです。

**Comment by jucky154** [comment]
`framecount`は指定していないです…（コピペプログラマーで申し訳ないです…）

`IsSilent`関数はpSampleを引数とするのではなく、`Signalint`でFFTをして200~2000Hzの間の最小値/最大値が0.7以上でtrueとする関数ということですか？

**Comment by jucky154** [comment]
`framecount`はサンプリング周波数を44100とすると、441のようです。
つまり、1/100秒ごとにデータが送られていると思います。　そのため、モールス信号の速度と比べても十分に小さな値だと思います。

**Comment by JG1VPP** [comment]
短すぎますね。適当な閾値を決めて、その秒数だけ無音であれば、解析を始めるようにしましょう。固定値で1秒相当で良いと思います。

**Comment by JG1VPP** [comment]
短すぎますね。適当な閾値を決めて、その秒数だけ連続で無音であれば、解析を始めるようにしましょう。固定値で1秒相当で良いと思います。

**Comment by JG1VPP** [comment]
この辺りの調整は、[WPM](https://www.jh4vaj.com/archives/10328)を参考にすれば良いと思いますが、わざわざ設定項目にする必要はないと思います。5WPMで長点が720ms程なら、1秒間無音なら、1文字の区切りとしては十分です。10WPMなら、1秒間無音ということは、単語の区切りですらありません。つまり、実用上、この設定で問題なく文章を解釈できるはずです。

**Comment by jucky154** [comment]
''deviceConfig.PeriodSizeInMilliseconds = uint32(100)''
および
'''Go
onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {
		fmt.Println(framecount)
		sampleCount := framecount * deviceConfig.Capture.Channels * sizeInBytes
		newCapturedSampleCount := capturedSampleCount + sampleCount
		pCapturedSamples = append(pCapturedSamples, pSample...)
		capturedSampleCount = newCapturedSampleCount
	}
'''
と試しに実行しても、2048で帰ってきますね…
（100を1000にしても変わらずです… 最大値が2048で決まっているような気がします…

**Comment by JG1VPP** [comment]
では、短期記憶用のリングバッファを用意して、そこにサンプルを追加して行く実装にしましょう。車輪の再発明になるので、リングバッファはライブラリを使ってください。1秒間の波形でFFTを行い、無音でなければ、長期記憶用のバッファに追加して行けば良いはずです。

**Comment by JG1VPP** [comment]
あと、最終的なプロダクトには、音源を設定する以外の設定項目をなくしましょう。

**Comment by jucky154** [comment]
つまりは以下のような感じですかね…

```Go
import "container/ring"
var ringbuffer *ring.Ring

//1秒に当たるバッファーを作る（つまりはサンプリング周波数かける1)
ringbuffer = ring.New(int(Sampling_Rate) * 1)
for i := 0; i < n; i++ {
		ringbuffer.Value = uint32(0)
		ringbuffer = ringbuffer.Next()
}

onRecvFrames := func(pSample2, pSample []byte, framecount uint32) {
	// ここでint32に変換しておく
	Signalint := make([]int32, framecount)
	buffer := bytes.NewReader(pSample)
	binary.Read(buffer, binary.LittleEndian, &Signalint)
       for _, val := range(Signalint){
		ringbuffer.Value = val
		ringbuffer = ringbuffer.Next()
	} 

	if IsSilent(ringbuffer) {
		go Decode(pCapturedSamples)
		pCapturedSamples = make([]byte, 0)
	} else {
		pCapturedSamples = append(pCapturedSamples, Signalint...)
	}
}

IsSilent(ringbuffer *Ring) bool {
	len_buffer:=  ringbuffer.Len()
        buffer_float64 := make([]float64, len_buffer)
	for i := 0;  i < len_buffer; i++{
		buffer_float64[I] = float64(ringbuffer.Value)
		ringbuffer = ringbuffer.Next()
	}
 
	var opt spectral.PwelchOptions

	opt.NFFT = 4096
	opt.Noverlap = 1024
	opt.Window = nil
	opt.Pad = 4096
	opt.Scale_off = false

	Power, Freq := spectral.Pwelch(buffer_float64, float64(sampling_freq), &opt)

	peakFreq := 0.0
	peakPower := 0.0
        lowPower := float64(math.power(2, 32))
	for i, val := range Freq {
		if val > 200 && val < 2000 {
			if Power[i] > peakPower {
				peakPower = Power[i]
			}
			if Power[i] > lowPower {
				lowPower = Power[i]
			}
		}
	}

        switch{
	case  lowPower/peakPower > 0.7 :
		return true
	default :
		return false
	}
}
		
```

**Comment by JG1VPP** [comment]
秒数などの定数は、リテラルではなく名前を付けて管理しましょう。

**Comment by jucky154** [comment]
@JG1VPP 
https://github.com/jucky154/cwListener/blob/main/cwListener.go
上のように実装しましたが、2点ほど微妙なことが出てきました

**スタートの部分がおかしくなる**
![freak-bimyo](https://user-images.githubusercontent.com/58735989/192804022-7db3dc79-db32-4029-9702-22ca74a908d6.png)
CWfreakをやらせたところ、スタートがダメです
その理由として考えられるのは、無音は[ここ](https://github.com/jucky154/cwListener/blob/main/cwListener.go#L707)のように周波数成分の最大値最小値の比で評価していますが、音が始まった最初はこの比の部分はほぼ音無と同じ状況（特に窓関数がかかっているのもあると思われる）なので、最初は無音として取られてしまい、立ち上がりが遅れている。

これに関しては`deviceConfig.PeriodSizeInMilliseconds`を大きくして`framecount`を最大値にしても発生しました。


**無音の評価**
無音は[ここ](https://github.com/jucky154/cwListener/blob/main/cwListener.go#L707)のように周波数成分の最大値最小値の比で評価していますが、その場合ノイズが入っていた場合値が0~0.01のように小さくてもminが0のとき/音ありが10^7とかの値でもノイズのときにmin=0.1, max=10の場合はフラットと評価できないという感じで、永遠と録音をし続ける（デコードに入らない）という状況になりました。

機械の値によって影響を受けないように周波数領域がフラットということで評価しようとしていますが、どうもうまくいきません…

**Comment by JG1VPP** [comment]
状況がよくわからないのですが、これは以前は問題なくデコードできていたと言うことですか？

**Comment by JG1VPP** [comment]
仮説を元に対策を考えても何も進みません。無音の判定が問題ということであれば、まず波形を見せていただけないですか？

**Comment by jucky154** [comment]
録音全体の波形とFFTは以下のとおりです…
ノイズが600Hzくらい中心にしたカイ二乗分布みたいになっていますね…
200Hz~2000Hzにおける`最小値 / 最大値 > 0.7`という基準でやっていましたが、微妙ですね…

**波形**
![smoothed](https://user-images.githubusercontent.com/58735989/192833474-5d299e63-89bd-487b-a9c8-dabe6cf36c91.png)
**FFT**
![FFT](https://user-images.githubusercontent.com/58735989/192833530-cbb2bbe0-d3f3-4e72-b132-8cba4a7e9188.png)

**Comment by JG1VPP** [comment]
これはピーク周波数が埋もれているので、十分に平坦な分布と言えるのではないですか？全周波数の平均をプロットしてみてください。

**Comment by jucky154** [comment]
![FFT-2](https://user-images.githubusercontent.com/58735989/192841307-3b0bd4c7-0777-4318-a35d-1a7b07c5010a.png)
200-2000Hzの周波数のPowerの平均値をとってみました…

**Comment by JG1VPP** [comment]
それで合っています。理想的なモールス信号でも同じようにスペクトルを可視化してみてください。それで無音の判別方法がわかると思います。

**Comment by jucky154** [comment]
![FFT-3](https://user-images.githubusercontent.com/58735989/192844209-ef18a02c-f089-4638-9907-99ee4c4fddd3.png)

1. ピークが非常に尖っているので、`平均を超える部分の点数 / 平均を超えない部分の点数` （比が1/5を切るとか？）で評価する
2. 平均値とピークの値で評価する（結構、環境依存しそう）

この二つという感じですか？

**Comment by JG1VPP** [comment]
2で十分だと思います

**Comment by jucky154** [comment]
https://github.com/jucky154/cwListener/blob/main/cwListener.go#L722
のようにピークが平均値の10倍以上かどうかで区別しました
立ち上がり時などに妙な文字列が並んだのでもう少しこの10倍という値がいいかどうかは検討したほうがいい気がしますね

![morserunner-2](https://user-images.githubusercontent.com/58735989/192854384-71fede25-a42b-4010-8821-5599414eac09.png)
morse runnerを一局やりましたけど結構簡単に話せる感じですね

**ちょっと検討が必要なところ**
https://github.com/nextzlog/todo/issues/97#issuecomment-1260573426
で1秒間を基準にしていますが、CQを出した後にすぐに応答されるので、自分のCQと相手の応答が一緒の回にデコードに回されてしまいますね…

**Comment by JG1VPP** [comment]
実用上は自分の送信したメッセージと相手から受信したメッセージを分離する必要はありません。気にする必要はないんじゃないですか？

**Comment by jucky154** [comment]
自分の送出したものと受信したものの速度が違う場合、解析精度が下がるかなと思いました
一般的にはCQを出している人の速度に合わせようというのが文化（本当に守られているかは知らない… ）なので、大体同じくらいの速度でしょうし、最悪moniを切ればいいので問題ないですね

**Comment by jucky154** [comment]
以上から途切れなくモールスを解読する件は実装

**Comment by jucky154** [comment]
あと一瞬思ったのは、自分の局の音の大きさに比べて相手の応答が小さいとデコードが悪くなってしまう可能性がある。
まぁその辺は複数のパイルを裁く能力でなんとかしてもらうしかないな…
