### ISSUE TITLE
wincの非推奨化

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#99]
## 問題意識

#95 で検討したように、wincやwalkといったWindows GUIライブラリは、[ウィンドウクラス](https://learn.microsoft.com/ja-jp/windows/win32/winmsg/about-window-classes)を[ハードコーディング](https://github.com/tadvi/winc/blob/33fdab6e7e584572a0ddf0313a9d8ec84b07f381/form.go#L32)している。これらのライブラリは、アプリケーション内でウィンドウクラスが重複した場合にpanicを発生するように実装されている。

## 没案

ウィンドウクラスが重複しないようにwincやwalkを改修すれば良いが、これらのライブラリはPRが開きっ放しでメンテナンス状況が悪く、と言って、自前でフォークを提供する気もない。

## 解決方法

`SetClassName`関数を提供している[gonutz/wui/v2](https://pkg.go.dev/github.com/gonutz/wui/v2)等のライブラリへの移行を推奨する。

**Comment by jucky154** [comment]
wincを使っているものについては今週末の土日くらいに移行しておきます

**Comment by JG1VPP** [comment]
この移行は不要になる可能性があります。

**Comment by jucky154** [comment]
jg1vpp/wincを使っている系はcwListener（明日作業予定）をのぞいて、zylo/reiwaのnewFormに移行しました
https://github.com/jucky154/soumuAPI/blob/main/soumuAPI.go
https://github.com/jucky154/infoEs/blob/main/infoEs.go
https://github.com/jucky154/comportlist/blob/main/comportlist.go

**Comment by JG1VPP** [comment]
小文字で始まる変数や関数はプライベートなもので、非推奨です。近日中に`zylo/win32`パッケージに移動します。

**Comment by JG1VPP** [comment]
小文字で始まる変数や関数はプライベートなものです。たまたま`main`パッケージにあるので利用可能なだけで、非推奨です。近日中に`zylo/win32`パッケージに移動します。

**Comment by JG1VPP** [comment]
真意としては、`tadvi/winc`に依存したコードを排除しつつ、`tadvi/winc`や`lxn/walk`等の既存のライブラリに手を加えることなく、ZyLOで利用可能にする方針でしたが、`zylo/win32`パッケージが既成事実化したので、このIssueは閉じます。
